#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PENDING = ROOT / "data" / "pending_audit_next.json"
OUT = ROOT / "data" / "clinical_overrides_wave28_0632_0681.json"
MANIFEST = ROOT / "data" / "manual_final_qa_wave28_0632_0681.json"
EXPECTED = [f"V2-Q{i:04d}" for i in range(632, 682)]

OPTIONS = {
632:("A benign facial asymmetry that requires no further neurologic evaluation","A dermatologic disorder that does not involve facial nerve motor function","Bell palsy causing peripheral facial weakness, while stroke is still excluded","An ischemic stroke diagnosis confirmed solely by isolated facial weakness"),
633:("A routine dental disorder causing continuous pain unrelated to facial triggers","Trigeminal neuralgia causing brief, severe facial pain triggered by light stimuli","Migraine causing prolonged throbbing headache rather than brief facial shocks","Otitis media causing persistent ear pain rather than triggered facial shocks"),
634:("Peripheral artery disease causing exertional pain that improves with resting","Restless legs syndrome causing an urge to move that worsens during rest","A primary psychiatric disorder causing leg movement without a circadian pattern","A normal response to inactivity that requires no further clinical assessment"),
635:("A urinary tract infection causing dysuria without new neurologic deficits","Cauda equina syndrome requiring immediate imaging and surgical evaluation","Uncomplicated sciatica appropriate for routine conservative outpatient care","Mechanical low-back pain appropriate for routine nonurgent follow-up care"),
636:("Use prealbumin alone as a reliable measure of short-term nutrition response","Interpret prealbumin primarily as a marker affected by inflammation and illness","Use prealbumin as a specific marker of total body protein and muscle stores","Prefer prealbumin over clinical assessment because of its shorter half-life"),
637:("A normal or elevated fibrinogen level reliably excludes disseminated intravascular coagulation","Fibrinogen is always profoundly reduced at the earliest stage of disseminated intravascular coagulation","Fibrinogen may fall from consumption, but a normal or elevated value does not exclude DIC","Fibrinogen has no role in evaluating suspected disseminated intravascular coagulation"),
638:("Isolated kidney dysfunction without evidence of hepatocellular involvement","A normal laboratory pattern that requires no assessment of possible liver injury","Possible hepatocellular injury or inflammation requiring clinical evaluation","Normal hepatocyte function despite the substantial transaminase elevations"),
639:("A laboratory pattern unrelated to thyroid function or pituitary regulation","Primary hypothyroidism with low free T4 and compensatory elevation of TSH","Normal thyroid function despite abnormal free T4 and TSH concentrations","Primary hyperthyroidism with excessive thyroid hormone and suppressed TSH"),
640:("A kidney-filtration marker that independently confirms or excludes sepsis","An abnormal marker that may reflect hypoperfusion and should be trended in context","A specific measure proving that tissue oxygen delivery has already improved","A normal metabolic finding that has no relevance during sepsis resuscitation"),
641:("Arterial sampling better assesses oxygenation because PaO2 requires arterial blood","Arterial sampling is used mainly for research rather than bedside oxygenation","Venous sampling provides an equivalent PaO2 for routine oxygenation assessment","Arterial sampling primarily measures glucose and electrolytes rather than gases"),
642:("Mix all crushed medications into the enteral formula before administration","Give all crushed medications together without flushing between medications","Give each medication separately and flush the tube between medications","Combine all medications in one syringe to reduce administration time"),
643:("Place the client flat in a supine position to reduce respiratory effort","Place the client upright in High-Fowler position to support lung expansion","Place the client prone with the head turned to limit chest wall movement","Place the client in Trendelenburg position to increase diaphragmatic pressure"),
644:("Apply continuous suction while inserting and withdrawing the suction catheter","Advance the catheter deeply while applying continuous suction during insertion","Apply intermittent suction during withdrawal, keep each pass brief, and reassess","Perform only one suction pass even when secretions remain after reassessment"),
645:("Use occupied-bed technique, turning the client safely from side to side","Postpone linen changes until the client can get out of bed independently","Remove all linens first and leave the client uncovered during replacement","Ask the immobile client to stand briefly while the linens are replaced"),
646:("Recommend routine PSA screening for all adult men beginning at age eighteen","Treat one elevated PSA result as diagnostic of prostate cancer without workup","Discuss individual PSA screening benefits and harms with men aged 55 to 69","Recommend routine PSA screening for all men aged seventy years and older"),
647:("Assess only whether the lesion is painful and ignore its visible characteristics","Assess asymmetry, border, color, diameter, and whether the lesion is evolving","Assess only lesion color because size and symmetry are not useful warning signs","Assess only lesions larger than six millimeters and ignore changes over time"),
648:("Screen only newborns with a documented family history of childhood hearing loss","Screen all newborns so hearing loss can be identified and addressed early","Delay hearing screening until speech delay becomes apparent in early childhood","Omit routine screening because congenital hearing loss is too uncommon to screen"),
649:("Recurrent binge eating followed by compensatory behaviors such as purging","Persistent caloric restriction without binge eating and with markedly low weight","Occasional overeating during stress without recurrent compensatory behaviors","Sustained food restriction causing low weight without recurrent binge episodes"),
650:("Typical adolescent rebellion without persistent violations of others' rights","A mood disorder defined mainly by sadness without serious behavioral violations","Conduct disorder with persistent aggression, destruction, or serious rule violations","A transient adjustment response without a persistent pattern of harmful behavior"),
651:("A brief adjustment response lasting weeks after a clearly identified stressor","Oppositional defiant disorder with persistent irritability and defiant behavior","Conduct disorder with serious aggression and violations of others' basic rights","A medical illness that does not involve persistent mood or behavioral symptoms"),
652:("LMWH must be given only by continuous intravenous infusion in most patients","LMWH has little anticoagulant effect compared with unfractionated heparin","LMWH has predictable dosing and usually does not require routine aPTT monitoring","LMWH requires daily aPTT testing in every patient receiving subcutaneous doses"),
653:("Inject subcutaneously in the abdomen, keep the air bubble, and do not rub afterward","Inject subcutaneously in the abdomen, then massage the site to increase absorption","Expel the air bubble from the prefilled syringe before giving the abdominal dose","Inject the dose intramuscularly to obtain faster and more predictable absorption"),
654:("Apply the patch to clean, dry, intact skin and rotate sites with replacement","Expose the patch to heating pads, hot tubs, or saunas while it is in place","Inspect the application site and use a different intact skin area next time","Fold used patches adhesive-side together and follow safe disposal instructions"),
655:("Hydromorphone is not an opioid and does not require equianalgesic conversion","Hydromorphone is less potent than morphine on a milligram-for-milligram basis","Hydromorphone and morphine have identical potency for all routes and patients","Hydromorphone is more potent than morphine and requires careful dose conversion"),
656:("Count only intravenous acetaminophen when calculating the daily exposure","Ignore acetaminophen contained in combination products when totaling the dose","Add acetaminophen from all routes and products before checking the daily limit","Double the oral acetaminophen allowance when intravenous doses are also used"),
657:("NSAIDs have no clinically important cardiovascular risk in patients with CVD","NSAIDs can increase the risk of serious cardiovascular thrombotic events","NSAID boxed warnings concern respiratory effects rather than cardiovascular events","NSAIDs reduce future myocardial infarction risk when used regularly for pain"),
658:("Prednisone usually lowers glucose enough to require stopping diabetes therapy","Prednisone has no meaningful effect on glucose during a short treatment course","Prednisone requires routine discontinuation of all existing diabetes medications","Prednisone can raise glucose, requiring closer monitoring and possible adjustment"),
659:("Adjust levothyroxine after each dose according to the client's symptoms that day","Adjust levothyroxine without laboratory monitoring once treatment has started","Use symptoms alone because TSH does not help guide replacement therapy dosing","Use periodic TSH with clinical assessment because dose effects take time to stabilize"),
660:("Monitor weight, glucose, and lipids because atypical antipsychotics can affect metabolism","Monitor only cardiac rhythm because metabolic complications are not clinically relevant","Perform no ongoing monitoring once the antipsychotic dose has remained unchanged","Monitor only visual acuity because weight, glucose, and lipid changes are unrelated"),
661:("Reserve naloxone only for people known to use nonprescribed illicit opioids","Avoid naloxone because offering it discourages appropriate opioid pain treatment","Offer naloxone as harm reduction when overdose risk factors are present","Avoid naloxone because it has no established role with prescribed opioid therapy"),
662:("Stop the medication for every patient without evaluating therapeutic alternatives","Continue usual use until inventory is depleted without a conservation strategy","Use a shortage plan with alternatives, prioritization, and staff communication","Notify prescribers only and allow nursing staff to learn changes informally"),
663:("Treat similar packaging as harmless until an actual medication error occurs","Leave packaging concerns solely to pharmacy and take no nursing safety action","Store look-alike products together because proximity reduces selection errors","Report the look-alike risk and consider separation, labeling, or other safeguards"),
664:("Replace all nursing judgment and independent checks for high-alert medications","Use barcode scanning to verify patient and medication information against the eMAR","Limit barcode scanning to controlled substances and verify other drugs manually","Use barcode scanning primarily for billing rather than medication-error prevention"),
665:("Remove tubing from the pump without clamping because free flow is not hazardous","Use free-flow protection only for enteral tubing rather than intravenous tubing","Use free-flow protection to prevent uncontrolled infusion when tubing leaves the pump","Use free-flow protection only to slow, but not stop, uncontrolled gravity infusion"),
666:("Keep factory alarm limits unchanged because only engineering staff may adjust them","Disable individualized alarm settings because they increase clinically useful alarms","Individualize alarm limits within policy so alarms remain meaningful and safe","Individualize alarm limits only in critical care and never on other monitored units"),
667:("Close the hospital immediately without first defining cases or possible exposures","Wait for more infections before collecting data or implementing control measures","Assume the cluster is coincidental unless every affected patient has the same organism","Define and identify cases, analyze exposures, and implement targeted controls"),
668:("Assume PPE technique is intuitive and does not require competency validation","Validate PPE technique because poor donning or doffing can cause self-contamination","Limit PPE competency checks to periods when a recognized outbreak is occurring","Skip PPE training when staff members have several years of clinical experience"),
669:("Share reusable cuffs and stethoscopes without cleaning when patients appear healthy","Clean shared noncritical equipment weekly regardless of how often it is used","Clean and disinfect shared noncritical equipment between patient uses as indicated","Avoid cleaning reusable equipment because disinfectants damage all device surfaces"),
670:("A professional ethics framework describing nurses' core obligations and values","A student-only document with no relevance after initial nursing licensure","A federal statute that has the force of law in every state and territory","An optional set of suggestions without professional significance in practice"),
671:("A harmless personal relationship that removes the need for professional boundaries","A dual relationship requiring attention to boundaries and the patient's interests","A relationship that automatically requires immediate reassignment in every setting","A personal friendship that permits different confidentiality standards for the patient"),
672:("A single-state license automatically authorizes practice in every other U.S. state","Temporary work in another state never requires additional nursing licensure","A noncompact license permits practice in compact states without further authorization","The nurse must hold authority to practice in the state where nursing care is provided"),
673:("The nurse may ignore the state nurse practice act when employer policy is broader","The nurse's scope is governed only by employer policy rather than nursing regulation","The nurse must practice within the applicable nurse practice act and board rules","The nurse may independently expand scope whenever a unit has a staffing shortage"),
674:("Document evidence handling only after law enforcement receives the specimen","Track evidence only when collection occurs outside a healthcare organization","Document each transfer and handler to preserve evidence integrity and chain of custody","Treat chain-of-custody documentation as optional when evidence is clinically collected"),
675:("Identify sentinel events, analyze causes, and make improvements to reduce recurrence","Report every sentinel event to Joint Commission because reporting is mandatory","Delay analysis until Joint Commission requests documentation from the organization","Take no formal improvement action when the organization chooses not to report externally"),
676:("Delay disclosure until all litigation is complete and facts can no longer change","Communicate honestly and compassionately, explain known facts, and outline next steps","Avoid empathy because expressions of concern are always admissions of legal liability","Assign disclosure to one clinician without organizational support or preparation"),
677:("Ask whether the client understands and accept a yes-or-no response as confirmation","Provide written instructions only and avoid asking the client to explain them","Use teach-back and ask the client to explain key instructions in their own words","Assume understanding from education level rather than checking comprehension"),
678:("Early septic shock always causes cool skin and increased systemic vascular resistance","Septic and cardiogenic shock produce identical hemodynamic patterns in all patients","Neither septic nor cardiogenic shock produces meaningful skin or perfusion changes","Early septic shock may cause warm skin and reduced systemic vascular resistance"),
679:("A mild upper respiratory infection requiring routine outpatient symptom management","Stable chronic heart-failure symptoms that require no urgent reassessment","Expected pulmonary findings that do not require immediate clinical intervention","Acute pulmonary edema requiring urgent assessment and emergency treatment"),
680:("Left-sided heart failure unrelated to the client's chronic pulmonary disease","An isolated renal disorder that fully explains the right-sided congestion findings","Cor pulmonale with right-heart failure related to chronic pulmonary disease","A normal consequence of aging unrelated to chronic pulmonary vascular disease"),
681:("An abdominal disorder causing referred symptoms without an intrathoracic process","Pleural effusion causing dyspnea with reduced breath sounds and dullness","A muscle strain causing unilateral decreased breath sounds and dull percussion","A normal respiratory finding that does not require diagnostic evaluation"),
}

KEYS={632:"C",633:"B",634:"B",635:"B",636:"B",637:"C",638:"C",639:"B",640:"B",641:"A",642:"C",643:"B",644:"C",645:"A",646:"C",647:"B",648:"B",649:"A",650:"C",651:"B",652:"C",653:"A",654:"B",655:"D",656:"C",657:"B",658:"D",659:"D",660:"A",661:"C",662:"C",663:"D",664:"B",665:"C",666:"C",667:"D",668:"B",669:"C",670:"A",671:"B",672:"D",673:"C",674:"C",675:"A",676:"B",677:"C",678:"D",679:"D",680:"C",681:"B"}

SOURCES={
632:("AAFP — Bell Palsy: Rapid Evidence Review","https://www.aafp.org/afp/2023/0400/bell-palsy","Diagnosis: acute unilateral peripheral facial weakness involving the forehead; alternative central causes must be considered; 2023 review, accessed 2026-08-14."),
633:("AAFP — Trigeminal Neuralgia: Rapid Evidence Review","https://www.aafp.org/afp/2025/0500/trigeminal-neuralgia","Clinical presentation: sudden brief electric-shock-like facial pain triggered by benign stimuli; 2025 review, accessed 2026-08-14."),
634:("AASM — Sleep Medicine Elective Toolkit","https://aasm.org/professional-development/choose-sleep/sleep-medicine-elective-toolkit/","RLS definition: urge to move, engendered by stillness, usually evening-predominant and relieved by movement; current AASM resource, accessed 2026-08-14."),
635:("NCBI Bookshelf — Low Back Pain: Evaluation and Management","https://www.ncbi.nlm.nih.gov/books/NBK538173/","Cauda equina red flags: urinary/bowel dysfunction and saddle anesthesia require urgent recognition/evaluation; current 2025/2026 StatPearls edition, accessed 2026-08-14."),
636:("ASPEN — Visceral Proteins terminology guidance","https://nutritioncare.org/definition-of-terms-style-and-conventions-used-in-aspen-board-of-directors-approved-documents/","Visceral Proteins: albumin/prealbumin are inflammation-responsive and should not be used as nutrition markers; accessed 2026-08-14."),
637:("NCBI Bookshelf — Disseminated Intravascular Coagulation","https://www.ncbi.nlm.nih.gov/books/NBK441834/","Evaluation/pathophysiology: consumptive coagulopathy can reduce fibrinogen, but laboratory diagnosis uses a pattern and fibrinogen may not be low early; last update 2024, accessed 2026-08-14."),
638:("NCBI Bookshelf — Liver Function Tests","https://www.ncbi.nlm.nih.gov/books/NBK482489/","AST/ALT are markers of hepatocellular injury; last update June 8, 2026, accessed 2026-08-14."),
639:("American Thyroid Association — Thyroid Function Tests","https://www.thyroid.org/thyroid-function-tests/","Elevated TSH with low free T4 indicates primary hypothyroidism; current patient/clinical education page, accessed 2026-08-14."),
640:("SCCM — Surviving Sepsis Campaign 2026","https://sccm.org/clinical-resources/guidelines/guidelines/surviving-sepsis-campaign-international-guidelines-for-management-of-sepsis-and-septic-shock-2026","Blood lactate/serial lactate recommendations: lactate may reflect impaired perfusion but is nonspecific and must be interpreted in clinical context; 2026 guideline, accessed 2026-08-14."),
641:("NCBI Bookshelf — Arterial Blood Gas Analysis","https://www.ncbi.nlm.nih.gov/books/NBK536919/","PaO2/oxygenation requires arterial sampling; updated 2026 StatPearls, accessed 2026-08-14."),
642:("NCBI Bookshelf — Administration of Enteral Medications","https://www.ncbi.nlm.nih.gov/books/NBK596740/","Administer multiple medications separately and flush between each medication; Nursing Skills, accessed 2026-08-14."),
643:("NCBI Bookshelf — Nursing Fundamentals: Oxygenation","https://www.ncbi.nlm.nih.gov/books/NBK610832/","High-Fowler/tripod positioning promotes chest expansion and reduces work of breathing; 2nd ed. 2024, accessed 2026-08-14."),
644:("NCBI Bookshelf — Nursing Skills: Tracheostomy Care & Suctioning","https://www.ncbi.nlm.nih.gov/books/NBK596713/","Apply suction intermittently during withdrawal; limit suction pass to 10–15 seconds and reassess; accessed 2026-08-14."),
645:("NCBI Bookshelf — Nursing Assistant: Making an Occupied Bed","https://www.ncbi.nlm.nih.gov/books/NBK599387/","Occupied-bed checklist and safe linen-change technique for a client who remains in bed; accessed 2026-08-14."),
646:("USPSTF — Prostate Cancer: Screening","https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/prostate-cancer-screening","Final recommendation May 8, 2018: individualized PSA decision age 55–69; recommend against routine screening age ≥70; update in progress, accessed 2026-08-14."),
647:("American Academy of Dermatology — ABCDEs of Melanoma","https://www.aad.org/public/diseases/skin-cancer/types/common/melanoma/symptoms","ABCDE warning signs: asymmetry, border, color, diameter, evolving; current page, accessed 2026-08-14."),
648:("CDC — EHDI 1-3-6 Benchmarks","https://www.cdc.gov/hearing-loss-children/articles/baby-hearing-screening-infographic.html","All infants should be screened for hearing loss before 1 month of age; May 7, 2025 page, accessed 2026-08-14."),
649:("NCBI Bookshelf — Bulimia Nervosa","https://www.ncbi.nlm.nih.gov/books/NBK562178/","Diagnostic features include recurrent binge eating and inappropriate compensatory behaviors; accessed 2026-08-14."),
650:("NCBI Bookshelf — Conduct Disorder","https://www.ncbi.nlm.nih.gov/books/NBK470238/","Persistent aggression/rights violations, property destruction, deceit/theft, and serious rule violations; accessed 2026-08-14."),
651:("NCBI Bookshelf — Oppositional Defiant Disorder","https://www.ncbi.nlm.nih.gov/books/NBK557443/","Persistent angry/irritable mood, argumentative/defiant behavior, or vindictiveness for at least 6 months; updated 2024, accessed 2026-08-14."),
652:("DailyMed — Enoxaparin Sodium Injection","https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e7568a6-cf8a-4de2-86ba-b94c8ab4c806","Prescribing information/monitoring: routine coagulation tests such as aPTT are not suitable for monitoring LMWH effect; current label updated 2026, accessed 2026-08-14."),
653:("DailyMed — Enoxaparin Sodium Injection","https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e7568a6-cf8a-4de2-86ba-b94c8ab4c806","Instructions for Use: abdominal SC site ≥2 inches from navel; do not remove air bubbles; do not rub site; updated 2026, accessed 2026-08-14."),
654:("DailyMed — Fentanyl Transdermal System","https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2a2238e9-4b5d-c56d-8663-dd354ff9ae0c","Warnings: external heat can increase fentanyl absorption and has resulted in fatal overdose; current label, accessed 2026-08-14."),
655:("DailyMed — Hydromorphone Hydrochloride","https://dailymed.nlm.nih.gov/dailymed/search.cfm?query=hydromorphone","Dosage/conversion guidance: hydromorphone is a potent opioid and conversion from other opioids requires conservative individualized dosing; DailyMed current labeling search, accessed 2026-08-14."),
656:("DailyMed — Acetaminophen Injection","https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1d456d07-fca2-4d43-92c0-f3b3c8b54420","Maximum daily acetaminophen includes all routes and all acetaminophen-containing products; current label 2026, accessed 2026-08-14."),
657:("DailyMed — Ibuprofen Tablets","https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4aefcb3a-5dc8-b88e-e063-6294a90ac044","Boxed Warning: NSAIDs increase risk of serious cardiovascular thrombotic events including MI and stroke; updated May 6, 2026, accessed 2026-08-14."),
658:("NCBI Bookshelf — Corticosteroids","https://www.ncbi.nlm.nih.gov/books/NBK554612/","Corticosteroids can cause dose-dependent hyperglycemia and may require increased glucose monitoring/antihyperglycemic adjustment; accessed 2026-08-14."),
659:("American Thyroid Association — Hypothyroidism","https://www.thyroid.org/hypothyroidism/","Levothyroxine treatment is titrated using thyroid laboratory assessment and clinical status; ATA patient/clinical guidance, accessed 2026-08-14."),
660:("American Diabetes Association — Antipsychotic Drugs and Metabolic Risk","https://diabetesjournals.org/care/article/27/2/596/28450/Consensus-Development-Conference-on-Antipsychotic","Baseline and ongoing weight/BMI, glucose and lipid monitoring recommended with second-generation antipsychotics; consensus guidance, accessed 2026-08-14."),
661:("CDC — Clinical Practice Guideline for Prescribing Opioids for Pain, 2022","https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm","Recommendation 8: mitigate opioid-related harms, including offering naloxone particularly when overdose risk factors are present; accessed 2026-08-14."),
662:("ASHP — Drug Shortages Resource Center","https://www.ashp.org/drug-shortages","Shortage management includes therapeutic alternatives, conservation/prioritization strategies and communication; current resource center, accessed 2026-08-14."),
663:("ISMP — Medication Safety Resources","https://www.ismp.org/resources","Look-alike/sound-alike and packaging risks should be reported and mitigated using system safeguards such as separation/labeling; current resource library, accessed 2026-08-14."),
664:("AHRQ PSNet — Bar Code Medication Administration","https://psnet.ahrq.gov/primer/bar-code-medication-administration","BCMA verifies patient/medication information against the electronic medication record and is used to reduce administration errors; accessed 2026-08-14."),
665:("FDA — Infusion Pumps","https://www.fda.gov/medical-devices/general-hospital-devices-and-supplies/infusion-pumps","Infusion pump safety includes preventing uncontrolled flow and over-infusion; current FDA device safety resource, accessed 2026-08-14."),
666:("Joint Commission — National Performance Goals","https://www.jointcommission.org/en-us/standards/national-performance-goals","2026 performance-goal framework replaces NPSGs; clinical alarm systems require safe management under organization policy; effective Jan 1, 2026, accessed 2026-08-14."),
667:("CDC — Field Epidemiology Manual: Healthcare Settings","https://www.cdc.gov/field-epi-manual/php/chapters/healthcare-settings.html","HAI outbreak investigation: establish case definition, identify/count cases, analyze exposures, implement control measures; accessed 2026-08-14."),
668:("CDC/NIOSH — Donning and Doffing PPE","https://www.cdc.gov/niosh/learning/safetyculturehc/module-3/8.html","Doffing must avoid self-contamination; training and demonstrated correct technique are core safety practices; accessed 2026-08-14."),
669:("CDC — Environmental Cleaning Procedures","https://www.cdc.gov/healthcare-associated-infections/hcp/cleaning-global/procedures.html","Shared noncritical equipment such as cuffs/stethoscopes is cleaned/disinfected before and after patient use as indicated; accessed 2026-08-14."),
670:("ANA — Code of Ethics for Nurses, 2025","https://www.nursingworld.org/nurses-books/Code-of-ethics-2025/","2025 Code expresses nursing's values, virtues, ideals and obligations and guides professional practice; accessed 2026-08-14."),
671:("NCSBN — A Nurse's Guide to Professional Boundaries","https://www.ncsbn.org/brochures-and-posters/nurses-guide-to-professional-boundaries","2024 guidance on professional nurse-client boundaries and boundary crossings/violations; accessed 2026-08-14."),
672:("NCSBN — Nurse Licensure Guidance","https://www.ncsbn.org/nurse-licensure-guidance","Practice is where the patient is; multistate license applies in compact states, while noncompact practice requires applicable state licensure; accessed 2026-08-14."),
673:("NCSBN — Nurse Practice Act Toolkit","https://www.ncsbn.org/policy-gov/npa-toolkit.page","NPA and BON rules guide/govern nursing practice; rules must be consistent with and cannot go beyond the NPA; accessed 2026-08-14."),
674:("OJP — SART Toolkit: Chain of Custody","https://ovc.ojp.gov/sites/g/files/xyckuh226/files/pubs/OVC_Archives/sartkit/develop/issues-coc.html","Evidence integrity requires documented chain of custody, including handlers/transfers and identifying details; accessed 2026-08-14."),
675:("Joint Commission — Sentinel Event FAQs","https://www.jointcommission.org/en-us/knowledge-library/sentinel-events/sentinel-event-faqs","Reporting remains voluntary; accredited organizations are expected to identify sentinel events, examine root causes/contributing factors, and improve systems; accessed 2026-08-14."),
676:("AHRQ — CANDOR Disclosure Checklist","https://www.ahrq.gov/patient-safety/settings/hospital/candor/modules/checklist5.html","Disclosure communication: explain known facts honestly, avoid speculation, show empathy, apologize appropriately, and outline follow-up/next steps; accessed 2026-08-14."),
677:("AHRQ — Use the Teach-Back Method","https://www.ahrq.gov/health-literacy/improve/precautions/tool5.html","Teach-back checks understanding by asking the patient/caregiver to explain information in their own words; 3rd edition toolkit, accessed 2026-08-14."),
678:("NCBI Bookshelf — Shock Resuscitation","https://www.ncbi.nlm.nih.gov/books/NBK534830/","Septic shock typically lowers SVR with a hyperdynamic/warm phase; cardiogenic shock lowers output and raises SVR; accessed 2026-08-14."),
679:("NCBI Bookshelf — Pulmonary Edema","https://www.ncbi.nlm.nih.gov/books/NBK557611/","Acute pulmonary edema presents with worsening dyspnea, hypoxia, crackles and sometimes pink frothy sputum and requires urgent management; accessed 2026-08-14."),
680:("NCBI Bookshelf — Cor Pulmonale","https://www.ncbi.nlm.nih.gov/books/NBK430739/","Cor pulmonale is right-ventricular structural/functional impairment caused by pulmonary disease/pulmonary hypertension; COPD is a common cause; accessed 2026-08-14."),
681:("NCBI Bookshelf — Pleural Effusion","https://www.ncbi.nlm.nih.gov/books/NBK448189/","Pleural effusion may produce dyspnea, decreased breath sounds/fremitus and percussion dullness; accessed 2026-08-14."),
}

SPECIAL={
636:{"stem":"A severely ill client has a low serum prealbumin concentration. Which interpretation is most consistent with current ASPEN guidance?","rationale":"Prealbumin (transthyretin) is strongly affected by inflammation and illness. ASPEN advises that visceral proteins such as albumin and prealbumin should not be used as stand-alone nutrition markers or proxies for total body protein. Nutrition assessment should integrate clinical history, intake, weight/body-composition findings and the inflammatory context."},
637:{"stem":"A client with suspected disseminated intravascular coagulation (DIC) has a fibrinogen value that is still within the reference range. Which interpretation is most accurate?","rationale":"DIC consumes platelets and coagulation factors, and fibrinogen can decrease as consumption progresses. However, fibrinogen is also an acute-phase reactant and may remain normal or elevated, especially earlier in the process. A normal fibrinogen value therefore does not exclude DIC; diagnosis relies on the clinical setting and a pattern of serial coagulation findings."},
640:{"stem":"A client with suspected sepsis has an elevated serum lactate level. How should the nurse interpret this result?","rationale":"Serum lactate is used in sepsis assessment and resuscitation because elevation may accompany tissue hypoperfusion and physiologic stress. It is not specific for sepsis or anaerobic metabolism, and an isolated value cannot confirm or exclude sepsis. Elevated lactate should be trended when indicated and interpreted with the full clinical picture."},
646:{"stem":"An asymptomatic 60-year-old man asks whether he should have PSA-based screening for prostate cancer. Which response best matches the current final USPSTF recommendation?","rationale":"The current final USPSTF recommendation (May 8, 2018; update in progress as of 2026-08-14) recommends individualized decision-making for PSA-based screening in men aged 55–69 after discussion of benefits and harms. It recommends against routine PSA-based screening in men aged 70 years or older."},
653:{"stem":"A nurse teaches a client how to self-administer enoxaparin from a prefilled syringe. Which technique is appropriate?","rationale":"Current enoxaparin instructions direct subcutaneous abdominal injection, generally at least 2 inches from the umbilicus, without removing the prefilled syringe's air bubble and without rubbing the site afterward. Intramuscular administration and post-injection massage are inappropriate."},
672:{"stem":"A nurse licensed in one U.S. state plans to provide nursing care to patients located in another state. Which licensure principle is most accurate?","rationale":"NCSBN states that nursing practice occurs where the patient is located. A multistate license authorizes practice in participating compact states when eligibility requirements are met; practice in a noncompact state requires the applicable single-state authority to practice."},
673:{"stem":"A unit policy appears to permit an RN to perform an activity that the nurse is unsure is authorized by the state nurse practice act. Which principle should guide the nurse's decision?","rationale":"The nurse must practice within the applicable nurse practice act and board of nursing rules. Employer policy cannot lawfully expand nursing scope beyond state law or regulation. The nurse should also consider education, competence and other applicable standards before performing an activity."},
675:{"stem":"A sentinel event occurs at a Joint Commission-accredited hospital. A staff member believes no formal review is needed if the organization chooses not to report it to Joint Commission. Which response is accurate?","rationale":"Joint Commission states that reporting sentinel events to Joint Commission remains voluntary. However, accredited organizations are expected to identify sentinel events, examine root causes and contributing factors, and make improvements that reduce the risk of recurrence. Choosing not to report externally does not remove the organization's internal patient-safety responsibilities."},
}

FLAGS=["MANUAL_ITEM_BY_ITEM_AUDIT","SOURCE_CURRENTNESS_CHECKED","KEY_VERIFIED","DISTRACTORS_REVIEWED","RATIONALE_VERIFIED","AMBIGUITY_REVIEWED","SECOND_PASS_MANUAL_QA"]

def qc(uid:str, options:dict[str,str], key:str)->dict:
    lengths={k:len(options[k].strip()) for k in "ABCD"}
    minimum=min(lengths.values()); maximum=max(lengths.values())
    ratio=maximum/max(minimum,1)
    dmean=sum(v for k,v in lengths.items() if k!=key)/3
    dev=abs(lengths[key]-dmean)/max(dmean,1)
    if ratio>1.15+1e-9 or dev>0.10+1e-9:
        raise SystemExit(f"Option-length gate failed for {uid}: ratio={ratio:.4f}, key_dev={dev:.4f}, lengths={lengths}")
    rank=sorted(lengths.values()).index(lengths[key])+1
    return {"question_uid":uid,"lengths_json":json.dumps(lengths,separators=(",",":")),"min_chars":minimum,"max_chars":maximum,"max_min_ratio":round(ratio,4),"correct_option":key,"correct_length_rank":rank,"correct_is_extreme":int(lengths[key] in (minimum,maximum)),"qc_status":"PASS","qc_note":f"Manual item-by-item cue review; strict quantitative check passed: max/min={ratio:.4f} <= 1.15; correct-vs-distractor-mean deviation={dev:.4f} <= 0.10.","correct_vs_distractor_mean_deviation":round(dev,4)}

def main()->None:
    payload=json.loads(PENDING.read_text(encoding="utf-8"))
    rows=payload.get("questions",[])
    ids=[r.get("question_uid") for r in rows]
    if payload.get("range") != [632,681] or len(rows)!=50 or ids!=EXPECTED:
        raise SystemExit(f"Pending scope mismatch: range={payload.get('range')} count={len(rows)} first={ids[:1]} last={ids[-1:]}")
    questions=[]; manifest_items=[]
    for row in rows:
        uid=row["question_uid"]; n=int(uid[-4:]); key=KEYS[n]
        options={k:v for k,v in zip("ABCD",OPTIONS[n])}
        source_name,source_url,source_detail=SOURCES[n]
        item=dict(row)
        item.update(SPECIAL.get(n,{}))
        item.update({
            "item_data_json":json.dumps({"options":options},ensure_ascii=False,separators=(",",":")),
            "correct_answer_json":json.dumps({"correct_option":key},separators=(",",":")),
            "source_name":source_name,"source_url":source_url,"source_detail":source_detail,
            "clinical_qa_status":"SOURCE_VERIFIED_2026_WAVE28_ITEM_BY_ITEM",
            "editorial_priority":"PRODUCTION_CANDIDATE",
            "editorial_flags_json":json.dumps(FLAGS,separators=(",",":")),
            "qc":qc(uid,options,key),
        })
        questions.append(item)
        manifest_items.append({"question_uid":uid,"manual_disposition":"PASS","all_11_dimensions":True,"second_pass_verified":True,"source_url":source_url,"source_locator":source_detail})
    OUT.write_text(json.dumps({"version":"2026-08-14-wave28-manual-item-audit","questions":questions},ensure_ascii=False,indent=2),encoding="utf-8")
    MANIFEST.write_text(json.dumps({"batch":"WAVE28_Q0632_Q0681","audit_date":"2026-08-14","reviewer":"OpenAI GPT-5.6 Sol — manual item-by-item clinical/source review","method":"Manual semantic review item-by-item; scripts only persist and enforce evidence/structure/quantitative cue gates.","items":manifest_items},ensure_ascii=False,indent=2),encoding="utf-8")
    print("Wave28 audited payload built: 50/50; manual source/key/rationale/distractor review recorded; option metrics strict PASS 50/50")

if __name__=="__main__": main()
