#!/usr/bin/env python3
from __future__ import annotations
import json, re, sqlite3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DB=ROOT/'NCLEX_COMMERCIAL_MASTER_CURRENT.db'
PENDING=ROOT/'data/pending_audit_next.json'
EVIDENCE=ROOT/'data/rule1_batch010_chronological_reaudit_evidence_q0451_q0500.json'
OVERRIDE=ROOT/'data/clinical_overrides_zzz_rule1_batch010_chronological_q0451_q0500_20260815.json'
PATCHES=[ROOT/f'data/manual_rule1_batch010_q{s:04d}_q{s+9:04d}_20260815.json' for s in (451,461,471,481,491)]
IDS=[f'V2-Q{i:04d}' for i in range(451,501)]
REVIEW_DATE='2026-08-15'; STATUS='SOURCE_VERIFIED_2026_RULE1_BATCH010_CHRONOLOGICAL_MANUAL'
NCSBN_URL='https://www.nclex.com/files/2026_RN_Test%20Plan_English-F.pdf'
NCSBN_VERSION='2026 NCLEX-RN Test Plan; effective 2026-04-01 through 2029-03-31; currentness rechecked 2026-08-15.'
CRITERIA=['source_authority_verified','source_currentness_verified','exact_locator_verified','stem_factual_accuracy_verified','correct_answer_verified','rationale_verified','distractors_verified','ambiguity_cue_second_answer_qc_verified','blueprint_topic_difficulty_verified','no_unresolved_conflicts','independent_second_pass_qa']
NEEDS={2:'Management of Care',3:'Safety & Infection Prevention and Control',4:'Health Promotion and Maintenance',5:'Psychosocial Integrity',7:'Basic Care and Comfort',8:'Pharmacological and Parenteral Therapies',9:'Reduction of Risk Potential',10:'Physiological Adaptation'}
NCSBN_LOCATORS={
2:'Client Needs — Safe and Effective Care Environment — Management of Care: prioritization, assignment/delegation, advocacy/client rights, continuity/referral, legal scope, professional limitations and emergency/quality-management activities as applicable.',
3:'Client Needs — Safe and Effective Care Environment — Safety and Infection Prevention and Control: transmission precautions, PPE, device/environmental safety, asepsis, identification and infection-prevention activities as applicable.',
4:'Client Needs — Health Promotion and Maintenance: preventive screening, age/risk-appropriate teaching, developmental and health-promotion activities as applicable.',
5:'Client Needs — Psychosocial Integrity: mental-health symptom recognition, therapeutic communication, coping, cultural/spiritual influences and psychosocial support as applicable.',
7:'Client Needs — Physiological Integrity — Basic Care and Comfort: mobility, assistive devices, hygiene, nutrition, elimination, comfort and nonpharmacological basic-care activities as applicable.',
8:'Client Needs — Physiological Integrity — Pharmacological and Parenteral Therapies: medication administration, adverse effects/interactions, monitoring, reconciliation and teaching.',
9:'Client Needs — Physiological Integrity — Reduction of Risk Potential: diagnostic/laboratory interpretation, transfusion risk, postprocedure monitoring, device management and potential complications.',
10:'Client Needs — Physiological Integrity — Physiological Adaptation: acute/complex alterations, emergency response and pathophysiologic adaptation.'}
# Static author decisions from the fresh Rule 1 item-by-item review. The code below only materializes them.
TARGET_KEYS={451:'B',452:'C',453:'D',454:'A',455:'B',456:'C',457:'D',458:'A',459:'B',460:'C',461:'D',462:'A',463:'B',464:'C',465:'D',466:'A',467:'B',468:'C',469:'D',470:'A',471:'B',472:'C',473:'D',474:'A',475:'B',476:'C',477:'D',478:'A',479:'B',480:'C',481:'D',482:'A',483:'B',484:'C',485:'D',486:'A',487:'B',488:'C',489:'D',490:'A',491:'B',492:'C',493:'D',494:'A',495:'B',496:'C',497:'D',498:'A',499:'B',500:'C'}
CATEGORY_PATCH={477:5,494:8,495:3,500:10}
AUTHORED_OPTIONS={
451:['Assess immediate safety and urgent needs, use calm supportive listening, and connect the client with appropriate crisis resources.','Complete a comprehensive lifetime psychiatric history before asking about immediate safety concerns.','Begin long-term psychotherapy goals before identifying the immediate problem that precipitated the crisis.','Encourage the client to manage the crisis independently before assessing available supports or urgent risk.'],
452:['Obtain baseline and follow-up pulmonary assessment, thyroid studies, and liver testing while monitoring clinically for toxicity.','Monitor serum glucose and hemoglobin A1c as the principal organ-toxicity surveillance throughout therapy.','Monitor renal ultrasound and urine protein as the primary tests for the major toxicities of amiodarone.','After the baseline ECG, no organ-specific surveillance is needed unless the prescribed dose is increased.'],
453:['Cough can still occur, but it was less frequent with losartan than lisinopril in trials of patients who previously had ACE-inhibitor cough.','A previous ACE-inhibitor cough makes losartan contraindicated even when there was no angioedema.','Losartan is expected to cause cough at approximately the same frequency as lisinopril in this situation.','Losartan prevents cough completely, so any cough after the switch must have a nonmedication cause.'],
454:['Diabetic ketoacidosis should still be evaluated because SGLT2-associated ketoacidosis may occur with glucose below 250 mg/dL.','Hyperosmolar hyperglycemic state is established by the glucose value of 210 mg/dL without additional testing.','Hypoglycemia is the likely metabolic emergency because SGLT2-related ketoacidosis requires glucose above 300 mg/dL.','The symptoms can be attributed to medication intolerance without checking ketones or acid-base status at this glucose level.'],
455:['Acute pancreatitis should be suspected when severe persistent abdominal pain may radiate to the back, with or without vomiting.','Expected early satiety is the best explanation for severe persistent pain that radiates to the back.','Injection-site irritation typically causes severe upper-abdominal pain accompanied by nausea and vomiting.','Isolated hypoglycemia characteristically presents as persistent abdominal pain radiating to the back.'],
456:['Vitamin B12 deficiency should be considered during long-term metformin therapy, particularly with compatible hematologic or neurologic findings.','Iron overload is a recognized cumulative effect of metformin and commonly produces distal paresthesias.','Vitamin C toxicity is expected after prolonged metformin use because the drug increases vitamin C absorption.','Folate excess is the characteristic nutritional complication responsible for neuropathy during metformin therapy.'],
457:['Hypomagnesemia should be considered because prolonged proton-pump-inhibitor therapy can produce clinically important magnesium depletion.','Hypermagnesemia is expected because proton-pump inhibitors substantially increase intestinal magnesium absorption.','Hypernatremia is the characteristic electrolyte effect of prolonged gastric acid suppression.','Hypercalcemia is the typical mineral abnormality that explains muscle twitching during long-term PPI treatment.'],
458:['Further QT prolongation and torsades-type ventricular arrhythmia are important concerns in a client with an already prolonged QT interval.','Azithromycin generally shortens the QT interval, so the prescription reduces torsades risk in this client.','The principal electrophysiologic concern is progressive PR shortening rather than ventricular rhythm disturbance.','A preexisting prolonged QT interval does not materially change cardiac risk when azithromycin is prescribed.'],
459:['Tramadol can increase seizure risk at recommended doses, and risk is greater in clients with epilepsy or a history of seizures.','Tramadol raises the seizure threshold and is preferred when analgesia is needed in a client with epilepsy.','Seizure risk with tramadol is limited to subtherapeutic dosing and is not relevant at recommended doses.','Concurrent antiseizure medication eliminates the seizure risk associated with tramadol.'],
460:['Monitor for excessive sedation and respiratory depression because opioids can add to gabapentin-related central nervous system and respiratory depression.','Monitor primarily for severe hypertension because the combination predictably increases systemic vascular resistance.','Monitor for marked psychomotor stimulation because opioids reverse the sedating effects of gabapentin.','Monitor for serotonin syndrome because gabapentin acts as a strong serotonin reuptake inhibitor when combined with an opioid.'],
461:['Skin atrophy with striae and telangiectasia is consistent with local toxicity from prolonged use of a high-potency topical corticosteroid.','Hyperkeratosis with progressive skin thickening is the characteristic local toxicity of prolonged clobetasol use.','Dependent edema is the expected local adverse effect that produces striae and visible superficial vessels.','Lichenification is the typical corticosteroid-induced change caused by increased dermal collagen production.'],
462:['Meticulous cleaning followed by at least high-level disinfection is required before a reusable flexible bronchoscope is used again.','Low-level surface disinfection is adequate when the bronchoscope was used in a client without a known infection.','High-level disinfection can be performed effectively without prior cleaning of the bronchoscope channels.','Reprocessing the exterior surface is sufficient because internal channels do not contact mucous membranes.'],
463:['Handle contaminated linen with minimum agitation and contain it at the point of use, using leak-resistant containment when indicated.','Sort contaminated linen in the client room before bagging so heavily soiled pieces can be separated early.','Shake contaminated linen before bagging to remove loose material and reduce the laundry load.','Prerinse contaminated linen in the patient-care area before placing it in the transport container.'],
464:['Classify the dressing as regulated waste because it would release blood in a liquid or semiliquid state if compressed.','Classify it as sharps waste because any item containing visible blood belongs in a puncture-resistant sharps container.','Classify it as pharmaceutical waste because blood-contaminated material is disposed through the medication-waste stream.','Classify it as ordinary solid waste because dressings are excluded from regulated waste regardless of saturation.'],
465:['Make hepatitis B vaccination available at no cost to employees with occupational exposure, subject to the standard’s stated exceptions.','Make seasonal influenza vaccination available at no cost because it is the vaccine specified by the Bloodborne Pathogens Standard.','Make MMR vaccination available because it is the required postexposure vaccine for occupational blood exposure.','Make Tdap vaccination available because it is the vaccine OSHA specifically mandates for bloodborne-pathogen exposure.'],
466:['Use a hierarchy of administrative measures, environmental controls, and respiratory protective equipment for healthcare TB infection control.','Use contact precautions, surgical hand antisepsis, and environmental surface disinfection as the three levels of TB control.','Use staff antibiotic prophylaxis, ultraviolet exposure, and elimination of symptom screening as the three control levels.','Use standard precautions alone, because a separate respiratory-protection component is not part of healthcare TB control.'],
467:['A fit-tested N95 is a tight-fitting respirator designed to filter airborne particles; a surgical mask does not provide the same fitted respiratory protection.','A surgical mask provides a tighter face seal than an N95 and is preferred for inhalation protection from airborne TB.','An N95 and a surgical mask provide equivalent filtration and fit when both are worn correctly.','An N95 is intended for splash protection but does not filter small airborne particles.'],
468:['Wear a gown or protective apron and gloves appropriate for terminal cleaning in a Contact Precautions environment.','Wear gloves alone because clothing protection is unnecessary once the client has left the room.','Wear a surgical mask and eye protection without gloves because Contact Precautions apply only while the client is present.','Wear an N95 respirator without gown or gloves because airborne protection replaces contact-barrier PPE during terminal cleaning.'],
469:['Close and replace the sharps container at the designated fill line rather than allowing it to overfill.','Push the existing sharps downward with a tool to create room before replacing the container.','Transfer the contents into a larger sharps container so the original container can remain in service.','Continue using the container until the opening is physically blocked, then close and replace it.'],
470:['Board-of-nursing discipline is possible and may include remediation, restrictions, suspension, or revocation depending on law and the facts.','The consequence is limited to employer counseling because Nurse Practice Acts are not enforced by boards of nursing.','A scope violation automatically produces permanent license revocation regardless of severity or jurisdiction.','A scope violation automatically produces a criminal conviction before any regulatory investigation occurs.'],
471:['Verify the current renewal requirements of the licensing jurisdiction because continuing-competency, education, and other requirements vary by jurisdiction.','Retake the NCLEX at every routine renewal because re-examination is a universal renewal requirement.','Use the renewal requirements from the state of original licensure even when the active license is issued by another jurisdiction.','Assume the license remains active indefinitely unless the employer requests a renewal.'],
472:['Nursing peer review is a systematic assessment by nursing peers of the quality and appropriateness of nursing care against professional standards.','Peer review is the manager’s annual employment-performance appraisal of a nurse’s attendance, goals, and job performance.','Peer review is informal feedback between coworkers that is not intended to assess practice against professional standards.','Peer review is the credentialing process used to verify an applicant’s initial education and licensure before employment.'],
473:['Base the staffing mix on patient care needs and acuity together with staff scope, education, skills, competencies, and relevant unit factors.','Base the staffing mix primarily on staff seniority because competency differences are addressed after assignments are made.','Use the same staffing pattern throughout the shift even when patient acuity and required competencies change.','Base assignments primarily on staff scheduling preferences when the planned head count has been met.'],
474:['Document assessments and care accurately, objectively, and promptly, and correct errors through the approved traceable record process.','Document planned interventions before they are performed when the nurse expects to complete them by the end of the shift.','Delete an inaccurate electronic entry so the original information is no longer visible in the record.','Limit documentation to medications and procedures because patient responses are not part of the legal health record.'],
475:['Reporting the near miss can reveal contributing factors and system weaknesses before a similar event causes patient harm.','A near miss confirms that existing safety controls are adequate, so additional review can distort performance data.','Near misses are useful mainly for identifying which individual should be disciplined when no patient harm occurred.','Safety reporting should be limited to events that cause injury because no learning can come from intercepted errors.'],
476:['Request a healthcare ethics consultation to help clarify values, options, and ethically supportable approaches to the disagreement.','Request risk management to determine which party is legally liable before the treatment values and goals are clarified.','Request a routine discharge-planning conference even though the unresolved issue is an ethical conflict about treatment.','Request security to resolve the disagreement because treatment-value conflicts are primarily behavioral-management problems.'],
477:['Use ongoing self-reflection about bias, power, and assumptions while learning from the individual patient’s experiences, values, and preferences.','Apply a previously learned cultural profile to predict the patient’s preferences without asking about individual differences.','Avoid discussing culture or bias so the nurse’s own values cannot influence the interaction.','Treat completion of cultural-competence training as permanent mastery of the beliefs of patients from that group.'],
478:['Weight loss despite increased appetite, heat intolerance, sweating, and a rapid or irregular heartbeat.','Weight gain, cold intolerance, constipation, and a slowed heart rate.','Central weight gain, rounded face, purple striae, and proximal muscle weakness.','Weight loss, hyperpigmentation, salt craving, and persistent hypotension.'],
479:['A rounded face with upper-body weight gain and increased fat over the upper back.','Diffuse hyperpigmentation with weight loss, salt craving, and persistent hypotension.','Enlarged hands and jaw with coarse facial features and increased shoe size.','Cold intolerance, bradycardia, constipation, and generalized weight gain.'],
480:['Water retention with hypotonic hyponatremia and urine that remains inappropriately concentrated.','Free-water loss with hypernatremia and persistently dilute urine.','Isotonic volume depletion with hypernatremia and maximally concentrated urine from appropriate vasopressin release.','Hypertonic hyponatremia with maximally dilute urine caused by complete suppression of vasopressin.'],
481:['A pancreatic pseudocyst or other post-pancreatitis pancreatic fluid collection requiring further evaluation.','Uncomplicated resolution of pancreatitis, because a new palpable abdominal mass is expected during recovery.','Renal colic, because a pancreatic complication would not persist for several weeks after acute pancreatitis.','Acute appendicitis, because post-pancreatitis fluid collections do not cause persistent upper-abdominal pain.'],
482:['Gastroesophageal varices that can bleed as portosystemic collateral veins enlarge.','Peripheral edema caused mainly by reduced plasma oncotic pressure from low albumin.','Prolonged INR caused by reduced hepatic synthesis of clotting factors.','Hepatorenal syndrome caused by advanced circulatory and renal dysfunction in decompensated cirrhosis.'],
483:['Hematochezia usually suggests a lower gastrointestinal source, but a brisk upper gastrointestinal bleed can also present this way.','Hematochezia localizes the source specifically to the rectum regardless of the client’s hemodynamic status.','Hematochezia is more typical of an upper gastrointestinal source than a lower gastrointestinal source.','Hematochezia provides no useful localization information because upper and lower sources are equally likely.'],
484:['The findings may represent an MS relapse and warrant evaluation, including assessment for infection, fever, heat, or another pseudo-relapse trigger.','The symptoms are a pseudo-relapse because any new neurologic symptom lasting more than 24 hours is caused by heat or infection.','The symptoms are routine daily fluctuation and do not require assessment when they persist for two days.','The symptoms establish permanent disease progression because an MS relapse cannot cause new visual or sensory findings.'],
485:['Guillain-Barré syndrome, with close monitoring for progression and respiratory muscle weakness.','Myasthenia gravis, which classically causes ascending symmetric weakness beginning in the legs after respiratory infection.','Multiple sclerosis, which typically produces rapidly ascending symmetric paralysis with respiratory failure over days.','A localized musculoskeletal strain, which best explains progressive bilateral weakness moving upward from the legs.'],
486:['The INR is below the prescribed therapeutic range and indicates inadequate anticoagulant effect for this warfarin regimen.','The INR is within the usual therapeutic range for nonvalvular atrial fibrillation treated with warfarin.','The INR is above the therapeutic range and indicates excessive anticoagulant effect.','The INR cannot be used to assess warfarin because vitamin K antagonist effect is monitored with aPTT.'],
487:['The bone marrow is increasing red blood cell production to replace cells lost through hemorrhage.','The bone marrow is suppressing erythropoiesis despite the recent blood loss.','The finding reflects increased platelet production rather than a red-cell marrow response.','The result indicates iron overload caused by the recent hemorrhage.'],
488:['Vitamin B12 or folate deficiency, which can produce megaloblastic macrocytic anemia.','Iron deficiency, which characteristically produces macrocytosis as iron stores fall.','Thalassemia trait, which characteristically produces a high MCV from enlarged red cells.','Anemia of chronic disease, which is defined by marked macrocytosis from folate trapping.'],
489:['Low hemoglobin with microcytosis and a low ferritin level.','Low hemoglobin with macrocytosis and a low vitamin B12 level.','Low hemoglobin with normocytosis and an elevated ferritin level in an inflammatory state.','Normal hemoglobin with macrocytosis and increased body iron stores.'],
490:['Group O red blood cells lack A and B antigens and can be used for recipients of other ABO groups when emergency red-cell transfusion is required before typing is known.','Group O red blood cells are universal recipients and can receive red cells from every ABO group.','Group O red blood cells express both A and B antigens, which makes them compatible with all recipients.','AB plasma and group O red cells use the same ABO compatibility rule because plasma and red-cell compatibility are interchangeable.'],
491:['The average size or volume of circulating red blood cells.','The total number of circulating red blood cells in a measured blood volume.','The average amount of hemoglobin contained in each red blood cell.','The percentage of blood volume occupied by red blood cells.'],
492:['Assess the client’s mobility and assistance needs, then use appropriate assistive equipment and additional staff when indicated.','Use a gait belt and perform a one-person transfer before determining whether the client can bear weight.','Manually lift the client’s full body weight when the transfer distance is short and a second nurse is nearby.','Begin the transfer without equipment, then add a device only if the client becomes unstable while standing.'],
493:['Record the wound’s precise location, size, wound-bed and periwound findings, drainage, pain, and other relevant assessment characteristics.','Record the wound stage and a photograph only; measurements and drainage characteristics can be added at discharge.','Record the dressing type and pain score only because wound-bed and surrounding-skin findings are treatment rather than assessment data.','Delay the baseline description until the first scheduled dressing change so admission findings do not affect later comparisons.'],
494:['Review the complete medication regimen, including prescription drugs, OTC products, and supplements, for adverse effects, interactions, duplication, and management problems.','Review only medications prescribed by the admitting clinician because drugs from other prescribers are outside the current medication review.','Stop the oldest medications first because duration of therapy is the primary criterion for deprescribing in polypharmacy.','Assume the regimen is safe when every drug was prescribed by a licensed clinician, even when several prescribers are involved.'],
495:['Remove tripping hazards, improve lighting, and install bathroom grab bars or other appropriate home-safety supports.','Limit routine walking inside the home so the older adult has fewer opportunities to experience a fall.','Keep familiar throw rugs in walking paths while adding brighter lighting to improve visual contrast.','Use loose backless slippers indoors because they are easier to remove if balance is lost.'],
496:['Wear a seat belt on every trip because consistent restraint use substantially reduces the risk of serious crash-related injury or death.','Reserve seat-belt use mainly for highway travel because short local trips have minimal serious-injury risk.','Adults seated in the rear seat can omit seat belts when the vehicle has front and side airbags.','Seat belts are primarily a pediatric intervention and add little protection after a passenger reaches adulthood.'],
497:['Keep the 4-month-old out of direct sunlight when possible, use shade and protective clothing, and ask the pediatrician before applying sunscreen.','Use sunscreen as the primary protection for the infant because shade and clothing provide insufficient ultraviolet protection.','Provide brief direct midday sun exposure each day because infants younger than 6 months are less susceptible to sunburn.','Apply an adult sunscreen routinely to all exposed skin before using shade or protective clothing.'],
498:['Teach community members to recognize mental-health or substance-use challenges, provide initial support, and help connect the person with appropriate care.','Teach community members to diagnose psychiatric disorders and select definitive treatment plans independently.','Train nonclinicians to replace professional services by providing ongoing psychotherapy and medication management.','Teach participants to avoid responding until a licensed clinician is physically present.'],
499:['Speak calmly and use simple grounding cues that orient the client to the present situation and current surroundings.','Ask for a detailed narrative of the traumatic event while the flashback is occurring so the memory can be processed immediately.','Leave the client alone until the episode ends because interaction generally prolongs trauma-related flashbacks.','Challenge the accuracy of the traumatic memory during the flashback to help the client distinguish it from current reality.'],
500:['Alcohol withdrawal delirium, a severe withdrawal syndrome requiring prompt medical treatment and close monitoring.','Hepatic encephalopathy, which is established by tremor and hallucinations after abrupt alcohol cessation without further evaluation.','Wernicke encephalopathy, which is defined by marked autonomic hyperactivity and hallucinations after stopping alcohol.','A primary psychotic disorder, which is more likely than withdrawal when severe tremor and autonomic hyperactivity follow alcohol cessation.']}
STEM_PATCH={
453:'A client stopped lisinopril because of a persistent ACE-inhibitor cough and is starting losartan. Which teaching about cough is most accurate?',
482:'In a client with cirrhosis, portal hypertension promotes formation of portosystemic collateral vessels. Which complication most directly reflects enlargement of those collateral veins?',
490:"During an emergency red-cell transfusion before the recipient's ABO type is known, why may group O red blood cells be selected?"}
RATIONALE_PATCH={
453:'DailyMed losartan labeling reports controlled trials in patients with prior ACE-inhibitor cough in which cough occurred less frequently with losartan than with lisinopril. A prior cough alone is not equivalent to a contraindication to an ARB.',
482:'Portal hypertension drives formation and dilation of portosystemic collateral veins, including gastroesophageal varices, which can rupture and bleed. The stem was narrowed to collateral-vessel formation so the keyed complication is anatomically specific and does not create a second-answer problem with other decompensation findings.',
490:'AABB identifies type O red blood cells as emergency red-cell units that can be given when the recipient’s ABO type is not yet known. The final item is deliberately limited to ABO red-cell compatibility and does not overgeneralize Rh selection or plasma compatibility.'}
SOURCE_PATCH={
452:('DailyMed/FDA — Amiodarone Hydrochloride Tablets','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=f3e631c5-1204-419c-8dbe-fa9b37a77f97','Warnings and Precautions §§5.2 Pulmonary Toxicity, 5.3 Hepatic Injury, and 5.6 Thyroid Abnormalities; baseline and follow-up monitoring recommendations.','Revised 06/2026; live DailyMed label currentness rechecked 2026-08-15.'),
453:('DailyMed/FDA — Losartan Potassium','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e5886220-43b7-46e1-9034-5242ba245bd1&version=25','Adverse Reactions — Cough: controlled trials in patients with prior ACE-inhibitor cough compare losartan with lisinopril.','DailyMed version 25; currentness rechecked 2026-08-15.'),
454:('DailyMed/FDA — JARDIANCE (empagliflozin)','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5777b8a8-ada6-4950-8548-43a1de11f075','Warnings and Precautions §5.1 — Ketoacidosis; evaluate compatible symptoms regardless of presenting blood glucose.','Revised 01/2026; live DailyMed label currentness rechecked 2026-08-15.'),
455:('DailyMed/FDA — OZEMPIC (semaglutide)','https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?matchtype=e&setid=adec4fd2-6858-4c99-91d4-531f5f2a2d79','Warnings and Precautions §5.2 — Acute Pancreatitis; characteristic severe persistent abdominal pain, sometimes radiating to the back.','Current 2026 DailyMed/FDA labeling; currentness rechecked 2026-08-15.'),
456:('DailyMed/FDA — Metformin Hydrochloride','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=9eebed09-2562-4d21-b3b3-c06562fe3f99&version=8','Warnings and Precautions §5.2 — Vitamin B12 Deficiency.','Revised 07/2026, version 8; currentness rechecked 2026-08-15.'),
457:('DailyMed/FDA — Pantoprazole Sodium','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=f403c94d-68b7-43df-8c8e-c9fef3309cfc&version=1','Warnings and Precautions §5.8 — Hypomagnesemia and Mineral Metabolism.','Revised 06/2026, version 1; currentness rechecked 2026-08-15.'),
458:('DailyMed/FDA — Azithromycin','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=661ff7a6-6394-493d-a307-a1f607e5d117','Warnings and Precautions §5.4 — QT Prolongation; torsades de pointes and risk factors.','Revised 06/2026; live DailyMed label currentness rechecked 2026-08-15.'),
459:('DailyMed/FDA — Tramadol Hydrochloride','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=5199132e-745e-46a0-8068-e06d1bca5c61','Warnings and Precautions §5.10 — Increased Risk of Seizure.','Live DailyMed label currentness rechecked 2026-08-15; no superseding label identified.'),
460:('DailyMed/FDA — Gabapentin','https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=54edd6f3-06c7-a0c7-e063-6394a90a8b4f','Warnings and Precautions §5.8 — Respiratory Depression with CNS depressants including opioids.','Live DailyMed label currentness rechecked 2026-08-15; no superseding label identified.'),
461:('DailyMed/FDA — Clobetasol Propionate Cream','https://www.dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cb0bc057-d6ab-4eea-af7a-01661ae9b517','Warnings/Adverse Reactions — local corticosteroid reactions including atrophy, striae, and telangiectasia.','Revised 04/2026, version 100, effective 2026-04-23; currentness rechecked 2026-08-15.'),
467:('CDC/NIOSH — Healthcare Respiratory Protection','https://www.cdc.gov/niosh/healthcare/respiratory-protection/index.html','Respirators versus facemasks: N95 filtering facepiece respirators require an adequate seal and provide fitted particulate respiratory protection.','Live CDC/NIOSH page currentness rechecked 2026-08-15.'),
469:('OSHA — 29 CFR 1910.1030 Bloodborne Pathogens','https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1030','§1910.1030(d)(4)(iii)(A)(2)(iii) sharps containers not allowed to overfill; §(A)(3)(i) close immediately before removal or replacement.','Current e-CFR/OSHA standard text rechecked 2026-08-15.'),
471:('NCSBN — Nurse Licensure Guidance','https://www.ncsbn.org/nursing-regulation/licensure/nurse-licensure-guidance.page','Licensure and renewal are governed by the applicable nursing regulatory body; requirements are jurisdiction-specific.','Live NCSBN guidance currentness rechecked 2026-08-15.'),
476:('VA National Center for Ethics in Health Care — Ethics Consultation','https://www.ethics.va.gov/help.asp','Ethics consultation is a resource for uncertainty or conflict about what should be done in health care and helps clarify ethically supportable options.','Live VA ethics guidance currentness rechecked 2026-08-15.'),
479:('NIDDK — Cushing’s Syndrome','https://www.niddk.nih.gov/health-information/endocrine-diseases/cushings-syndrome','Symptoms and physical changes: upper-body weight gain, rounded face, and fat accumulation around neck/upper back.','Live NIDDK page currentness rechecked 2026-08-15.'),
481:('NCBI Bookshelf / StatPearls — Pancreatic Pseudocyst','https://www.ncbi.nlm.nih.gov/books/NBK557594/','Clinical presentation and evaluation of pancreatic pseudocyst after pancreatitis, including persistent abdominal symptoms and mass effect.','StatPearls update 2026-04-15; currentness rechecked 2026-08-15.'),
482:('AASLD — Portal Hypertension and Varices in Cirrhosis','https://www.aasld.org/practice-guidelines/portal-hypertension-bleeding-cirrhosis','Portal hypertension produces portosystemic collaterals including gastroesophageal varices and risk of variceal hemorrhage.','Current AASLD portal-hypertension practice guidance rechecked 2026-08-15.'),
483:('American College of Gastroenterology — Management of Patients With Acute Lower Gastrointestinal Bleeding','https://pubmed.ncbi.nlm.nih.gov/36735555/','Guideline discussion of hematochezia and evaluation for an upper-GI source when bleeding is brisk or hemodynamic findings suggest it.','ACG Clinical Guideline, 2023; currentness rechecked 2026-08-15.'),
486:('DailyMed/FDA — Warfarin Sodium','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=efded00a-22b9-1da7-e053-2995a90a58ca','Dosage/monitoring for nonvalvular atrial fibrillation: target INR 2.5, range 2.0–3.0.','Live DailyMed label currentness rechecked 2026-08-15.'),
488:('ARUP Consult — Megaloblastic Anemia','https://arupconsult.com/content/megaloblastic-anemia','Macrocytic/megaloblastic anemia evaluation: increased MCV and vitamin B12 or folate deficiency.','Live ARUP Consult topic currentness rechecked 2026-08-15.'),
489:('ARUP Consult — Iron Deficiency Anemia','https://arupconsult.com/content/iron-deficiency-anemia','Laboratory evaluation: low hemoglobin, microcytosis as deficiency progresses, and low ferritin supporting depleted iron stores.','Last updated 10/2025; currentness rechecked 2026-08-15.'),
490:('AABB — FAQs About Blood and Blood Donation','https://www.aabb.org/for-donors-patients/faqs-about-blood-and-blood-donation','ABO red-cell compatibility: in an emergency, type O red blood cells can be given when the recipient blood type is not yet known.','Live AABB FAQ currentness rechecked 2026-08-15.'),
494:('National Institute on Aging — Taking Medicines Safely as You Age','https://www.nia.nih.gov/health/medicines-and-medication-management/taking-medicines-safely-you-age','Polypharmacy/medication management: maintain and review a complete list because multiple medicines increase adverse-effect and interaction risk.','Live NIA page currentness rechecked 2026-08-15.'),
496:('CDC — Facts About Seat Belt Use','https://www.cdc.gov/seat-belts/facts/index.html','Seat belts reduce serious crash-related injuries and deaths and should be used on every trip.','CDC page dated 2026-01-27; currentness rechecked 2026-08-15.'),
499:('VA National Center for PTSD — Grounding Technique','https://www.ptsd.va.gov/professional/treat/care/toolkits/police/managingStrategies.asp','Grounding for intrusive thoughts/flashbacks: focus attention on the current situation and present sensory surroundings.','Live VA National Center for PTSD page currentness rechecked 2026-08-15.'),
500:('American Society of Addiction Medicine — Alcohol Withdrawal Management Guideline','https://www.asam.org/quality-care/clinical-guidelines/alcohol-withdrawal-management-guideline','Alcohol withdrawal delirium: severe withdrawal with delirium/autonomic activation; recommendations VI.7–VI.13 address close monitoring and active medical management.','ASAM Clinical Practice Guideline 2020 remains the active ASAM alcohol-withdrawal guideline; currentness rechecked 2026-08-15.')}
def authority(url:str)->str:
    if 'dailymed.nlm.nih.gov' in url: return 'PRIMARY_FDA_DAILYMED_LABEL'
    if 'osha.gov' in url: return 'PRIMARY_FEDERAL_REGULATION_OSHA'
    if 'cdc.gov' in url: return 'PRIMARY_FEDERAL_CDC_NIOSH'
    if 'samhsa.gov' in url: return 'PRIMARY_FEDERAL_SAMHSA'
    if 'ncsbn.org' in url or 'nclex.com' in url: return 'PRIMARY_NCSBN'
    if 'va.gov' in url or 'ethics.va.gov' in url: return 'PRIMARY_FEDERAL_VA'
    if 'hhs.gov' in url: return 'PRIMARY_FEDERAL_HHS'
    if 'niddk.nih.gov' in url or 'ninds.nih.gov' in url or 'nia.nih.gov' in url: return 'PRIMARY_FEDERAL_NIH'
    if 'ncbi.nlm.nih.gov' in url or 'medlineplus.gov' in url: return 'AUTHORITATIVE_NLM_NCBI'
    if 'ahrq.gov' in url: return 'PRIMARY_FEDERAL_AHRQ'
    if 'fda.gov' in url: return 'PRIMARY_FEDERAL_FDA'
    if 'arupconsult.com' in url: return 'AUTHORITATIVE_LAB_ARUP'
    if 'aabb.org' in url: return 'PROFESSIONAL_STANDARD_AABB'
    if 'aasld.org' in url: return 'PROFESSIONAL_GUIDELINE_AASLD'
    if 'pubmed.ncbi.nlm.nih.gov' in url: return 'PEER_REVIEWED_PROFESSIONAL_GUIDELINE'
    if 'nursingworld.org' in url: return 'PROFESSIONAL_STANDARD_ANA'
    if 'asam.org' in url: return 'PROFESSIONAL_GUIDELINE_ASAM'
    if 'mentalhealthfirstaid.org' in url: return 'PRIMARY_PROGRAM_SOURCE_MHFA_USA'
    return 'AUTHORITATIVE_PRIMARY_OR_PROFESSIONAL_SOURCE'
def metrics(opts,key):
    ls={k:len(str(opts[k]).strip()) for k in 'ABCD'}; dm=sum(ls[k] for k in 'ABCD' if k!=key)/3
    return {'characters':ls,'max_min_ratio':round(max(ls.values())/max(min(ls.values()),1),4),'correct_option':key,'correct_deviation_from_distractor_mean':round(abs(ls[key]-dm)/max(dm,1),4),'use':'MEASUREMENT_ONLY_NOT_SEMANTIC_GATE'}
def place_options(authored,target):
    letters='ABCD'; out={}; out[target]=authored[0]; j=1
    for k in letters:
        if k==target: continue
        out[k]=authored[j]; j+=1
    return {k:out[k] for k in letters}
def main():
    if not DB.exists(): raise SystemExit('Current master DB missing')
    pdoc=json.loads(PENDING.read_text(encoding='utf-8'))
    if pdoc.get('range')!=[451,500] or pdoc.get('count')!=50: raise SystemExit(f'Expected pending Batch 010 Q0451-Q0500, got {pdoc.get("range")} count={pdoc.get("count")}')
    rows=pdoc.get('questions',[])
    if [q.get('question_uid') for q in rows]!=IDS: raise SystemExit('Pending questions are not exactly V2-Q0451..V2-Q0500 in order')
    current={q['question_uid']:q for q in rows}; items=[]
    default_cat={v:k for k,v in NEEDS.items()}
    for n in range(451,501):
        uid=f'V2-Q{n:04d}'; q=current[uid]
        cat=CATEGORY_PATCH.get(n,default_cat.get(q['client_need']))
        if cat not in NEEDS: raise SystemExit(f'{uid}: unmapped client need {q["client_need"]}')
        opts=place_options(AUTHORED_OPTIONS[n],TARGET_KEYS[n]); key=TARGET_KEYS[n]
        stem=STEM_PATCH.get(n,q['stem'])
        rationale=RATIONALE_PATCH.get(n,re.sub(r'\bOption\s+[A-D]\b','The keyed response',q['rationale']))
        if n in SOURCE_PATCH:
            sname,surl,locator,version=SOURCE_PATCH[n]
        else:
            sname,surl,locator=q['source_name'],q['source_url'],q['source_detail']
            version='Source has no separate formal version identifier in the cited page metadata; live currentness and applicability rechecked 2026-08-15.'
        finding='Fresh Rule 1 review of stem, four final authored choices, key, rationale, source hierarchy/currentness, blueprint, difficulty, ambiguity, cueing and second-answer risk; final state independently re-read.'
        if n==453: finding+=' Replaced broad mechanism wording with the directly label-supported losartan-versus-lisinopril cough comparison.'
        if n==477: finding+=' Corrected blueprint from Management of Care to Psychosocial Integrity.'
        if n==482: finding+=' Narrowed the stem to portosystemic collateral-vein formation to eliminate overlap with other cirrhosis decompensation complications.'
        if n==490: finding+=' Removed the prior Rh-selection generalization and limited the item to AABB-supported ABO emergency red-cell compatibility.'
        if n==494: finding+=' Corrected blueprint from Basic Care and Comfort to Pharmacological and Parenteral Therapies.'
        if n==495: finding+=' Corrected blueprint from Basic Care and Comfort to Safety and Infection Prevention and Control.'
        if n==500: finding+=' Corrected blueprint from Psychosocial Integrity to Physiological Adaptation.'
        items.append({'id':uid,'cat':cat,'need':NEEDS[cat],'diff':q['difficulty'],'stem':stem,'options':opts,'key':key,'rationale':rationale,'source_name':sname,'source_url':surl,'locator':locator,'version':version,'authority':authority(surl),'finding':finding,'qa':[11,'PASS','FINAL_QA_PASS']})
    # Materialize the five manual audit records. Static data above contains the semantic/editorial decisions; this loop only serializes them.
    for idx,start in enumerate((451,461,471,481,491)):
        chunk=items[idx*10:(idx+1)*10]
        doc={'batch':'Q0451-Q0500','range':f'Q{start:04d}-Q{start+9:04d}','review_date':REVIEW_DATE,'legacy_status_evidence':False,'semantic_decisions_by_script':False,'manual_decision_source':'STATIC_AUTHORED_RULE1_ITEM_BY_ITEM_REVIEW','items':chunk}
        PATCHES[idx].write_text(json.dumps(doc,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    con=sqlite3.connect(DB); con.row_factory=sqlite3.Row; evidence=[]; overrides=[]
    for p in items:
        uid=p['id']; q=con.execute('SELECT * FROM questions WHERE question_uid=?',(uid,)).fetchone()
        if q is None: raise SystemExit(f'{uid}: missing DB row')
        opts=p['options']; key=p['key']
        if set(opts)!=set('ABCD') or key not in opts or len({v.strip().casefold() for v in opts.values()})!=4: raise SystemExit(f'{uid}: invalid options/key')
        if p.get('qa')!=[11,'PASS','FINAL_QA_PASS']: raise SystemExit(f'{uid}: incomplete semantic QA')
        for fld in ('stem','rationale','source_name','source_url','locator','version','authority','need','diff'):
            if not str(p.get(fld,'')).strip(): raise SystemExit(f'{uid}: missing {fld}')
        ncsbn={'required_currentness_and_blueprint_check':True,'source':'NCSBN — 2026 NCLEX-RN Test Plan','url':NCSBN_URL,'locator':NCSBN_LOCATORS[p['cat']],'version':NCSBN_VERSION,'result':'PASS','scope':'Mandatory current NCLEX blueprint/category/entry-level relevance check; exact clinical/legal claim separately verified against the item authority.'}
        m=metrics(opts,key); detail=f"{p['locator']} {p['version']} NCSBN first-check: {ncsbn['locator']} {NCSBN_VERSION}"
        flags=['RULE1_BATCH010_MANUAL_ITEM_BY_ITEM_REAUDIT','LEGACY_STATUS_NOT_USED_AS_EVIDENCE','SEMANTIC_DECISIONS_NOT_BY_SCRIPT','STATIC_MANUAL_AUTHORED_FINAL_OPTIONS','SOURCE_LOCATOR_VERSION_CURRENTNESS_VERIFIED','MANUAL_DISTRACTOR_AMBIGUITY_CUE_SECOND_ANSWER_QC_PASS','INDEPENDENT_SECOND_PASS_QA_PASS','OPTION_LENGTH_METRICS_MEASUREMENT_ONLY']
        overrides.append({'question_uid':uid,'source_id':int(q['source_id']),'category_id':p['cat'],'client_need':p['need'],'difficulty':p['diff'],'stem':p['stem'],'item_data_json':json.dumps({'options':opts},ensure_ascii=False,separators=(',',':')),'correct_answer_json':json.dumps({'correct_option':key},separators=(',',':')),'rationale':p['rationale'],'source_name':p['source_name'],'source_detail':detail,'source_url':p['source_url'],'clinical_qa_status':STATUS,'editorial_priority':'PRODUCTION_CANDIDATE','editorial_flags_json':json.dumps(flags,separators=(',',':')),'qc':{'question_uid':uid,'lengths_json':json.dumps(m['characters'],separators=(',',':')),'min_chars':min(m['characters'].values()),'max_chars':max(m['characters'].values()),'max_min_ratio':m['max_min_ratio'],'correct_option':key,'correct_length_rank':sorted(m['characters'].values()).index(m['characters'][key])+1,'correct_is_extreme':int(m['characters'][key] in (min(m['characters'].values()),max(m['characters'].values()))),'qc_status':'MEASURED_NOT_GATE','qc_note':'Length metrics are measurement only; semantic option/cue/ambiguity decisions are manual.'}})
        evidence.append({'id':uid,'key':key,'category_id':p['cat'],'client_need':p['need'],'difficulty':p['diff'],'source_authority':p['authority'],'source_name':p['source_name'],'source_url':p['source_url'],'source_locator':p['locator'],'source_version':p['version'],'reviewed_at':REVIEW_DATE,'finding':p['finding'],'ncsbn_first_check':ncsbn,'criteria':11,'criteria_names':CRITERIA,'second_pass':'PASS','second_pass_method':'Independent fresh second read of final corrected stem, all four authored options, key, rationale, source locator/version/currentness, blueprint/difficulty and second-answer/cue risk without using legacy status as evidence.','final':'FINAL_QA_PASS','option_measurement':m,'semantic_decision_origin':'MANUAL_ITEM_BY_ITEM_AUDIT_NOT_SCRIPT'})
    con.close()
    EVIDENCE.write_text(json.dumps({'standard':'RULE_1_FINAL_10_OF_10_MANUAL_ITEM_BY_ITEM_REAUDIT','batch':'Q0451-Q0500','review_date':REVIEW_DATE,'legacy_status_evidence':False,'semantic_decisions_by_script':False,'criteria_names':CRITERIA,'ncsbn_test_plan':{'url':NCSBN_URL,'version':NCSBN_VERSION},'items':evidence},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    OVERRIDE.write_text(json.dumps({'version':'2026-08-15-rule1-batch010-manual-item-by-item-q0451-q0500','semantic_decisions_by_script':False,'questions':overrides},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print('BATCH010_MANUAL_ARTIFACTS_BUILT items=50/50 criteria11=50/50 second_pass=50/50 semantic_script_decisions=0 option_metrics=measurement_only')
if __name__=='__main__': main()
