#!/usr/bin/env python3
from __future__ import annotations
import json
import run_wave30_manual_payload as wave30

BALANCED={
733:{'A':'An allergic response causing itching, swelling, wheezing, and other hypersensitivity findings','B':'Nicotine withdrawal causing cravings, irritability, poor concentration, and increased appetite','C':'A normal hospital adjustment reaction unrelated to nicotine exposure or recent tobacco cessation','D':'An acute neurologic emergency causing sudden focal deficits rather than gradual withdrawal symptoms'},
734:{'A':'A pharmacogenetic crisis triggered by volatile anesthetics or succinylcholine in susceptible people','B':'A heat illness caused only by prolonged environmental exposure without any anesthetic trigger','C':'A chronic metabolic disorder that develops gradually over months rather than during anesthesia','D':'An exertional heat illness caused by exercise in hot conditions rather than anesthetic exposure'},
735:{'A':'Expected postoperative drainage with stable circulation and no evidence of ongoing blood loss','B':'Anesthetic allergy causing rash, bronchospasm, or swelling without progressive wound bleeding','C':'Postoperative hemorrhage causing blood loss that requires urgent assessment and intervention','D':'Urinary infection causing dysuria and fever rather than increasing sanguineous wound drainage'},
737:{'A':'Lower venous thromboembolism risk that usually requires fewer preventive interventions','B':'Cardiac operative risk used to estimate complications after valve or bypass procedures','C':'Higher venous thromboembolism risk that may justify more intensive preventive measures','D':'General recovery status used mainly to estimate mobility and discharge readiness after surgery'},
738:{'A':'The technical experience of the surgical and anesthesia teams assigned to provide the procedure','B':'The insurance authorization category used to approve the planned procedure and anesthetic care','C':'The client\'s pre-anesthesia physical health status and the burden of systemic disease present','D':'The predicted surgical outcome based only on procedure type, complexity, and expected duration'},
739:{'A':'A numeric 0-to-10 rating scale requiring reliable understanding of ordered number values','B':'No formal pain tool because young children cannot provide clinically useful pain information','C':'A behavioral assumption that lack of a numeric self-report means the child has no pain','D':'A developmentally appropriate faces scale that lets the child select the face matching pain'},
740:{'A':'Nutrition has little effect on healing or immunity and usually corrects without intervention','B':'A screening score replaces any later detailed nutrition assessment or dietitian evaluation','C':'Early malnutrition-risk detection allows timely nutrition assessment and targeted intervention','D':'Nutrition screening is mainly for outpatient care because hospital meals correct inpatient risk'},
741:{'A':'Order the same fixed laboratory panel for every client regardless of procedure or health status','B':'Delay scheduling by obtaining routine tests even when results cannot influence perioperative care','C':'Replace the preoperative history and examination with a standardized set of laboratory results','D':'Select tests according to clinical history, comorbidities, procedure, and likely management impact'},
742:{'A':'Replace nursing judgment entirely by dictating one handling method without individual assessment','B':'Document staff injury after it occurs rather than guide safer handling before moving the client','C':'Guide selection of safer handling methods and equipment using mobility and client-specific factors','D':'Apply only to bariatric clients because standard-weight clients do not create handling injury risk'},
743:{'A':'Use one fixed bathing schedule for the entire admission regardless of skin or comfort changes','B':'Individualize bathing to skin condition, preferences, culture, comfort, and clinical circumstances','C':'Schedule hygiene mainly around staff convenience even when this conflicts with client preferences','D':'Provide identical bathing frequency to every client without adapting to clinical or personal needs'},
744:{'A':'Increase activity gradually while reassessing tolerance, strength, symptoms, and safety each day','B':'Use the same walking distance for every postoperative client regardless of baseline function','C':'Begin at the client\'s maximum possible distance on the first postoperative ambulation attempt','D':'Avoid adjusting activity because gradual progression has little effect on recovery or fall risk'},
746:{'A':'Use regular activity, relaxation skills, adequate sleep, and supportive social connections','B':'Wait for workplace stress to resolve without using any deliberate coping or recovery strategy','C':'Reduce physical activity during stressful periods to conserve energy for work responsibilities','D':'Rely on caffeine and alcohol to manage stress, improve sleep, and maintain daily performance'},
747:{'A':'Express milk regularly at intervals similar to usual feeds to help maintain supply while apart','B':'Stop breastfeeding after returning to work because pumping rarely maintains milk production','C':'Expect milk supply to decline sharply whenever daytime separation from the infant begins','D':'Assume workplace protections do not apply and that scheduled milk-expression breaks are unavailable'},
748:{'A':'Share an adult bed with the infant overnight so the parent can continuously monitor breathing','B':'Use pillows and thick blankets in the sleep space to prevent the infant from becoming cold','C':'Avoid smoke and overheating and consider a pacifier for sleep once breastfeeding is established','D':'Permit secondhand smoke exposure because tobacco smoke is not associated with sleep-related death'},
749:{'A':'Strong social support, flexible coping skills, adaptability, and a meaningful sense of purpose','B':'Rigid thinking that limits adaptation when circumstances or demands change unexpectedly','C':'Minimal prior exposure to stress because resilience depends mainly on avoiding adversity','D':'Social withdrawal during hardship so the person can manage problems without outside support'},
750:{'A':'Adjustment disorder linked to an identifiable stressor with clinically significant distress','B':'A psychiatric condition that develops independently of any identifiable life stressor','C':'A normal transition response that does not merit assessment despite substantial impairment','D':'A longstanding personality pattern present across contexts and unrelated to the recent event'},
752:{'A':'An intermediate-acting insulin suspension that is normally cloudy after gentle resuspension','B':'A clear insulin solution that should be warmed before injection whenever cloudiness develops','C':'A contaminated insulin product that should always be discarded whenever it looks uniformly white','D':'A long-acting insulin solution that should remain completely clear and never require mixing'},
756:{'A':'A minor insertion-site bruise that needs no reassessment despite increasing pain and swelling','B':'A reason to increase the infusion rate so the remaining phenytoin enters the vein more quickly','C':'Purple glove syndrome, requiring the phenytoin infusion to stop and the site to be evaluated','D':'An expected local phenytoin effect that can be ignored when distal color and swelling develop'},
757:{'A':'Mild fatigue alone without abdominal symptoms, jaundice, urine change, or other liver findings','B':'Jaundice, dark urine, nausea, or vomiting that can indicate clinically important hepatotoxicity','C':'A mild isolated headache without gastrointestinal symptoms or any evidence of hepatic injury','D':'A modest increase in appetite without jaundice, dark urine, nausea, or abdominal discomfort'},
758:{'A':'A complete loss of taste that commonly develops during otherwise uncomplicated rifampin therapy','B':'Orange-red discoloration of urine, sweat, tears, or saliva that is expected with rifampin','C':'No visible change in any body fluid because rifampin does not alter secretion coloration','D':'Permanent dark discoloration of tooth enamel that routinely occurs during rifampin treatment'},
759:{'A':'Oral vancomycin has poor systemic absorption and stays mainly in the gut, while IV reaches blood','B':'The route differs only because oral vancomycin is cheaper than intravenous vancomycin therapy','C':'Oral and intravenous vancomycin produce essentially identical drug exposure throughout the body','D':'Using oral vancomycin for intestinal infection is a prescribing error because all therapy is IV'},
762:{'A':'A surgical mask alone even when blood or body fluid could splash into the nurse\'s eyes','B':'Eye or face protection with other indicated PPE when splash or spray exposure is anticipated','C':'Gloves alone because standard precautions do not require mucous-membrane protection from splashes','D':'Eye protection only when the client specifically requests additional protective equipment'},
764:{'A':'Rub a small amount for only a few seconds even if parts of the hands remain uncovered','B':'Use alcohol hand rub over visibly soiled hands rather than washing them with soap and water','C':'Apply hand rub and immediately wipe the hands dry with a disposable towel before it evaporates','D':'Apply enough product to cover all hand surfaces and rub the hands together until completely dry'},
765:{'A':'Keep all PPE on until reaching the nurses\' station so every item can be removed at one location','B':'Remove the respirator inside the patient room before removing contaminated gloves and gown','C':'Remove other PPE before leaving the care area, then remove the respirator after exit and door closure','D':'Remove PPE in any order or location because correct hand hygiene makes doffing sequence irrelevant'},
767:{'A':'Keep the same gloves because changing tasks for one client does not create cross-contamination risk','B':'Change gloves and perform hand hygiene before moving from contaminated wound care to clean handling','C':'Use the same gloves for wound care and clean linen handling as long as no second client is touched','D':'Change gloves only when moving to another client, not when changing from dirty to clean tasks'},
768:{'A':'Separate sharps, regulated medical, pharmaceutical, and ordinary waste according to applicable rules','B':'Discard every item in ordinary trash because special waste streams apply only to laboratory material','C':'Use a sharps container only for needles and place all other clinical waste in ordinary trash','D':'Place every healthcare item in one biohazard bag because pharmaceutical waste has no separate rules'},
769:{'A':'Sterilization and disinfection are interchangeable processes with the same microbial endpoint','B':'Sterilization applies only to environmental surfaces and is not used for reusable instruments','C':'Sterilization removes fewer microorganisms than high-level disinfection used on medical devices','D':'Sterilization destroys all microbial life, including bacterial spores, unlike disinfection'},
770:{'A':'Physician-sensitive indicators that primarily measure medical decisions rather than nursing care','B':'Nurse-sensitive indicators that reflect outcomes influenced by nursing care and nursing practice','C':'Unstructured measurements that lack defined methods for comparing quality across clinical units','D':'Billing indicators used primarily for reimbursement and not for clinical quality improvement'},
771:{'A':'Replace internal quality-improvement work because national benchmark reports are sufficient','B':'Compare unit outcomes with national benchmarks to identify gaps and guide improvement efforts','C':'Collect nursing data without using it to change practice, staffing, education, or safety processes','D':'Track financial performance only rather than clinically relevant nurse-sensitive outcomes'},
772:{'A':'Professional accountability, meaning responsibility for nursing decisions, actions, and outcomes','B':'Delegation alone, meaning the nurse transfers all responsibility to another member of the team','C':'Professional detachment, meaning clinical decisions carry no individual responsibility afterward','D':'Avoidance of independent judgment so responsibility always remains with another licensed clinician'},
773:{'A':'Telehealth practice is exempt from state nursing licensure whenever communication occurs remotely','B':'A home-state nursing license automatically authorizes practice in every other state by telehealth','C':'No state authorization matters when the encounter does not involve in-person nursing contact','D':'Practice authority generally must cover the state where the client is located during the encounter'},
774:{'A':'Use evidence-based practice only in academic settings and not when designing bedside protocols','B':'Treat research as separate from clinical care because studies do not guide nursing interventions','C':'Rely on unit tradition alone even when stronger current research supports a different approach','D':'Integrate current research evidence with clinical expertise when developing nursing protocols'},
776:{'A':'State staffing laws vary, with different approaches such as ratios, committees, or no specific law','B':'No state has enacted any staffing-related nursing requirements, reporting rules, or ratio standards','C':'Every state now uses the same mandatory nurse-to-patient ratios for comparable hospital units','D':'Only federal law determines nurse staffing requirements, leaving states no regulatory role'},
777:{'A':'Follow the supervisor\'s instruction because management authority overrides legal scope restrictions','B':'Decline the out-of-scope task and escalate the concern through appropriate clinical channels','C':'Perform the task to avoid conflict even though state law does not authorize the nursing activity','D':'Perform the task only when no one is watching because the legal scope rule applies only if reported'},
778:{'A':'Compensation can preserve near-normal blood pressure through tachycardia and vasoconstriction early','B':'Early shock usually produces bradycardia while blood pressure remains normal through compensation','C':'Compensatory mechanisms do not affect heart rate, vascular tone, or perfusion in the early stage','D':'Severe hypotension must already be present before shock can exist or require clinical recognition'},
780:{'A':'First-degree frostbite, a superficial injury that does not form blisters after tissue rewarming','B':'Second-degree frostbite, which develops clear or milky blisters after the tissue has been rewarmed','C':'Third-degree frostbite, which causes deeper injury and typically forms hemorrhagic blisters','D':'Fourth-degree frostbite, which extends into deeper structures such as muscle, tendon, or bone'},
781:{'A':'A permanent loss of consciousness that does not resolve spontaneously without resuscitation','B':'A transient complete loss of consciousness with rapid spontaneous and complete recovery','C':'A disorder unrelated to cerebral perfusion that presents primarily with persistent focal deficits','D':'Lightheadedness without actual loss of consciousness, which describes presyncope rather than syncope'}
}

KEY={733:'B',734:'A',735:'C',737:'C',738:'C',739:'D',740:'C',741:'D',742:'C',743:'B',744:'A',746:'A',747:'A',748:'C',749:'A',750:'A',752:'A',756:'C',757:'B',758:'B',759:'A',762:'B',764:'D',765:'C',767:'B',768:'A',769:'D',770:'B',771:'B',772:'A',773:'D',774:'D',776:'A',777:'B',778:'A',780:'A',781:'B'}

def main():
    pending=json.loads(wave30.PENDING.read_text(encoding='utf-8'))
    by_id={int(q['source_id']):q for q in pending['questions']}
    for n,opts in BALANCED.items():
        q=by_id[n]
        prior=wave30.FIX.get(n,{})
        wave30.FIX[n]={
            'stem':prior.get('stem',q['stem']),
            'options':opts,
            'key':KEY[n],
            'rationale':prior.get('rationale',q['rationale'])
        }
    wave30.main()

if __name__=='__main__': main()
