#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
OUT=Path('usmle/batch_specs_1501_1600/02_q1506_q1510_author_20260910.json')
DB_BLOB='921a18dae711f516de4d90d8935c850bc611eff3'

def ev(q,key,sid,loc,r):
 return [{'claim_id':f'Q{q}-{L}','option':L,'claim_locator':f'explanation.distractor_explanations.{L}','claim':r[L],'source_ids':[sid],'direct_or_inference':'direct' if L==key else 'inference','source_locator':loc,'item_specific_application':'Keyed mechanism is directly source-bound; distractor rejection uses that mechanism plus stipulated experimental findings.'} for L in 'ABCDE']
def qa(alt,res):
 return {'key_correctness':'PASS','all_options_review':'PASS','single_best_answer':'PASS','second_answer_attack':{'option':alt,'resolution':res,'status':'PASS'},'hidden_assumptions':'PASS','numerical_claims':'PASS — no empirical calibration or unsupported numerical claim used to identify the key.','fabricated_distractors':'PASS','source_identity_setid_url_locator':'PASS','currentness':'PASS — current DailyMed SetID page reverified 2026-09-10.','blueprint':'PASS','difficulty':'Author estimate only','rationale':'PASS A-E','educational_objective':'PASS','adversarial_second_pass':'PASS','technical_hash_gate':'PENDING','unresolved_content_defects':[]}
def make(q,drug,system,disc,vig,lead,opts,key,construct,keyexp,rats,eo,title,setid,alt,res):
 loc='12.1 Mechanism of Action'; sid=f'Q{q}-LABEL'
 return {'num':q,'drug':drug,'country_scope':'United States','status':'AUTHOR_QA_PASS_PENDING_TECHNICAL_FREEZE_AND_INDEPENDENT_AUDIT','blueprint':{'primary_system':system,'primary_competency':'Medical Knowledge: Applying Foundational Science Concepts','disciplines':disc,'official_outline_path':[system],'specification_source_id':'USMLE-SPEC'},'item':{'vignette':vig,'lead_in':lead,'options':opts,'intended_key':key,'tested_construct':construct,'difficulty':'moderate-hard','difficulty_basis':'Requires mechanistic discrimination among plausible pharmacologic targets; author estimate only.'},'explanation':{'key_explanation':keyexp,'distractor_explanations':rats,'educational_objective':eo},'sources':[{'source_id':sid,'title':title,'agency':'Manufacturer prescribing information hosted by NLM DailyMed','url':f'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid={setid}','setid':setid,'source_section_date':None,'date_basis':'Current DailyMed SetID page checked 2026-09-10; no unsupported revision date inferred.','retrieved_at':'2026-09-10','section_locator':loc,'source_page_sha256':None,'cited_section_sha256':None,'hash_status':'PENDING_DETERMINISTIC_REFETCH_AND_HASH'}],'evidence_map':ev(q,key,sid,loc,rats),'author_qa':qa(alt,res)}
def main():
 items=[]
 items.append(make(1506,'seladelpar','Gastrointestinal System',['Pharmacology','Biochemistry'],'Hepatocytes are exposed to seladelpar. A nuclear-receptor reporter increases, FGF21 signaling rises, and CYP7A1 expression falls with reduced bile-acid synthesis. Thyroid-hormone receptor signaling is unchanged.','Which direct receptor action best explains these findings?',{'A':'Agonism of PPAR-delta','B':'Partial agonism of thyroid hormone receptor-beta','C':'Antagonism of the farnesoid X receptor','D':'Agonism of PPAR-gamma only','E':'Inhibition of the ileal bile-acid transporter'},'A','PPAR-delta agonism with FGF21-dependent suppression of CYP7A1','Seladelpar is a PPAR-delta agonist. PPAR-delta activation can reduce bile-acid synthesis through FGF21-dependent downregulation of CYP7A1.',{'A':'Correct. PPAR-delta agonism directly fits the reporter signal and FGF21/CYP7A1 pattern.','B':'THR-beta agonism is excluded by unchanged thyroid-hormone receptor signaling.','C':'FXR antagonism is not the documented direct target.','D':'The labeled receptor target is PPAR-delta rather than selective PPAR-gamma agonism.','E':'An ileal transporter mechanism would not explain a direct hepatocyte nuclear-receptor reporter response.'},'Link PPAR-delta agonism to FGF21-dependent suppression of hepatic bile-acid synthesis.','LIVDELZI- seladelpar lysine capsule','89f79d98-135c-40b2-a585-6996c04e599c','B','THR-beta agonism can also alter hepatic lipid metabolism, but the PPAR-delta reporter and FGF21/CYP7A1 pattern specifically identify seladelpar pharmacology.'))
 items.append(make(1507,'resmetirom','Gastrointestinal System',['Pharmacology','Biochemistry'],'A liver-cell preparation is exposed to resmetirom. A thyroid-hormone-responsive reporter is activated much more strongly through the beta receptor isoform than through the alpha isoform, and intracellular triglyceride content decreases.','Which direct action best explains this pattern?',{'A':'PPAR-delta agonism','B':'Partial agonism of thyroid hormone receptor-beta','C':'Antagonism of thyroid hormone receptor-alpha','D':'Inhibition of acetyl-CoA carboxylase','E':'Activation of the farnesoid X receptor'},'B','Liver-directed partial THR-beta agonism','Resmetirom is a partial agonist of thyroid hormone receptor-beta. THR-beta is the major hepatic thyroid-hormone receptor isoform, and its stimulation reduces intrahepatic triglycerides.',{'A':'PPAR-delta is a different nuclear receptor target.','B':'Correct. Preferential THR-beta agonism explains the receptor assay and hepatic triglyceride reduction.','C':'The documented action is THR-beta agonism, not THR-alpha antagonism.','D':'ACC inhibition is an enzymatic lipid-synthesis mechanism and would not explain the thyroid-receptor reporter.','E':'FXR activation would not account for the measured THR-beta-selective response.'},'Differentiate THR-beta agonism from other hepatic nuclear-receptor and lipid-synthesis mechanisms.','REZDIFFRA- resmetirom tablet, coated','e67ea09f-a840-439c-86c8-f98585f978b2','A','PPAR-delta agonism is a plausible liver-directed nuclear-receptor mechanism, but the assay directly demonstrates preferential activation of THR-beta.'))
 items.append(make(1508,'sotatercept-csrk','Cardiovascular System',['Pharmacology','Physiology'],'Pulmonary vascular cells are exposed to a recombinant ActRIIA-Fc fusion protein. Free activin A and related TGF-beta-superfamily ligands decrease, Smad2/3-dominant pro-proliferative signaling falls, and the balance shifts toward BMPRII/Smad1/5/8 signaling.','Which direct action best explains these findings?',{'A':'BMPRII kinase inhibition','B':'Endothelin-A receptor antagonism','C':'Ligand trapping of activin A and related TGF-beta-superfamily ligands by an ActRIIA-Fc fusion protein','D':'Soluble guanylate cyclase stimulation','E':'Phosphodiesterase-5 inhibition'},'C','ActRIIA-Fc sequestration of activin/TGF-beta-superfamily ligands','Sotatercept-csrk is an ActRIIA-Fc fusion protein that binds activin A and other TGF-beta-superfamily ligands, inhibiting activin signaling and shifting the balance away from pro-proliferative ActRIIA/Smad2/3 signaling.',{'A':'BMPRII inhibition would oppose, not restore, the anti-proliferative signaling balance described.','B':'Endothelin-receptor antagonism does not directly sequester activin-family ligands.','C':'Correct. The ActRIIA-Fc fusion acts as a ligand trap for activin A and related ligands.','D':'sGC stimulation raises cGMP but does not explain ligand depletion.','E':'PDE5 inhibition also affects cGMP signaling rather than activin ligand sequestration.'},'Recognize ligand trapping by an ActRIIA-Fc fusion protein as distinct from vasodilator mechanisms in pulmonary arterial hypertension.','WINREVAIR- sotatercept-csrk kit','21693ee2-cd23-4137-ac67-066bb3a4a9b7','B','Endothelin antagonism is a common PAH mechanism, but direct depletion of activin-family ligands by an ActRIIA-Fc protein uniquely identifies sotatercept.'))
 items.append(make(1509,'olezarsen','Cardiovascular System',['Pharmacology','Biochemistry'],'Hepatocytes take up a GalNAc-conjugated antisense oligonucleotide. ApoC-III messenger RNA falls, serum apoC-III decreases, and clearance of triglyceride-rich lipoproteins increases. The genomic APOC3 sequence remains unchanged.','Which direct molecular action best explains this effect?',{'A':'CRISPR-mediated disruption of APOC3','B':'Neutralization of circulating apoC-III with a monoclonal antibody','C':'siRNA loading into RISC to cleave apoC-III mRNA','D':'Antisense binding to apoC-III mRNA leading to mRNA degradation','E':'Inhibition of microsomal triglyceride transfer protein'},'D','GalNAc-conjugated antisense oligonucleotide degradation of apoC-III mRNA','Olezarsen is a GalNAc-conjugated antisense oligonucleotide that binds apoC-III mRNA, leading to mRNA degradation and reduced apoC-III protein, which increases clearance of triglyceride-rich particles.',{'A':'The unchanged genomic sequence excludes gene editing.','B':'Protein neutralization would not directly lower apoC-III mRNA.','C':'A RISC-mediated siRNA mechanism is a different nucleic-acid platform.','D':'Correct. Olezarsen directly binds apoC-III mRNA as an antisense oligonucleotide and promotes its degradation.','E':'MTP inhibition reduces lipoprotein assembly rather than selectively degrading apoC-III mRNA.'},'Distinguish antisense-oligonucleotide mRNA degradation from siRNA, antibody, and genome-editing strategies.','TRYNGOLZA- olezarsen sodium injection, solution','0f51aa8e-8475-8cf9-e063-6394a90a6848','C','siRNA can also lower a target mRNA, but the stipulated antisense oligonucleotide platform distinguishes olezarsen from RISC-mediated RNA interference.'))
 items.append(make(1510,'givinostat','Musculoskeletal, Skin & Subcutaneous Tissue',['Pharmacology','Biochemistry'],'A muscle-cell nuclear extract is exposed to givinostat. Histone acetylation increases. Investigators explicitly avoid claiming that this biochemical action fully explains the clinical benefit in Duchenne muscular dystrophy.','Which direct pharmacologic action is established for this drug?',{'A':'Activation of histone deacetylases','B':'Inhibition of DNA methyltransferases','C':'Agonism of the glucocorticoid receptor','D':'Inhibition of histone acetyltransferases','E':'Inhibition of histone deacetylases'},'E','Histone deacetylase inhibition without overclaiming the disease-level mechanism','Givinostat is a histone deacetylase inhibitor. Its precise mechanism of therapeutic effect in Duchenne muscular dystrophy is not known, so the defensible direct claim is HDAC inhibition.',{'A':'HDAC activation would reduce rather than increase histone acetylation.','B':'DNA methyltransferase inhibition is a distinct epigenetic mechanism.','C':'Glucocorticoid-receptor agonism is not the documented direct target.','D':'Histone acetyltransferase inhibition would tend to decrease histone acetylation.','E':'Correct. Givinostat is directly established as a histone deacetylase inhibitor.'},'Separate a documented biochemical target from an incompletely established disease-level therapeutic mechanism.','DUVYZAT- givinostat suspension','1a28a3db-7880-4ac2-a2f2-2b4e362aafb6','D','Histone acetyltransferase inhibition affects the same acetylation axis, but its direction is opposite the observed increase in histone acetylation.'))
 b={'batch_id':'Q1506-Q1510-20260910','created_at':'2026-09-10','status':'AUTHOR_QA_PASS_PENDING_TECHNICAL_FREEZE_AND_INDEPENDENT_AUDIT','production_import_ready':False,'candidate_count':5,'canonical_count_before':1505,'canonical_count_after':1505,'canonical_db_blob':DB_BLOB,'answer_key_sequence':'ABCDE','answer_key_distribution':{L:1 for L in 'ABCDE'},'technical_integrity':{'source_hashes_fabricated':False,'source_hashes_complete':False,'independent_audit_complete':False,'trusted_importer_complete':False},'items':items}
 OUT.parent.mkdir(exist_ok=True); OUT.write_text(json.dumps(b,indent=2,ensure_ascii=False)+'\n')
 assert [x['num'] for x in items]==list(range(1506,1511)); assert ''.join(x['item']['intended_key'] for x in items)=='ABCDE'; assert 'ncjmm' not in OUT.read_text().casefold(); print(json.dumps({'status':'AUTHOR_QA_PASS_PENDING_INDEPENDENT_AUDIT','items':5,'keys':'ABCDE'}))
if __name__=='__main__': main()
