#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
import author_q1506_q1510 as a

OUT=Path('usmle/batch_specs_1501_1600/09_q1541_q1545_author_20260912.json')
DB_BLOB='6e55027ca4232f0d0c0df99c33702c5f1d6df117'
TODAY='2026-09-12'

def make(*args, **kwargs):
    x=a.make(*args, **kwargs)
    x['sources'][0]['date_basis']=f'Current DailyMed SetID page checked {TODAY}; no unsupported revision date inferred.'
    x['sources'][0]['retrieved_at']=TODAY
    x['author_qa']['currentness']=f'PASS — current DailyMed SetID page reverified {TODAY}.'
    return x

def main():
    items=[]

    items.append(make(
        1541,'sebetralstat','Blood & Lymphoreticular/Immune Systems',['Pharmacology','Physiology'],
        'Plasma from a patient with hereditary angioedema is incubated with sebetralstat. Kallikrein activity decreases rapidly, and generation of the vasoactive mediator responsible for increased vascular permeability is reduced.',
        'Which substrate-to-product reaction is most directly inhibited?',
        {'A':'High-molecular-weight kininogen to bradykinin','B':'Angiotensin I to angiotensin II','C':'Plasminogen to plasmin','D':'Fibrinogen to fibrin','E':'Complement C3 to C3a and C3b'},
        'A','Inhibition of plasma-kallikrein cleavage of high-molecular-weight kininogen to bradykinin',
        'Sebetralstat is a competitive, reversible inhibitor of plasma kallikrein. Plasma kallikrein cleaves high-molecular-weight kininogen and releases bradykinin; inhibition of this reaction reduces bradykinin generation and vascular permeability during hereditary angioedema attacks.',
        {'A':'Correct. Plasma kallikrein cleaves high-molecular-weight kininogen to release bradykinin, and sebetralstat inhibits this reaction.','B':'Angiotensin-converting enzyme catalyzes conversion of angiotensin I to angiotensin II and is not the target of sebetralstat.','C':'Plasminogen activation belongs to the fibrinolytic system rather than the kallikrein-kinin reaction targeted here.','D':'Thrombin converts fibrinogen to fibrin and is not directly inhibited by sebetralstat.','E':'Complement C3 cleavage is mediated by complement convertases, not plasma kallikrein in this therapeutic mechanism.'},
        'Connect plasma kallikrein inhibition with reduced cleavage of high-molecular-weight kininogen and reduced bradykinin formation in hereditary angioedema.',
        'EKTERLY- sebetralstat tablet, film coated','1d145e2f-8e7e-2e90-e063-6294a90a4449','C',
        'Plasminogen-to-plasmin conversion is another serine-protease pathway, but the hereditary-angioedema phenotype and bradykinin reduction specifically identify the kallikrein-kinin reaction.'
    ))

    items.append(make(
        1542,'nerandomilast','Respiratory System',['Pharmacology','Cell Biology'],
        'Fibroblast-lineage cells from fibrotic lung tissue are exposed to nerandomilast. Expression of profibrotic growth factors decreases after preferential inhibition of a phosphodiesterase isoenzyme that normally hydrolyzes a cyclic nucleotide.',
        'Which intracellular change most directly follows this enzyme inhibition?',
        {'A':'Decreased cyclic AMP','B':'Increased cyclic AMP','C':'Decreased cyclic GMP','D':'Increased inositol trisphosphate','E':'Increased diacylglycerol'},
        'B','Elevation of intracellular cyclic AMP after preferential PDE4B inhibition',
        'Nerandomilast preferentially inhibits phosphodiesterase 4B. PDE4 hydrolyzes and inactivates cyclic AMP; therefore PDE4B inhibition elevates intracellular cyclic AMP and contributes to reduced profibrotic and inflammatory signaling.',
        {'A':'PDE4 inhibition prevents cyclic AMP hydrolysis, so cyclic AMP rises rather than falls.','B':'Correct. Preferential PDE4B inhibition decreases cyclic AMP degradation and raises intracellular cyclic AMP.','C':'PDE4 acts on cyclic AMP rather than cyclic GMP.','D':'IP3 is generated by phospholipase C signaling and is not the immediate product of PDE4B inhibition.','E':'DAG is also generated by phospholipase C and is not the second-messenger change caused directly by PDE4B inhibition.'},
        'Recognize that PDE4B inhibition decreases cyclic AMP hydrolysis and therefore increases intracellular cyclic AMP.',
        'JASCAYD- nerandomilast tablet, film coated','fa1b14c6-957f-d326-5099-911bfe33e391','C',
        'A change in cyclic GMP is plausible for other phosphodiesterase inhibitors, but PDE4 selectively hydrolyzes cyclic AMP, making increased cyclic AMP the direct consequence.'
    ))

    items.append(make(
        1543,'mavorixafor','Blood & Lymphoreticular/Immune Systems',['Pharmacology','Immunology'],
        'Neutrophils from a patient with WHIM syndrome carry a gain-of-function CXCR4 variant and show excessive retention in bone marrow. After mavorixafor treatment, mature neutrophils and lymphocytes increase in peripheral blood.',
        'Which receptor-ligand interaction is directly blocked to produce this mobilization?',
        {'A':'CCR5 binding to CCL5','B':'CXCR2 binding to CXCL8','C':'CXCR4 binding to CXCL12','D':'CCR7 binding to CCL19','E':'S1P1 binding to sphingosine-1-phosphate'},
        'C','Blockade of CXCR4 binding to CXCL12, reducing marrow retention of leukocytes',
        'Mavorixafor is a CXCR4 antagonist that blocks binding of CXCL12, also called stromal-derived factor-1. CXCR4-CXCL12 signaling promotes leukocyte homing and retention in bone marrow; antagonism mobilizes mature neutrophils and lymphocytes into the circulation.',
        {'A':'CCR5-CCL5 signaling participates in leukocyte trafficking but is not the interaction directly blocked by mavorixafor.','B':'CXCR2-CXCL8 signaling promotes neutrophil chemotaxis and is not the WHIM-associated receptor-ligand pair.','C':'Correct. Mavorixafor blocks CXCR4-CXCL12 signaling and thereby releases leukocytes from marrow retention.','D':'CCR7-CCL19 is important for lymphoid-organ trafficking rather than the CXCR4-mediated myelokathexis mechanism.','E':'S1P1 regulates lymphocyte egress from lymphoid tissue but is not the direct target of mavorixafor.'},
        'Link WHIM syndrome myelokathexis to excessive CXCR4-CXCL12 signaling and explain leukocyte mobilization by CXCR4 antagonism.',
        'XOLREMDI- mavorixafor capsule, gelatin coated','7f3a5ee3-ca73-4876-85a0-ed1e108a2237','E',
        'S1P1 signaling can also regulate leukocyte egress, but the gain-of-function CXCR4 mutation and marrow retention specifically identify CXCR4-CXCL12 blockade.'
    ))

    items.append(make(
        1544,'aprocitentan','Cardiovascular System',['Pharmacology','Physiology'],
        'Vascular smooth-muscle cells are exposed to endothelin-1 in the presence of aprocitentan. Endothelin-dependent vasoconstrictive and proliferative signaling is suppressed. Receptor-binding studies show that the drug is not selective for only one endothelin receptor subtype.',
        'Which receptor profile is directly antagonized?',
        {'A':'Angiotensin II AT1 and AT2 receptors','B':'Alpha-1 and alpha-2 adrenergic receptors','C':'Vasopressin V1a and V2 receptors','D':'Endothelin ETA and ETB receptors','E':'Mineralocorticoid and glucocorticoid receptors'},
        'D','Dual antagonism of endothelin ETA and ETB receptors',
        'Aprocitentan is an endothelin receptor antagonist that inhibits endothelin-1 binding to both ETA and ETB receptors. Endothelin signaling contributes to vasoconstriction, vascular remodeling, fibrosis, inflammation, and aldosterone synthesis in hypertension.',
        {'A':'AT1 and AT2 are angiotensin II receptors and are not the direct targets of aprocitentan.','B':'Adrenergic receptor antagonism would affect catecholamine signaling rather than endothelin-1 responses.','C':'Vasopressin receptors mediate vascular and renal water-balance effects but are not the aprocitentan targets.','D':'Correct. Aprocitentan antagonizes both ETA and ETB endothelin receptors.','E':'Steroid-hormone receptors are intracellular nuclear receptors and do not explain direct blockade of endothelin-1 signaling.'},
        'Differentiate dual endothelin ETA/ETB receptor antagonism by aprocitentan from other antihypertensive receptor mechanisms.',
        'TRYVIO- aprocitentan tablet, film coated','dfe7a2ee-612c-4aba-834a-d68e6b59a0a6','A',
        'Angiotensin-receptor blockade is a common antihypertensive mechanism, but the direct endothelin-1 challenge and dual-receptor binding profile identify ETA/ETB antagonism.'
    ))

    items.append(make(
        1545,'clesrovimab-cfor','Respiratory System',['Pharmacology','Microbiology'],
        'Respiratory syncytial virus is incubated with a long-acting human IgG1 monoclonal antibody before exposure to airway epithelial cells. Viral entry is reduced even though viral genome replication enzymes are not inhibited. The antibody binds a conserved epitope present on both pre-fusion and post-fusion forms of the viral fusion protein.',
        'Which direct action best explains the antiviral effect?',
        {'A':'Inhibition of the RSV RNA-dependent RNA polymerase','B':'Inhibition of viral protease cleavage of polyproteins','C':'Blockade of the RSV G-protein attachment receptor interaction','D':'Depletion of infected cells through CD20 binding','E':'Binding antigenic site IV on RSV F protein to prevent viral-cell membrane fusion'},
        'E','Neutralizing binding to conserved antigenic site IV on RSV F protein, preventing membrane fusion and entry',
        'Clesrovimab-cfor is a neutralizing monoclonal antibody that targets the extracellular RSV fusion protein. It binds a conserved epitope on antigenic site IV of the F protein and prevents fusion of viral and cellular membranes, thereby blocking viral entry.',
        {'A':'Polymerase inhibition acts after viral entry and is not the mechanism of this monoclonal antibody.','B':'RSV does not rely on the described protease-targeting mechanism, and the antibody acts extracellularly before entry.','C':'The documented direct target is the RSV F protein rather than blockade of a G-protein attachment interaction.','D':'CD20 is a B-cell surface protein and has no role in direct RSV neutralization.','E':'Correct. Clesrovimab-cfor binds conserved antigenic site IV on RSV F protein and prevents viral-cell membrane fusion and entry.'},
        'Recognize neutralization of RSV by antibody binding to antigenic site IV of the F protein and blockade of membrane fusion.',
        'ENFLONSIA- clesrovimab-cfor injection','c9004a92-40e8-4cdb-b22d-d07929f8fc3b','C',
        'An attachment-blocking antibody could also act before entry, but the conserved site-IV epitope on the RSV F protein specifically identifies fusion blockade by clesrovimab-cfor.'
    ))
    items[-1]['sources'][0]['section_locator']='12.4 Microbiology; Mechanism of Action'
    for e in items[-1]['evidence_map']:
        e['source_locator']='12.4 Microbiology; Mechanism of Action'

    b={
        'batch_id':'Q1541-Q1545-20260912',
        'created_at':TODAY,
        'status':'AUTHOR_QA_PASS_PENDING_TECHNICAL_FREEZE_AND_INDEPENDENT_AUDIT',
        'production_import_ready':False,
        'candidate_count':5,
        'canonical_count_before':1540,
        'canonical_count_after':1540,
        'canonical_db_blob':DB_BLOB,
        'answer_key_sequence':'ABCDE',
        'answer_key_distribution':{L:1 for L in 'ABCDE'},
        'technical_integrity':{
            'source_hashes_fabricated':False,
            'source_hashes_complete':False,
            'independent_audit_complete':False,
            'trusted_importer_complete':False
        },
        'items':items
    }
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(b,indent=2,ensure_ascii=False)+'\n')
    assert [x['num'] for x in items]==list(range(1541,1546))
    assert ''.join(x['item']['intended_key'] for x in items)=='ABCDE'
    assert len({x['drug'].casefold() for x in items})==5
    assert 'ncjmm' not in OUT.read_text().casefold()
    print(json.dumps({'status':'AUTHOR_QA_PASS_PENDING_INDEPENDENT_AUDIT','items':5,'keys':'ABCDE'}))

if __name__=='__main__':
    main()
