#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
ROOT=Path(__file__).resolve().parent
base=ROOT/'author_q1291_q1300.py'
s=base.read_text()
repls=[
("tested='Under HHS 45 CFR 46.408, when an IRB determines that children are capable of assent and has not waived assent, adequate provisions must be made to obtain that assent; parental permission alone does not replace required child assent.'","tested='Under 45 CFR 46.408, when an IRB determines that children are capable of assent and has not waived assent, adequate provisions must be made to solicit that assent; parental permission is a separate protection and does not replace required child assent.'"),
("refs=[O(1291,2,'HHS Office for Human Research Protections','Subpart D — Additional Protections for Children Involved as Subjects in Research','https://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/common-rule-subpart-d/index.html','current access 2026-09-06','45 CFR 46.408(a)','The IRB must determine that adequate provisions are made for soliciting assent when children are capable of providing assent; age, maturity, and psychological state are considered.'),O(1291,3,'HHS Office for Human Research Protections','Research with Children FAQs','https://www.hhs.gov/ohrp/regulations-and-policy/guidance/faq/children-research/index.html','current access 2026-09-06','Child assent FAQ','If a child is capable of assent and the IRB requires assent, assent must be obtained before participation; parental permission does not by itself override a capable child’s dissent when no regulatory exception applies.')]","refs=[O(1291,2,'Electronic Code of Federal Regulations','45 CFR 46.408 — Requirements for permission by parents or guardians and for assent by children','https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-46/subpart-D/section-46.408','current eCFR; verified 2026-09-06','45 CFR 46.408(a), (e)','The IRB shall determine that adequate provisions are made for soliciting assent when children are capable of providing assent; age, maturity, and psychological state are considered, and when assent is required the IRB determines whether and how it is documented.'),S(1291,3,'Parental permission and child assent in research on children','24058304','2013','Parental permission and child assent function together as distinct protections in pediatric research; meaningful child assent or dissent should reflect developmentally appropriate information, comprehension, and voluntariness.')]"),
("keyexp='Complex informed consent requires accurate, impartial bidirectional communication. HHS guidance under Section 504/Section 1557 states that covered entities must ensure effective communication and provide appropriate auxiliary aids and services when necessary; a qualified interpreter must be able to interpret effectively, accurately, and impartially using necessary specialized vocabulary.'","keyexp='Complex informed consent requires accurate, impartial bidirectional communication. ADA effective-communication requirements place responsibility on the covered health-care entity to provide appropriate auxiliary aids and services when needed; a qualified sign-language interpreter must be able to interpret effectively, accurately, and impartially using necessary specialized vocabulary.'"),
("refs=[O(1293,2,'HHS Office for Civil Rights','Effective Communication for Persons Who Are Deaf or Hard of Hearing','https://www.hhs.gov/civil-rights/for-individuals/disability/effective-communication/index.html','current access 2026-09-06','Effective communication; qualified interpreter definition','HHS explains that covered entities are responsible for effective communication and defines a qualified interpreter as one able to interpret effectively, accurately, and impartially using necessary specialized vocabulary.'),O(1293,3,'U.S. Department of Health and Human Services','HHS’ Office for Civil Rights Secures Provider Compliance with Disability Rights Laws','https://www.hhs.gov/press-room/ocr-secures-compliance-with-disability-rights-laws.html','2026-04-13','Effective communication enforcement','HHS OCR states that Section 504 and Section 1557 require effective communication and may require qualified sign-language interpreters or other auxiliary aids and services in health care.')]","refs=[O(1293,2,'U.S. Department of Justice / ADA.gov','ADA Requirements: Effective Communication','https://www.ada.gov/resources/effective-communication/','current access 2026-09-06','Auxiliary Aids and Services; Use of Accompanying Adults or Children as Interpreters','ADA rules require covered entities to communicate effectively with people with communication disabilities, provide auxiliary aids and services when needed, and define a qualified interpreter as one who interprets effectively, accurately, and impartially using necessary specialized vocabulary.'),O(1293,3,'U.S. Department of Justice / ADA.gov','ADA Business Brief: Communicating with People Who Are Deaf or Hard of Hearing in Hospital Settings','https://www.ada.gov/resources/business-brief-hospital/','current access 2026-09-06','Hospital effective communication; Sign language interpreters','For complex interactive health-care communication such as diagnosis and treatment discussions, a qualified sign-language interpreter may be necessary; hospitals should not simply ask family members to interpret.')]"),
("fingerprint=['Deaf patient','qualified sign language interpreter','effective communication','Section 504','Section 1557']","fingerprint=['Deaf patient','qualified sign language interpreter','effective communication','ADA','auxiliary aids']")
]
for old,new in repls:
 if old not in s: raise SystemExit('author R3 source token missing: '+old[:100])
 s=s.replace(old,new)
for stale in ['hhs.gov/ohrp','hhs.gov/civil-rights','hhs.gov/press-room','Section 504','Section 1557']:
 if stale in s: raise SystemExit('stale inaccessible/source-framework token remains: '+stale)
compile(s,str(base)+'[Q1291-Q1300 R3 source repair]','exec')
exec(compile(s,str(base)+'[Q1291-Q1300 R3 source repair]','exec'),{'__name__':'__main__','__file__':str(Path(__file__).resolve())})
