#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
import repair_q1401_q1475_cross_collisions_r3 as h

OUT=Path('usmle/batch_specs_1501_1600/01_q1501_q1505_author_20260910.json')

def main():
 items=[]
 items.append(h.make(1501,'nipocalimab-aahu','Blood & Lymphoreticular/Immune Systems',['Pharmacology','Immunology'],
  'Endothelial cells expressing neonatal Fc receptor (FcRn) are exposed to nipocalimab-aahu. Recycling of IgG is reduced, circulating total IgG falls, and IgG-class autoantibody concentrations decline without direct depletion of antibody-producing B cells.',
  'Which direct action best explains these findings?',
  {'A':'Binding to neonatal Fc receptor and reducing IgG recycling','B':'Depletion of CD20-positive B cells','C':'Inhibition of plasma-cell proteasomes','D':'Neutralization of complement C5','E':'Blockade of the interleukin-6 receptor'},'A','FcRn binding that reduces circulating IgG',
  'Nipocalimab-aahu is a human IgG1 monoclonal antibody that binds FcRn, reducing FcRn-mediated IgG preservation and thereby lowering circulating IgG, including pathogenic IgG autoantibodies.',
  {'A':'Correct. FcRn binding reduces IgG recycling and lowers circulating IgG.','B':'B-cell depletion would reduce antibody production but does not match the FcRn-dependent recycling assay.','C':'Proteasome inhibition targets plasma-cell protein handling rather than IgG salvage.','D':'Complement C5 blockade affects complement activation, not IgG recycling.','E':'IL-6 receptor blockade does not directly explain reduced FcRn-mediated IgG preservation.'},
  'Connect FcRn blockade with reduced IgG recycling and lower circulating IgG rather than B-cell depletion or complement inhibition.','IMAAVY- nipocalimab-aahu injection, solution, concentrate','8886274c-f2b2-48af-85c1-2f90bfe304b8','12.1 Mechanism of Action','B','B-cell depletion can eventually lower antibody levels, but the immediate defect in FcRn-dependent recycling localizes the mechanism to FcRn blockade.'))
 items.append(h.make(1502,'gepotidacin','Multisystem Processes & Disorders',['Pharmacology','Microbiology'],
  'A bacterial isolate is exposed to gepotidacin. DNA replication stops despite preserved folate synthesis and intact ribosomal peptide elongation. Enzyme assays show inhibition of two type II topoisomerases involved in chromosome supercoiling and segregation.',
  'Which paired bacterial targets are directly inhibited?',
  {'A':'Dihydrofolate reductase and dihydropteroate synthase','B':'DNA gyrase and topoisomerase IV','C':'30S and 50S ribosomal subunits','D':'RNA polymerase and DNA-dependent RNA helicase','E':'Transpeptidase and transglycosylase'},'B','Bacterial DNA gyrase and topoisomerase IV inhibition',
  'Gepotidacin inhibits bacterial type II topoisomerases, including DNA gyrase and topoisomerase IV, thereby inhibiting DNA replication.',
  {'A':'Folate-pathway inhibition is a different antibacterial mechanism.','B':'Correct. Gepotidacin directly inhibits DNA gyrase and topoisomerase IV.','C':'Ribosomal inhibition would impair translation rather than the specified topoisomerase assays.','D':'RNA polymerase inhibition targets transcription, not the paired type II topoisomerases.','E':'Cell-wall enzyme inhibition does not explain halted DNA replication with intact wall synthesis.'},
  'Differentiate type II topoisomerase inhibition from folate, ribosomal, transcriptional, and cell-wall antibacterial mechanisms.','BLUJEPA- gepotidacin tablet, film coated','80b57cfe-7819-4d95-a57d-014af42f118d','12.4 Microbiology — Mechanism of Action','C','Translation inhibition is a common bactericidal/bacteriostatic alternative, but direct inhibition of DNA gyrase and topoisomerase IV fixes the mechanism at DNA replication.'))
 items.append(h.make(1503,'olezarsen','Cardiovascular System',['Pharmacology','Biochemistry'],
  'Hepatocytes take up a GalNAc-conjugated antisense oligonucleotide. Apolipoprotein C-III mRNA and protein decrease, followed by increased clearance of triglyceride-rich lipoproteins and VLDL. The APOC3 genomic sequence is unchanged.',
  'Which molecular process most directly produces the initial decrease in apoC-III?',
  {'A':'CRISPR-mediated disruption of the APOC3 gene','B':'Monoclonal-antibody neutralization of circulating apoC-III protein','C':'Antisense binding to apoC-III mRNA leading to mRNA degradation','D':'Inhibition of microsomal triglyceride-transfer protein','E':'Activation of lipoprotein lipase transcription by a nuclear receptor'},'C','GalNAc antisense-mediated degradation of apoC-III mRNA',
  'Olezarsen is an ASO-GalNAc conjugate that binds apoC-III mRNA, leading to mRNA degradation and reduced apoC-III protein; lower apoC-III increases clearance of plasma triglycerides and VLDL.',
  {'A':'The genomic sequence remains unchanged, excluding gene editing.','B':'Protein neutralization would not directly lower apoC-III mRNA.','C':'Correct. Olezarsen binds apoC-III mRNA and promotes its degradation.','D':'MTP inhibition affects lipoprotein assembly rather than selectively degrading APOC3 mRNA.','E':'Transcriptional activation of lipoprotein lipase would not explain the primary fall in apoC-III mRNA.'},
  'Recognize antisense oligonucleotide-mediated mRNA degradation from a selective fall in target mRNA without genomic editing.','TRYNGOLZA- olezarsen sodium injection, solution','0f51aa8e-8475-8cf9-e063-6394a90a6848','12.1 Mechanism of Action','B','Neutralizing circulating apoC-III could mimic downstream lipid effects, but it cannot explain the selective decrease in apoC-III mRNA.'))
 items.append(h.make(1504,'ensartinib','Respiratory & Renal/Urinary Systems',['Pharmacology','Biochemistry'],
  'An ALK-fusion-positive non-small-cell lung cancer line is exposed to ensartinib. Phosphorylation of ALK, AKT, ERK, and S6 decreases and proliferation slows. A parallel kinase panel also demonstrates activity against MET and ROS1.',
  'Which direct action best explains the primary signaling change?',
  {'A':'Selective EGFR inhibition','B':'KRAS G12C covalent inhibition','C':'MEK1/2 inhibition only','D':'ALK kinase inhibition with additional activity against MET and ROS1','E':'HER2-directed antibody-drug conjugate internalization'},'D','ALK kinase inhibition with MET and ROS1 activity',
  'Ensartinib is an ALK kinase inhibitor that also inhibits kinases including MET and ROS1. It suppresses ALK phosphorylation and downstream AKT, ERK, and S6 signaling in ALK-altered cells.',
  {'A':'EGFR inhibition does not match direct ALK phosphorylation loss.','B':'KRAS G12C inhibition is a different oncogenic target.','C':'MEK-only inhibition could reduce ERK signaling but would not directly reduce ALK phosphorylation or explain MET/ROS1 activity.','D':'Correct. The observed kinase and downstream signaling profile matches ensartinib.','E':'An antibody-drug conjugate does not explain direct kinase-panel inhibition.'},
  'Use receptor phosphorylation and downstream pathway changes to identify ALK kinase inhibition rather than downstream-only or unrelated oncogenic targets.','ENSACOVE- ensartinib capsule','1e1b2f79-678a-472a-b924-66909c8a4b2e','12.1 Mechanism of Action','C','MEK inhibition would lower ERK signaling, but preservation of the upstream assay showing direct ALK inhibition and additional MET/ROS1 activity excludes a MEK-only mechanism.'))
 items.append(h.make(1505,'elamipretide','Cardiovascular System',['Pharmacology','Biochemistry'],
  'Isolated mitochondria from cardiomyocytes are exposed to elamipretide. The compound concentrates at the inner mitochondrial membrane, mitochondrial ultrastructure improves, and respiratory function improves without direct inhibition of the electron-transport complexes.',
  'Which direct molecular interaction best explains this localization and effect?',
  {'A':'Covalent inhibition of complex I','B':'Opening of the mitochondrial permeability-transition pore','C':'Uncoupling of oxidative phosphorylation','D':'Activation of mitochondrial DNA polymerase gamma','E':'Binding to cardiolipin in the inner mitochondrial membrane'},'E','Mitochondrial cardiolipin binding',
  'Elamipretide is a mitochondrial cardiolipin binder that localizes to the inner mitochondrial membrane and improves mitochondrial morphology and function.',
  {'A':'Complex I inhibition would impair rather than explain improved mitochondrial function.','B':'Opening the permeability-transition pore promotes mitochondrial dysfunction and cell injury.','C':'Uncoupling dissipates the proton gradient rather than specifically localizing through cardiolipin binding.','D':'Polymerase-gamma activity concerns mitochondrial DNA replication and does not explain rapid membrane localization.','E':'Correct. Cardiolipin binding localizes elamipretide to the inner mitochondrial membrane.'},
  'Identify cardiolipin binding as a mechanism for selective inner-mitochondrial-membrane localization and improved mitochondrial structure/function.','FORZINITY- elamipretide hydrochloride injection','146bf34c-76f2-48db-ac07-fb29cce2cd75','12.1 Mechanism of Action','C','Uncouplers also act at the inner mitochondrial membrane, but they dissipate the proton gradient; the labeled direct interaction is cardiolipin binding with improved morphology and function.'))
 batch={'batch_id':'Q1501-Q1505-20260910','created_at':'2026-09-10','status':'AUTHOR_QA_PASS_PENDING_TECHNICAL_FREEZE_AND_INDEPENDENT_AUDIT','production_import_ready':False,'candidate_count':5,'canonical_count_before':1500,'canonical_count_after':1500,'canonical_db_blob':'3ed79b65e3422fa8d9649ba7870185fbf0a07e9c','answer_key_sequence':'ABCDE','answer_key_distribution':{'A':1,'B':1,'C':1,'D':1,'E':1},'scope':'Five original USMLE Step 1 mechanism-focused items; no NCJMM metadata; author QA does not substitute for zero-trust independent evidence-derived audit.','technical_integrity':{'source_hashes_fabricated':False,'source_hashes_complete':False,'required_before_freeze':'Live refetch and declared-locator hashing required','independent_audit_complete':False,'trusted_importer_complete':False},'items':items}
 OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(batch,indent=2,ensure_ascii=False)+'\n')
 print(json.dumps({'status':'AUTHOR_BATCH_CREATED','items':5,'keys':'ABCDE','canonical_blob':batch['canonical_db_blob']}))
if __name__=='__main__': main()
