def build(make):
 return make(1580,'leniolisib','Blood & Lymphoreticular/Immune Systems',['Pharmacology','Cell Biology'],
 'B lymphocytes from a patient with activated PI3K-delta syndrome are exposed to leniolisib. Akt phosphorylation decreases and abnormal lymphocyte activation is reduced.',
 'Which intracellular lipid second messenger decreases most directly?',
 {'A':'Phosphatidylinositol 4,5-bisphosphate','B':'Diacylglycerol','C':'Inositol 1,4,5-trisphosphate','D':'Cyclic AMP','E':'Phosphatidylinositol 3,4,5-trisphosphate'},
 'E','PI3K-delta inhibition with reduced PIP3 production and downstream Akt signaling',
 'Leniolisib selectively inhibits PI3K-delta by blocking its active binding site. PI3K-delta normally generates phosphatidylinositol 3,4,5-trisphosphate (PIP3), which activates downstream Akt/mTOR signaling; inhibition therefore lowers PIP3 and pAkt activity.',
 {'A':'PIP2 is the substrate used to generate PIP3 rather than the direct product that falls.','B':'DAG is produced by phospholipase C signaling, not directly by PI3K-delta.','C':'IP3 is also generated by phospholipase C and is not the direct lipid product of PI3K-delta.','D':'cAMP is regulated by adenylyl cyclase and phosphodiesterases, not directly by PI3K-delta.','E':'Correct. PI3K-delta inhibition reduces production of PIP3 and downstream Akt signaling.'},
 'Link PI3K-delta inhibition with reduced PIP3 generation and decreased Akt/mTOR pathway activity in activated PI3K-delta syndrome.',
 'JOENJA- leniolisib tablet, film coated','eefbcef8-2130-4654-8f29-b58077e08212','D',
 'cAMP is a common intracellular second messenger, but PI3K-delta directly regulates phosphoinositide conversion to PIP3 rather than adenylyl-cyclase signaling.')
