def build(make):
 return make(1618,'','Renal/Urinary System',['Physiology','Genetics','Nephrology'],
 'A 9-year-old boy has epilepsy beginning in infancy, nonprogressive cerebellar ataxia, sensorineural hearing loss, and chronic salt wasting. Laboratory studies show hypokalemic metabolic alkalosis, hypomagnesemia, and low urinary calcium. Genetic testing identifies biallelic loss-of-function variants in KCNJ10.',
 'Which renal transport abnormality most directly accounts for the salt-wasting tubulopathy?',
 {'A':'Loss of apical NKCC2-mediated sodium-potassium-chloride uptake in the thick ascending limb','B':'Loss of apical ROMK-mediated potassium recycling in the thick ascending limb','C':'Reduced basolateral potassium conductance through Kir4.1 in distal convoluted tubular cells, impairing salt reabsorption','D':'Constitutive activation of epithelial sodium channels in principal cells of the collecting duct','E':'Loss of apical pendrin-mediated chloride-bicarbonate exchange in beta-intercalated cells'},
 'C','KCNJ10/Kir4.1 loss reduces basolateral potassium conductance in distal convoluted tubular cells and impairs renal salt reabsorption',
 'KCNJ10 encodes the inwardly rectifying potassium channel Kir4.1. In kidney, KCNJ10 localizes to basolateral membranes of distal tubular segments, especially the distal convoluted tubule. EAST/SeSAME-associated loss-of-function variants markedly reduce channel activity, disrupting the basolateral potassium conductance needed for efficient distal salt transport and producing a Gitelman-like salt-wasting tubulopathy.',
 {'A':'NKCC2 loss causes Bartter syndrome, which localizes primarily to the thick ascending limb and does not explain the neurologic and auditory syndrome caused by KCNJ10 variants.','B':'ROMK loss causes a form of Bartter syndrome; KCNJ10 instead encodes the basolateral Kir4.1 channel in distal tubular cells.','C':'Correct. KCNJ10 loss impairs basolateral Kir4.1 potassium-channel function in distal convoluted tubular cells, reducing the transport capacity that supports salt reabsorption.','D':'ENaC activation causes sodium retention, hypertension, hypokalemia, and metabolic alkalosis rather than renal salt wasting with the EAST neurologic phenotype.','E':'Pendrin loss causes a different chloride-handling disorder and does not explain the characteristic KCNJ10-associated neurologic, auditory, and distal-tubular phenotype.'},
 'Recognize EAST/SeSAME syndrome as KCNJ10/Kir4.1 loss of function and connect the renal phenotype to impaired basolateral potassium conductance in distal convoluted tubular cells.',
 [{'source_id':'Q1618-PUBMED','title':'KCNJ10 gene mutations causing EAST syndrome (epilepsy, ataxia, sensorineural deafness, and tubulopathy) disrupt channel function','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/20651251/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-18; no unsupported exact revision or publication-day metadata inferred.','retrieved_at':'2026-09-18','section_locator':'Kcnj10 and Kcnj16 were found in the basolateral membrane of mouse distal convoluted tubules'}],
 'A','Bartter syndrome from NKCC2 loss can also cause hypokalemic metabolic alkalosis, but the neurologic-auditory phenotype plus KCNJ10 genotype localizes the defect to basolateral Kir4.1 in distal tubular cells rather than apical NKCC2 in the thick ascending limb.')
