def build(make):
 return make(1617,'','Blood & Lymphoreticular/Immune Systems',['Immunology','Genetics','Cell Biology'],
 'A 3-year-old boy has recurrent severe bacterial infections without pus formation, persistent leukocytosis, gingival bleeding, and recurrent epistaxis. Flow cytometry shows normal surface expression of beta2 integrins on leukocytes and alpha-IIb-beta3 integrin on platelets, but receptor stimulation fails to induce high-affinity ligand binding in either cell type.',
 'Which molecular defect best explains both the immune and bleeding manifestations?',
 {'A':'Loss of the beta2-integrin subunit CD18, preventing leukocyte integrin surface expression','B':'Loss of FERMT3-encoded kindlin-3, impairing inside-out activation of hematopoietic-cell integrins','C':'Loss of platelet glycoprotein IIb/IIIa expression with otherwise normal leukocyte integrin activation','D':'Defective phagocyte NADPH oxidase assembly, preventing the respiratory burst','E':'Loss of endothelial selectin expression, preventing leukocyte rolling'},
 'B','FERMT3/kindlin-3 deficiency causing defective inside-out integrin activation in leukocytes and platelets',
 'Leukocyte adhesion deficiency type III is caused by FERMT3 mutations that reduce or eliminate kindlin-3. Leukocytes and platelets can retain beta1, beta2, and beta3 integrin expression, but defective inside-out signaling prevents normal integrin activation. Because the defect affects hematopoietic-cell integrins in both leukocytes and platelets, patients develop recurrent infections together with a Glanzmann-like bleeding phenotype.',
 {'A':'CD18 deficiency causes LAD-I with absent or markedly reduced beta2-integrin surface expression; this patient has normal beta2-integrin expression but defective activation.','B':'Correct. FERMT3 encodes kindlin-3, which is required for inside-out activation of hematopoietic-cell integrins; deficiency affects both leukocyte adhesion and platelet function.','C':'Loss of platelet alpha-IIb-beta3 causes Glanzmann thrombasthenia and bleeding but does not explain defective leukocyte integrin activation and recurrent infections.','D':'NADPH oxidase deficiency impairs intracellular killing after phagocytosis; it does not cause the combined leukocyte-and-platelet integrin activation defect.','E':'Endothelial selectin loss would affect leukocyte rolling but would not explain defective platelet integrin activation and bleeding.'},
 'Distinguish LAD-III from LAD-I and isolated platelet disorders by recognizing normal integrin surface expression with defective FERMT3/kindlin-3-dependent inside-out activation in both leukocytes and platelets.',
 [{'source_id':'Q1617-PUBMED','title':'Leukocyte adhesion deficiency-III is caused by mutations in KINDLIN3 affecting integrin activation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/19234463/','source_section_date':'2009-02-22','date_basis':'PubMed record reports Epub 2009-02-22; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'defective inside-out signaling causes immune deficiency and bleeding problems'}],
 'C','An isolated alpha-IIb-beta3 defect is the strongest bleeding alternative, but it cannot account for the leukocyte activation defect. LAD-III affects integrin activation across hematopoietic cells despite preserved surface expression, unifying the infection and bleeding phenotypes.')
