def build(make):
 return make(1616,'','Blood & Lymphoreticular/Immune Systems',['Immunology','Genetics','Cell Biology'],
 'A 13-year-old boy has persistent Epstein-Barr virus viremia, recurrent lymphadenopathy, and reduced cytotoxic activity of natural killer cells. Flow cytometry shows markedly decreased NKG2D on NK cells and CD8+ T cells. Sequencing identifies a loss-of-function variant in MAGT1. Immunoblotting of patient lymphocytes shows underglycosylated NKG2D protein with reduced steady-state expression.',
 'Which cellular process is most directly impaired by this mutation?',
 {'A':'N-linked glycosylation of selected proteins in the endoplasmic reticulum','B':'O-linked glycosylation of proteins in the Golgi apparatus','C':'TAP-dependent transport of cytosolic peptides into the endoplasmic reticulum','D':'Proteasomal degradation of ubiquitinated cytosolic proteins','E':'Attachment of glycosylphosphatidylinositol anchors to proteins in the endoplasmic reticulum'},
 'A','MAGT1 is an accessory component of the STT3B oligosaccharyltransferase machinery; its loss causes selective N-linked glycosylation defects, including hypoglycosylation and reduced expression of NKG2D',
 'MAGT1 functions with the endoplasmic-reticulum oligosaccharyltransferase machinery that catalyzes N-linked glycosylation of selected protein substrates. In MAGT1 deficiency, NKG2D is hypoglycosylated and its steady-state expression is reduced, impairing cytotoxic lymphocyte function and contributing to susceptibility to persistent EBV infection.',
 {'A':'Correct. MAGT1 deficiency causes selective N-linked glycosylation defects; NKG2D hypoglycosylation directly explains the reduced steady-state expression in the vignette.','B':'O-linked glycosylation is a distinct Golgi-centered glycosylation pathway and is not the MAGT1-dependent defect demonstrated in these patients.','C':'TAP transports cytosolic peptides into the endoplasmic reticulum for MHC class I loading; that pathway does not explain NKG2D hypoglycosylation.','D':'The ubiquitin-proteasome system degrades cytosolic proteins and does not account for the demonstrated glycosylation defect.','E':'GPI-anchor attachment is a distinct endoplasmic-reticulum modification and does not explain selective underglycosylation of NKG2D in MAGT1 deficiency.'},
 'Recognize MAGT1 deficiency as a selective N-linked glycosylation disorder in which NKG2D hypoglycosylation reduces NKG2D expression and compromises cytotoxic lymphocyte function.',
 [{'source_id':'Q1616-PUBMED-NLG','title':'Magnesium transporter 1 (MAGT1) deficiency causes selective defects in N-linked glycosylation and expression of immune-response genes','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/31337704/','source_section_date':'2019-07-23','date_basis':'PubMed reports Epub 2019-07-23; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'integral part of the N-linked glycosylation complex'},
  {'source_id':'Q1616-PUBMED-NKG2D','title':'Lack of NKG2D in MAGT1-deficient patients is caused by hypoglycosylation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/35182234/','source_section_date':'2022-02-19','date_basis':'PubMed reports Epub 2022-02-19; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'reduced steady-state levels of NKG2D are caused by hypoglycosylation of the protein'}],
 'B','O-linked glycosylation is the strongest same-category alternative because both are post-translational glycan modifications. The cited MAGT1 studies specifically establish an N-linked glycosylation defect and directly connect NKG2D hypoglycosylation to its reduced expression.')
