def build(make):
 return make(1616,'','Blood & Lymphoreticular/Immune Systems',['Immunology','Genetics','Cell Biology'],
 'A 13-year-old boy has persistent Epstein-Barr virus viremia, recurrent lymphadenopathy, and reduced cytotoxic activity of natural killer cells. Flow cytometry shows markedly decreased NKG2D on NK cells and CD8+ T cells. Sequencing identifies a loss-of-function variant in MAGT1. Immunoblotting of patient lymphocytes shows underglycosylated NKG2D protein with reduced steady-state expression.',
 'Which cellular process is most directly impaired by this mutation?',
 {'A':'N-linked glycosylation of selected proteins in the endoplasmic reticulum','B':'O-linked glycosylation of proteins in the Golgi apparatus','C':'TAP-dependent transport of cytosolic peptides into the endoplasmic reticulum','D':'Proteasomal degradation of ubiquitinated cytosolic proteins','E':'Attachment of glycosylphosphatidylinositol anchors to proteins in the endoplasmic reticulum'},
 'A','MAGT1 deficiency causes selective defects in N-linked glycosylation, including hypoglycosylation and reduced expression of NKG2D',
 'MAGT1 participates in the oligosaccharyltransferase machinery that supports N-linked glycosylation of selected proteins. In MAGT1 deficiency, NKG2D becomes hypoglycosylated and its steady-state surface expression falls, impairing cytotoxic lymphocyte function and contributing to susceptibility to persistent EBV infection.',
 {'A':'Correct. MAGT1 deficiency can impair N-linked glycosylation of selected proteins; NKG2D hypoglycosylation directly explains its reduced steady-state expression in the vignette.','B':'O-linked glycosylation occurs primarily in the Golgi and is not the defect demonstrated for NKG2D in MAGT1 deficiency.','C':'TAP transports peptides into the endoplasmic reticulum for MHC class I loading; loss causes an antigen-presentation defect rather than selective NKG2D hypoglycosylation.','D':'The ubiquitin-proteasome system degrades cytosolic proteins and does not account for the observed glycosylation defect.','E':'GPI-anchor attachment is a distinct endoplasmic-reticulum modification and does not explain selective underglycosylation of NKG2D in MAGT1 deficiency.'},
 'Recognize MAGT1 deficiency as a selective N-linked glycosylation disorder in which NKG2D hypoglycosylation reduces NKG2D expression and compromises cytotoxic lymphocyte function.',
 [{'source_id':'Q1616-PUBMED-PRIMARY','title':'Lack of NKG2D in MAGT1-deficient patients is caused by hypoglycosylation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/35182234/','source_section_date':'2022-02-19','date_basis':'PubMed record reports Epub 2022-02-19; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'reduced steady-state levels of NKG2D are caused by hypoglycosylation of the protein'}],
 'B','O-linked glycosylation is the strongest same-category alternative because both are post-translational glycan modifications, but the primary study directly demonstrates NKG2D hypoglycosylation from MAGT1 deficiency in the N-linked glycosylation pathway, not a Golgi O-glycosylation defect.')
