def build(make):
 return make(1619,'','Blood & Lymphoreticular/Immune Systems',['Hematology','Physiology','Genetics'],
 'A 24-year-old woman has lifelong compensated hemolysis, splenomegaly, and dehydrated erythrocytes with increased mean corpuscular hemoglobin concentration. Her father has similar findings. Sequencing identifies a gain-of-function variant in PIEZO1 that prolongs activity of the mechanically activated cation channel.',
 'Which downstream ionic sequence most directly causes erythrocyte dehydration in this disorder?',
 {'A':'Reduced calcium entry followed by inhibition of potassium efflux through the Gardos channel','B':'Increased sodium entry followed by osmotic water influx through aquaporin-1','C':'Increased chloride entry followed by activation of the erythrocyte sodium-potassium ATPase','D':'Increased calcium entry followed by activation of the KCa3.1 Gardos channel and loss of potassium and water','E':'Reduced proton extrusion followed by intracellular alkalinization and water loss'},
 'D','PIEZO1-mediated calcium entry activates the KCa3.1 Gardos channel, promoting potassium loss and erythrocyte dehydration',
 'PIEZO1 is a mechanically activated cation channel involved in erythrocyte volume regulation. Excess PIEZO1 activity increases calcium entry. The rise in intracellular calcium activates the calcium-sensitive KCa3.1 Gardos channel, driving potassium efflux; water follows osmotically, producing the dehydrated erythrocyte phenotype of hereditary xerocytosis/dehydrated hereditary stomatocytosis.',
 {'A':'The pathogenic sequence begins with increased, not reduced, calcium entry; Gardos-channel activation promotes rather than inhibits potassium loss.','B':'Sustained sodium and water influx would tend to swell erythrocytes rather than produce the characteristic dehydration.','C':'The experimentally demonstrated downstream effector of PIEZO1-mediated calcium entry is the KCa3.1 Gardos potassium channel, not a chloride-triggered increase in sodium-potassium ATPase activity.','D':'Correct. Increased PIEZO1-dependent calcium entry activates KCa3.1/Gardos channels, leading to potassium efflux and osmotic water loss from erythrocytes.','E':'Intracellular alkalinization is not the defining downstream mechanism linking PIEZO1 gain of function to erythrocyte dehydration.'},
 'Connect PIEZO1 gain of function in hereditary xerocytosis to calcium influx, secondary KCa3.1/Gardos-channel activation, potassium efflux, and osmotic water loss.',
 [{'source_id':'Q1619-PUBMED','title':'Piezo1 links mechanical forces to red blood cell volume','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/26001274/','source_section_date':'2015-05-22','date_basis':'PubMed record reports publication 2015-05-22; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'causes calcium influx and subsequent dehydration of RBCs via downstream activation of the KCa3.1 Gardos channel'}],
 'A','The strongest competing option uses the same calcium-Gardos components but reverses their direction. Primary experimental evidence shows PIEZO1 activation increases calcium influx and subsequently activates, rather than inhibits, the Gardos channel.')
