def build(make):
 return make(1612,'','Blood & Lymphoreticular/Immune Systems',['Immunology','Genetics','Cell Biology'],
 'A 9-year-old boy has severe eczema, food allergies, markedly elevated IgE, recurrent sinopulmonary infections, and extensive molluscum contagiosum and herpes simplex skin infections. Platelet count and platelet size are normal. In a three-dimensional collagen matrix, his activated T cells become abnormally elongated and fragment during migration.',
 'Which cellular defect most directly explains the abnormal migration-survival phenotype?',
 {'A':'Failure of STAT3-dependent T-helper 17 differentiation','B':'Failure of DOCK8-dependent CDC42/WASp actin-cytoskeleton organization in lymphocytes','C':'Loss of WASp causing defective actin polymerization with microthrombocytopenia','D':'Failure of phagocyte NADPH oxidase to generate superoxide','E':'Loss of Bruton tyrosine kinase signaling in B-cell precursors'},
 'B','DOCK8-dependent coupling of CDC42/WASp signaling to lymphocyte actin-cytoskeleton integrity',
 'DOCK8 functions upstream of CDC42 and WASp in T cells and is required for normal actin-cytoskeleton organization. DOCK8-deficient lymphocytes lose shape integrity during migration through confined three-dimensional tissues and may undergo cytothripsis, helping explain severe cutaneous viral susceptibility.',
 {'A':'STAT3 deficiency can cause hyper-IgE syndrome, but it does not produce the characteristic DOCK8-dependent three-dimensional lymphocyte shape-integrity defect.','B':'Correct. DOCK8 links CDC42/WASp signaling to actin organization needed for lymphocyte structural integrity and survival during migration.','C':'WASp deficiency also disrupts actin biology, but classic Wiskott-Aldrich syndrome is associated with microthrombocytopenia; normal platelet size/count and the described migration-fragmentation phenotype favor DOCK8 deficiency.','D':'NADPH oxidase deficiency causes defective phagocyte oxidative killing rather than a T-cell actin-cytoskeleton migration defect.','E':'BTK deficiency impairs B-cell maturation and immunoglobulin production rather than causing this hyper-IgE, cutaneous-viral, T-cell cytoskeletal phenotype.'},
 'Connect DOCK8 loss to defective CDC42/WASp-dependent actin organization and impaired lymphocyte integrity during migration through confined tissues.',
 [{'source_id':'Q1612-PMC','title':'A DOCK8-WIP-WASp complex links T cell receptors to the actin cytoskeleton','agency':'PubMed Central, U.S. National Library of Medicine','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC5096816/','source_section_date':None,'date_basis':'PMC full-text article live reverified 2026-09-18; no unsupported revision date inferred.','retrieved_at':'2026-09-18','section_locator':'Abstract; DOCK8 GEF activity is essential for the integrity of the subcortical actin cytoskeleton and TCR-driven actin polymerization'}],
 'C','Wiskott-Aldrich syndrome is the strongest alternative because WASp participates in the same actin pathway and causes infection and eczema, but classic WAS adds microthrombocytopenia, whereas the stipulated DOCK8-like three-dimensional migration-fragmentation phenotype occurs with normal platelet size and count.')
