def build(make):
 return make(1613,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neuroscience'],
 'A 4-year-old child has severe developmental delay, epilepsy, and dystonia. Proton magnetic resonance spectroscopy shows a markedly decreased cerebral creatine peak. Guanidinoacetate is elevated in plasma and urine, while creatine is low.',
 'Which reaction is directly deficient in this disorder?',
 {'A':'Transfer of an amidino group from arginine to glycine to form guanidinoacetate','B':'Sodium- and chloride-dependent uptake of creatine into brain and muscle','C':'S-adenosylmethionine-dependent methylation of guanidinoacetate to form creatine','D':'Phosphorylation of creatine to phosphocreatine by creatine kinase','E':'Hydrolysis of arginine to ornithine and urea by arginase'},
 'C','GAMT-catalyzed methylation of guanidinoacetate to creatine',
 'Creatine synthesis has two major enzymatic steps. After AGAT/GATM forms guanidinoacetate, guanidinoacetate methyltransferase (GAMT) uses S-adenosylmethionine to methylate guanidinoacetate and generate creatine. GAMT deficiency therefore causes guanidinoacetate accumulation with cerebral creatine deficiency.',
 {'A':'This is the upstream AGAT/GATM reaction; its deficiency lowers rather than raises guanidinoacetate.','B':'SLC6A8 transports already synthesized creatine; transporter deficiency does not directly block methylation of accumulated guanidinoacetate.','C':'Correct. GAMT catalyzes S-adenosylmethionine-dependent methylation of guanidinoacetate to creatine.','D':'Creatine kinase acts after creatine synthesis and does not explain guanidinoacetate accumulation.','E':'Arginase is part of the urea cycle and is not the blocked reaction in creatine synthesis.'},
 'Use elevated guanidinoacetate plus cerebral creatine deficiency to localize the block to the GAMT-catalyzed methylation step of creatine synthesis.',
 [{'source_id':'Q1613-GENEREVIEWS','title':'Creatine Deficiency Disorders - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK3794/','source_section_date':'2025-08-07','date_basis':'GeneReviews reports Last Revision: 2025-08-07; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Biochemical findings; Molecular Pathogenesis'}],
 'A','AGAT/GATM deficiency is the strongest alternative because it is the other creatine-biosynthesis defect, but it reduces guanidinoacetate production; the elevated guanidinoacetate in this vignette specifically localizes the block to GAMT.')
