def build(make):
 return make(1617,'','Gastrointestinal System',['Biochemistry','Genetics','Physiology'],
 'A 27-year-old man has recurrent episodes of confusion after carbohydrate-rich meals. During an episode, plasma ammonia and citrulline are markedly elevated. He has a longstanding preference for protein- and fat-rich foods. Genetic testing identifies biallelic loss-of-function variants in SLC25A13.',
 'Which mitochondrial transport process is most directly impaired?',
 {'A':'Import of ornithine from the cytosol into the mitochondrial matrix','B':'Export of aspartate from the mitochondrial matrix in exchange for glutamate plus a proton','C':'Export of citrate from the mitochondrial matrix in exchange for malate','D':'Import of pyruvate from the cytosol into the mitochondrial matrix','E':'Exchange of cytosolic ADP for mitochondrial ATP across the inner mitochondrial membrane'},
 'B','Citrin is the mitochondrial aspartate-glutamate carrier that exports aspartate to the cytosol while importing glutamate plus a proton',
 'SLC25A13 encodes citrin, a calcium-regulated aspartate-glutamate carrier in the inner mitochondrial membrane. Citrin exports mitochondrial aspartate to the cytosol while importing glutamate with a proton. Cytosolic aspartate is required for argininosuccinate synthesis in the urea cycle, and citrin is also a component of the malate-aspartate shuttle; loss therefore can produce hyperammonemia and citrullinemia.',
 {'A':'Mitochondrial ornithine import is mediated by ORNT1/SLC25A15 and is impaired in hyperornithinemia-hyperammonemia-homocitrullinuria syndrome, not citrin deficiency.','B':'Correct. Citrin exchanges mitochondrial aspartate for cytosolic glutamate plus a proton across the inner mitochondrial membrane.','C':'The mitochondrial citrate carrier SLC25A1 exchanges citrate and related tricarboxylates across the inner membrane; it is not the SLC25A13 transport step required to supply cytosolic aspartate.','D':'Mitochondrial pyruvate import is mediated by the mitochondrial pyruvate carrier, not citrin.','E':'ADP/ATP exchange is mediated by adenine nucleotide translocases and does not provide cytosolic aspartate for argininosuccinate synthesis.'},
 'Link SLC25A13/citrin deficiency to loss of mitochondrial aspartate export, impaired malate-aspartate shuttling, and reduced cytosolic aspartate availability for the urea cycle.',
 [{'source_id':'Q1617-GENEREVIEWS','title':'Citrin Deficiency - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1181/','source_section_date':'2025-03-20','date_basis':'GeneReviews reports Last Update: 2025-03-20; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Molecular Pathogenesis'}],
 'A','ORNT1-mediated ornithine import is the strongest alternative because it is another real inner-mitochondrial-membrane transport step linked to hyperammonemia. However, SLC25A13 specifically encodes the aspartate-glutamate carrier, and the citrullinemia phenotype follows reduced cytosolic aspartate availability rather than defective ornithine import.')
