def build(make):
 return make(1616,'','Nervous System & Special Senses',['Genetics','Biochemistry','Cell Biology'],
 'An 8-year-old girl has progressive ataxia, dysarthria, vertical supranuclear gaze palsy, and splenomegaly. Cultured skin fibroblasts show intense perinuclear filipin staining caused by lysosomal accumulation of unesterified cholesterol.',
 'Which cellular process is most directly impaired in this disorder?',
 {'A':'Intracellular trafficking of unesterified cholesterol and other lipid cargo out of late endosomal-lysosomal compartments by NPC1/NPC2','B':'Lysosomal hydrolysis of sphingomyelin by acid sphingomyelinase','C':'Receptor-mediated endocytosis of circulating LDL through the LDL receptor','D':'Esterification of free cholesterol in the endoplasmic reticulum by acyl-CoA:cholesterol acyltransferase','E':'Peroxisomal beta-oxidation of very-long-chain fatty acids'},
 'A','Loss of NPC1/NPC2 function causing lysosomal accumulation of unesterified cholesterol and other lipid cargo',
 'Niemann-Pick disease type C is caused by loss of NPC1 or NPC2 function. These proteins are involved in intracellular cholesterol handling; their deficiency causes lysosomal accumulation of lipid cargo, including unesterified cholesterol. The neurologic-visceral phenotype plus filipin-positive lysosomal cholesterol accumulation therefore points to defective NPC1/NPC2-dependent lipid trafficking.',
 {'A':'Correct. Loss of NPC1 or NPC2 function causes accumulation of unesterified cholesterol and other lipid cargo in lysosomes, reflecting impaired intracellular lipid trafficking.','B':'Acid sphingomyelinase deficiency causes acid sphingomyelinase deficiency disease with sphingomyelin accumulation, not the characteristic NPC lysosomal unesterified-cholesterol trafficking defect.','C':'LDL-receptor deficiency impairs plasma LDL clearance and causes hypercholesterolemia; it does not produce the characteristic NPC neurovisceral phenotype with lysosomal filipin-positive cholesterol accumulation.','D':'ACAT-mediated cholesterol esterification occurs in the endoplasmic reticulum and is not the primary defect in NPC1/NPC2 deficiency.','E':'Defective peroxisomal beta-oxidation causes accumulation of very-long-chain fatty acids rather than the NPC pattern of lysosomal unesterified-cholesterol accumulation.'},
 'Recognize Niemann-Pick disease type C as an NPC1/NPC2 loss-of-function disorder in which defective intracellular lipid trafficking produces lysosomal accumulation of unesterified cholesterol and other lipid cargo.',
 [{'source_id':'Q1616-GENEREVIEWS','title':'Niemann-Pick Disease Type C - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1296/','source_section_date':'2025-11-20','date_basis':'GeneReviews reports Last Update: 2025-11-20; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Molecular Pathogenesis'}],
 'B','Acid sphingomyelinase deficiency is the strongest lysosomal-storage alternative, but the vignette specifically identifies filipin-positive lysosomal unesterified cholesterol together with the classic NPC neurologic-visceral phenotype; NPC1/NPC2 loss directly produces that lipid-trafficking pattern.')
