def build(make):
 return make(1615,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neuroscience'],
 'A 5-year-old child has developmental delay, epilepsy, and autistic features. Urine and cerebrospinal fluid contain the normally undetectable succinylpurines succinylaminoimidazole carboxamide riboside (SAICAr) and succinyladenosine (S-Ado).',
 'Which pair of reactions is directly impaired by the deficient enzyme?',
 {'A':'Hypoxanthine to IMP and guanine to GMP through phosphoribosyl salvage','B':'IMP plus aspartate to adenylosuccinate and IMP to xanthosine monophosphate','C':'AICAR to formyl-AICAR and formyl-AICAR to IMP','D':'AMP to IMP and adenosine to inosine','E':'SAICAR to AICAR plus fumarate and adenylosuccinate to AMP plus fumarate'},
 'E','Adenylosuccinate lyase catalysis of two nonsequential purine-biosynthesis reactions that each release fumarate',
 'Adenylosuccinate lyase (ADSL) catalyzes two nonsequential reactions in de novo purine synthesis: cleavage of SAICAR to AICAR plus fumarate and cleavage of adenylosuccinate to AMP plus fumarate. ADSL deficiency leads to accumulation of dephosphorylated derivatives of its substrates, including SAICAr and S-Ado.',
 {'A':'HGPRT mediates purine salvage; failure produces a different metabolite pattern and does not explain SAICAr plus S-Ado accumulation.','B':'Adenylosuccinate synthetase forms adenylosuccinate, while IMP dehydrogenase directs IMP toward GMP synthesis; neither enzyme catalyzes both accumulating-substrate reactions.','C':'ATIC catalyzes later steps involving AICAR and IMP but does not cleave adenylosuccinate.','D':'AMP deaminase and adenosine deaminase act in nucleotide/nucleoside catabolism rather than the two ADSL reactions.','E':'Correct. ADSL cleaves SAICAR to AICAR and adenylosuccinate to AMP, releasing fumarate in both reactions.'},
 'Recognize adenylosuccinate lyase deficiency from succinylpurine accumulation and identify its two nonsequential fumarate-releasing reactions in de novo purine synthesis.',
 [{'source_id':'Q1615-PMC','title':'Adenylosuccinate lyase deficiency','agency':'PubMed Central, U.S. National Library of Medicine','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC4341013/','source_section_date':None,'date_basis':'PMC full-text review live reverified 2026-09-18; no unsupported revision date inferred.','retrieved_at':'2026-09-18','section_locator':'Abstract; Definition; Diagnosis, diagnostic criteria, diagnostic methods'}],
 'C','ATIC-pathway dysfunction is the strongest pathway-level alternative because AICAR participates in nearby de novo purine synthesis, but simultaneous accumulation of derivatives of both SAICAR and adenylosuccinate identifies the dual-substrate enzyme ADSL, not ATIC.')
