def build(make):
 return make(1612,'','Blood & Lymphoreticular/Immune Systems',['Immunology','Genetics','Cell Biology'],
 'A 9-year-old boy has severe eczema, food allergies, markedly elevated IgE, recurrent sinopulmonary infections, and extensive molluscum contagiosum and herpes simplex skin infections. Platelet count and platelet size are normal. In a three-dimensional collagen matrix, his activated T cells become abnormally elongated and fragment during migration.',
 'Which cellular defect most directly explains the abnormal migration-survival phenotype?',
 {'A':'Failure of STAT3-dependent T-helper 17 differentiation','B':'Failure of DOCK8-dependent CDC42-PAK signaling that coordinates cytoskeletal structures during confined lymphocyte migration','C':'Loss of WASp causing defective actin polymerization with microthrombocytopenia','D':'Failure of phagocyte NADPH oxidase to generate superoxide','E':'Loss of Bruton tyrosine kinase signaling in B-cell precursors'},
 'B','DOCK8-dependent CDC42-PAK control of lymphocyte shape integrity during migration through confined three-dimensional tissues',
 'DOCK8-deficient T and NK cells can elongate, undergo nuclear deformation, and fragment during migration through confined collagen-rich spaces. Experimental loss of DOCK8 or CDC42 and inhibition or knockdown of PAK1/2 reproduce this shape-integrity and survival defect, whereas loss of WASp does not. Thus the migration-survival phenotype is most directly explained by failure of the DOCK8-CDC42-PAK axis that coordinates cytoskeletal structures during cell movement.',
 {'A':'STAT3 deficiency can cause a hyper-IgE phenotype, but it does not explain the characteristic confined-migration elongation and cytothripsis phenotype.','B':'Correct. DOCK8 acts through CDC42 and PAK1/2 to preserve lymphocyte shape integrity during confined migration; disruption produces elongation, nuclear deformation, and cytothripsis.','C':'WASp deficiency disrupts actin biology and causes Wiskott-Aldrich syndrome, but experimental WASp loss did not reproduce the DOCK8-like elongation and cytothripsis phenotype; classic disease also features microthrombocytopenia.','D':'NADPH oxidase deficiency causes defective phagocyte oxidative killing rather than a T-cell shape-integrity defect during three-dimensional migration.','E':'BTK deficiency impairs B-cell maturation and immunoglobulin production rather than causing this hyper-IgE, cutaneous-viral, migration-fragmentation phenotype.'},
 'Connect DOCK8 loss to failure of CDC42-PAK-dependent coordination of cytoskeletal structures, causing lymphocyte elongation and cytothripsis during migration through confined tissues.',
 [{'source_id':'Q1612-PMC-CYTOTHRIPSIS','title':'DOCK8 regulates lymphocyte shape integrity for skin antiviral immunity','agency':'PubMed Central, U.S. National Library of Medicine','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC4267229/','source_section_date':None,'date_basis':'PMC full-text primary research article live reverified 2026-09-18; no unsupported revision date inferred.','retrieved_at':'2026-09-18','section_locator':'Abstract; DOCK8, through CDC42 and p21-activated kinase (PAK), regulates lymphocyte shape integrity to coordinate cytoskeletal structures during cell movement'}],
 'C','Wiskott-Aldrich syndrome is the strongest alternative because WASp affects actin and shares eczema and infection susceptibility, but the primary confined-migration experiment found that WASp loss did not reproduce the elongation/cytothripsis phenotype, while DOCK8, CDC42, and PAK1/2 perturbation did; normal platelet size and count further argue against classic WAS.')
