def build(make):
 return make(1614,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neuroscience'],
 'A 7-year-old boy has severe speech delay, intellectual disability, and seizures. Brain proton magnetic resonance spectroscopy shows a markedly decreased creatine peak. His urinary creatine-to-creatinine ratio is elevated, and cultured fibroblasts show markedly reduced uptake of extracellular creatine despite intact creatine biosynthesis.',
 'Which process is directly impaired?',
 {'A':'Formation of guanidinoacetate from arginine and glycine by AGAT','B':'Methylation of guanidinoacetate to creatine by GAMT','C':'Transfer of a phosphate group from ATP to creatine by creatine kinase','D':'Sodium- and chloride-dependent cellular uptake of creatine by SLC6A8','E':'Transport of long-chain fatty acids into mitochondria by the carnitine shuttle'},
 'D','SLC6A8-mediated sodium- and chloride-dependent creatine transport into brain and muscle',
 'SLC6A8 encodes the sodium- and chloride-dependent creatine transporter. Pathogenic variants cause creatine transporter deficiency, in which creatine synthesis can remain intact but cellular uptake into brain and muscle is impaired. Affected males commonly have an elevated urinary creatine-to-creatinine ratio and a reduced cerebral creatine peak.',
 {'A':'AGAT deficiency is a creatine-synthesis defect and would decrease guanidinoacetate; it does not explain defective uptake of extracellular creatine.','B':'GAMT deficiency blocks creatine synthesis and raises guanidinoacetate; the vignette instead demonstrates intact synthesis with defective uptake.','C':'Creatine kinase deficiency would affect phosphocreatine buffering after uptake and would not directly cause loss of SLC6A8-mediated cellular creatine transport.','D':'Correct. SLC6A8 is the sodium- and chloride-dependent transporter responsible for cellular creatine uptake, particularly relevant to brain and muscle.','E':'The carnitine shuttle transports fatty acyl groups rather than creatine.'},
 'Distinguish SLC6A8 creatine transporter deficiency from AGAT and GAMT biosynthetic defects by recognizing impaired cellular creatine uptake despite intact synthesis.',
 [{'source_id':'Q1614-GENEREVIEWS','title':'Creatine Deficiency Disorders - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK3794/','source_section_date':'2025-08-07','date_basis':'GeneReviews reports Last Revision: 2025-08-07; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Biochemical findings; Molecular Pathogenesis'}],
 'B','GAMT deficiency can also cause a low cerebral creatine peak and neurologic disease, but it is a synthesis defect with guanidinoacetate accumulation; direct failure of extracellular creatine uptake with intact synthesis identifies SLC6A8 transporter deficiency.')
