def build(make):
 return make(1611,'','Nervous System & Special Senses',['Biochemistry','Genetics','Pathology'],
 'A 2-day-old newborn develops refractory seizures, axial hypotonia, and apnea. Urine testing shows sulfite and S-sulfocysteine, serum uric acid is markedly decreased, and urinary xanthine and hypoxanthine are increased.',
 'Which biochemical defect best explains the combination of sulfur-metabolite and purine abnormalities?',
 {'A':'Loss of a shared molybdenum cofactor required by sulfite oxidase and xanthine oxidase','B':'Isolated deficiency of sulfite oxidase with intact molybdenum cofactor synthesis','C':'Isolated deficiency of xanthine oxidase with normal sulfite oxidation','D':'Deficiency of hypoxanthine-guanine phosphoribosyltransferase','E':'Deficiency of cystathionine beta-synthase'},
 'A','Molybdenum cofactor deficiency simultaneously reduces activity of sulfite oxidase and xanthine oxidase',
 'Molybdenum cofactor is required by several human enzymes, including sulfite oxidase and xanthine oxidase. Loss of the cofactor therefore causes sulfite/S-sulfocysteine accumulation together with impaired conversion of purine breakdown products to uric acid, producing low uric acid and increased xanthine/hypoxanthine.',
 {'A':'Correct. A shared molybdenum cofactor defect explains simultaneous sulfite oxidase and xanthine oxidase dysfunction.','B':'Isolated sulfite oxidase deficiency can reproduce the neurologic and sulfur-metabolite findings, but uric acid and xanthine/hypoxanthine are expected to remain normal because other molybdenum-cofactor enzymes are intact.','C':'Isolated xanthine oxidase deficiency explains low uric acid and xanthine accumulation but not sulfite or S-sulfocysteine accumulation.','D':'HGPRT deficiency disrupts purine salvage and causes hyperuricemia rather than the combined sulfite-oxidation and low-uric-acid pattern.','E':'Cystathionine beta-synthase deficiency causes homocystinuria and does not simultaneously impair xanthine oxidase.'},
 'Use the combined sulfur-metabolite and purine pattern to identify loss of a shared molybdenum cofactor rather than an isolated sulfite- or purine-pathway enzyme defect.',
 [{'source_id':'Q1611-GENEREVIEWS','title':'Molybdenum Cofactor Deficiency - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK575630/','source_section_date':'2023-02-02','date_basis':'GeneReviews reports Last Revision: 2023-02-02; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Differential Diagnosis; Molecular Pathogenesis'}],
 'B','Isolated sulfite oxidase deficiency is the strongest alternative because it can closely reproduce the neonatal neurologic and sulfur-metabolite phenotype, but it leaves uric acid and xanthine/hypoxanthine normal; the purine abnormalities require loss of the shared molybdenum cofactor.')
