def build(make):
 return make(1619,'','Gastrointestinal System',['Biochemistry','Genetics','Hematology'],
 'A 5-month-old infant has poor growth, chronic diarrhea, recurrent Pneumocystis jirovecii pneumonia, and megaloblastic anemia with pancytopenia. Serum folate and cerebrospinal-fluid 5-methyltetrahydrofolate are both very low, whereas vitamin B12 is normal. Genetic testing identifies biallelic loss-of-function variants in SLC46A1.',
 'Which transport defect most directly explains both the systemic and neurologic folate deficiency?',
 {'A':'Loss of folate receptor-alpha-mediated uptake at the choroid plexus with preserved intestinal folate absorption','B':'Loss of intrinsic-factor-dependent cobalamin uptake in the terminal ileum','C':'Loss of the reduced folate carrier that mediates folate entry into systemic tissues at near-neutral pH','D':'Loss of proton-coupled folate transport across the apical proximal small intestine and at the choroid plexus','E':'Loss of intracellular folylpolyglutamate synthesis that normally retains folates within cells'},
 'D','SLC46A1 encodes the proton-coupled folate transporter required for intestinal folate absorption and for folate transport into cerebrospinal fluid',
 'SLC46A1 encodes the proton-coupled folate transporter (PCFT). PCFT is highly expressed on the apical membrane of the proximal small intestine, where it mediates dietary folate absorption, and it also participates in folate transport at the choroid plexus. Loss therefore causes both systemic folate deficiency with megaloblastic cytopenias and severe cerebral folate deficiency.',
 {'A':'FOLR1 loss impairs folate transport into cerebrospinal fluid but typically leaves serum folate and the hemogram relatively preserved; it does not explain combined intestinal malabsorption and cerebral deficiency.','B':'Intrinsic factor mediates vitamin B12 absorption, not folate transport; this patient has normal vitamin B12.','C':'The reduced folate carrier is important for folate transport into many systemic cells, but SLC46A1 encodes PCFT, the transporter required for intestinal absorption and choroid-plexus folate transport.','D':'Correct. PCFT mediates proton-coupled folate uptake in the proximal intestine and contributes to folate transport into cerebrospinal fluid.','E':'Folylpolyglutamate synthesis retains folates intracellularly after uptake and does not explain the characteristic intestinal and choroid-plexus transport defect.'},
 'Distinguish hereditary folate malabsorption from isolated cerebral folate disorders by recognizing that SLC46A1/PCFT is required for both proximal-intestinal folate absorption and transport of folate into cerebrospinal fluid.',
 [{'source_id':'Q1619-GENEREVIEWS','title':'Hereditary Folate Malabsorption - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1673/','source_section_date':'2026-03-25','date_basis':'GeneReviews reports Last Update: 2026-03-25; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Molecular Pathogenesis'}],
 'A','FOLR1-related cerebral folate transport deficiency is the strongest alternative because it can produce very low CSF folate. However, FOLR1 loss does not explain profound systemic folate deficiency and megaloblastic pancytopenia from intestinal malabsorption, whereas SLC46A1/PCFT loss explains both compartments.')
