def build(make):
 return make(1618,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neurology'],
 'A newborn develops recurrent seizures that persist despite phenobarbital and levetiracetam but stop after intravenous pyridoxine. Urine and plasma contain markedly increased alpha-aminoadipic semialdehyde and piperideine-6-carboxylate. Genetic testing identifies biallelic pathogenic variants in ALDH7A1.',
 'Which biochemical mechanism most directly explains the pyridoxine dependence?',
 {'A':'Failure to oxidize pyridoxine phosphate to pyridoxal 5-prime-phosphate because of PNPO deficiency','B':'Loss of PLPBP-mediated maintenance of intracellular pyridoxal 5-prime-phosphate homeostasis','C':'Condensation of accumulated piperideine-6-carboxylate with pyridoxal 5-prime-phosphate, functionally inactivating the cofactor','D':'Failure of tissue-nonspecific alkaline phosphatase to dephosphorylate extracellular pyridoxal 5-prime-phosphate for cellular uptake','E':'Failure of pyridoxal kinase to phosphorylate intracellular pyridoxal to pyridoxal 5-prime-phosphate'},
 'C','ALDH7A1 deficiency causes P6C accumulation, which chemically condenses with and inactivates pyridoxal 5-prime-phosphate',
 'ALDH7A1 encodes alpha-aminoadipic semialdehyde dehydrogenase in lysine degradation. Deficiency causes accumulation of alpha-aminoadipic semialdehyde and its cyclic form, piperideine-6-carboxylate (P6C). P6C chemically condenses with pyridoxal 5-prime-phosphate (PLP), the active vitamin B6 cofactor, producing functional PLP deficiency and pyridoxine-responsive seizures.',
 {'A':'PNPO deficiency is a real vitamin B6-dependent epilepsy mechanism, but the ALDH7A1 biomarker pattern in this patient identifies PLP sequestration by P6C rather than impaired PNPO-mediated PLP production.','B':'PLPBP deficiency is another real cause of vitamin B6-dependent epilepsy, but it disrupts intracellular PLP homeostasis rather than causing the alpha-AASA/P6C accumulation shown here.','C':'Correct. Accumulated P6C condenses with PLP and functionally inactivates this vitamin B6 cofactor, producing pyridoxine dependence.','D':'Severe ALPL deficiency can produce vitamin B6-responsive seizures through impaired extracellular PLP dephosphorylation, but it does not produce the characteristic ALDH7A1 alpha-AASA/P6C biomarker pattern.','E':'Pyridoxal kinase generates intracellular PLP from pyridoxal; failure of that step is mechanistically distinct from the P6C-mediated cofactor inactivation caused by ALDH7A1 deficiency.'},
 'Recognize pyridoxine-dependent epilepsy due to ALDH7A1 deficiency as a lysine-catabolism disorder in which accumulated P6C chemically inactivates PLP.',
 [{'source_id':'Q1618-PUBMED-PRIMARY','title':'Biochemical and molecular characterization of 18 patients with pyridoxine-dependent epilepsy and mutations of the antiquitin (ALDH7A1) gene','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/17068770/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-18; no unsupported exact publication date inferred.','retrieved_at':'2026-09-18','section_locator':'The accumulating compound piperideine-6-carboxylic acid (P6C) was shown to inactivate pyridoxalphosphate (PLP) by a Knoevenagel condensation'}],
 'A','PNPO deficiency is the strongest clinical alternative because it can also cause neonatal vitamin B6-responsive epilepsy. The elevated alpha-AASA/P6C pattern and ALDH7A1 variants identify a different mechanism: chemical inactivation of PLP by P6C.')
