def build(make):
 return make(1624,'','Cardiovascular System',['Biochemistry','Genetics','Cell Biology'],
 'A newborn has bilateral congenital cataracts, hypertrophic cardiomyopathy, skeletal myopathy, and persistent lactic acidosis. Genetic testing identifies biallelic loss-of-function variants in AGK. Patient fibroblasts contain a destabilized inner-mitochondrial-membrane protein-import complex and reduced abundance of several mitochondrial carrier proteins.',
 'Which cellular function is most directly impaired?',
 {'A':'Recognition of N-terminal mitochondrial targeting sequences by the TOM20 receptor','B':'Cleavage of mitochondrial targeting peptides by the matrix processing peptidase','C':'Import of presequence-containing proteins into the mitochondrial matrix through the TIM23 complex','D':'TIM22-dependent import and assembly of multipass mitochondrial carrier proteins into the inner membrane','E':'TAFAZZIN-dependent remodeling of cardiolipin acyl chains within the inner mitochondrial membrane'},
 'D','AGK is a kinase-independent subunit of the TIM22 complex required for import and assembly of mitochondrial carrier proteins',
 'Although AGK can function as a lipid kinase, the Sengers-syndrome mechanism relevant here is kinase independent: AGK is a component of the mitochondrial TIM22 import complex. Loss destabilizes TIM22 and impairs import and assembly of carrier-family substrates in the inner mitochondrial membrane.',
 {'A':'TOM20 participates in initial recognition of many presequence-containing mitochondrial proteins at the outer membrane, but it is not the AGK-dependent defect described here.','B':'Matrix processing peptidase removes targeting presequences after import; AGK deficiency instead disrupts the TIM22 carrier-import machinery.','C':'TIM23 imports many presequence-containing proteins into the matrix or inner membrane, whereas AGK is specifically a subunit of the distinct TIM22 carrier pathway.','D':'Correct. AGK maintains TIM22-complex integrity and facilitates import and assembly of mitochondrial carrier proteins.','E':'TAFAZZIN deficiency causes Barth syndrome by defective cardiolipin remodeling; that is mechanistically distinct from AGK/TIM22 dysfunction.'},
 'Recognize Sengers syndrome due to AGK deficiency as a mitochondrial carrier-import disorder caused by disruption of the TIM22 complex, independent of AGK lipid-kinase activity.',
 [{'source_id':'Q1624-PUBMED-PRIMARY','title':'Sengers Syndrome-Associated Mitochondrial Acylglycerol Kinase Is a Subunit of the Human TIM22 Protein Import Complex','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/28712726/','source_section_date':'2017-07-14','date_basis':'PubMed reports Epub 2017-07-14; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'AGK functions in a kinase-independent manner to maintain the integrity of the TIM22 complex, where it facilitates the import and assembly of mitochondrial carrier proteins'}],
 'C','TIM23 is the strongest same-organelle alternative because it is another inner-membrane translocase. AGK, however, is a defined subunit of TIM22, the pathway for mitochondrial carrier proteins.')
