def build(make):
 return make(1625,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neurology'],
 'An 8-year-old boy has progressive dystonia, dysarthria, rigidity, and pigmentary retinal degeneration. T2-weighted MRI shows the characteristic eye-of-the-tiger appearance of the globus pallidus. Genetic testing identifies biallelic loss-of-function variants in PANK2.',
 'Which reaction is catalyzed by the deficient enzyme?',
 {'A':'Conversion of cysteine and pantothenate derivatives to phosphopantothenoylcysteine','B':'Decarboxylation of phosphopantothenoylcysteine to phosphopantetheine','C':'Adenylylation of phosphopantetheine to dephospho-coenzyme A','D':'Phosphorylation of dephospho-coenzyme A to coenzyme A','E':'ATP-dependent phosphorylation of pantothenate to 4-prime-phosphopantothenate'},
 'E','PANK2 is a pantothenate kinase that phosphorylates pantothenate at the entry step of coenzyme A biosynthesis',
 'PANK2 encodes a functional pantothenate kinase. Pantothenate kinase catalyzes ATP-dependent phosphorylation of pantothenate (vitamin B5), generating 4-prime-phosphopantothenate early in the coenzyme A biosynthetic pathway. Loss of PANK2 causes pantothenate kinase-associated neurodegeneration.',
 {'A':'Phosphopantothenoylcysteine synthetase catalyzes a later step after pantothenate phosphorylation and is not PANK2.','B':'Phosphopantothenoylcysteine decarboxylase catalyzes a later step in coenzyme A synthesis.','C':'Phosphopantetheine adenylyltransferase catalyzes adenylylation later in the pathway, not the PANK2 reaction.','D':'Dephospho-CoA kinase catalyzes the terminal phosphorylation step to form CoA; PANK2 acts much earlier.','E':'Correct. PANK2 phosphorylates pantothenate using ATP, producing 4-prime-phosphopantothenate in coenzyme A biosynthesis.'},
 'Link PANK2-associated neurodegeneration to loss of pantothenate kinase activity, which normally catalyzes ATP-dependent phosphorylation of vitamin B5 in coenzyme A biosynthesis.',
 [{'source_id':'Q1625-GENEREVIEWS','title':'Pantothenate Kinase-Associated Neurodegeneration - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1490/','source_section_date':'2017-08-03','date_basis':'GeneReviews reports Last Update: 2017-08-03; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Pantothenate kinase is an essential regulatory enzyme in CoA biosynthesis, catalyzing the phosphorylation of pantothenate (vitamin B5), N-pantothenoyl-cysteine, and pantetheine'}],
 'D','The final kinase step is a plausible pathway distractor, but PANK2 is pantothenate kinase and acts on pantothenate near the beginning of CoA synthesis, not on dephospho-CoA.')
