def build(make):
 return make(1627,'','Nervous System & Special Senses',['Cell Biology','Genetics','Neurology'],
 'A 5-year-old girl has nonprogressive cerebellar ataxia, short stature, and mild intellectual disability. Genetic testing identifies biallelic pathogenic variants in PMPCA. Patient fibroblasts accumulate precursor forms of several nuclear-encoded mitochondrial proteins, including incompletely processed frataxin, despite normal delivery of these proteins into mitochondria.',
 'Which cellular process is most directly impaired?',
 {'A':'Recognition of mitochondrial targeting sequences by TOM20 at the outer mitochondrial membrane','B':'Proteolytic maturation of imported mitochondrial precursor proteins by the mitochondrial processing peptidase','C':'TIM22-dependent insertion of multipass carrier proteins into the inner mitochondrial membrane','D':'Replication of mitochondrial DNA by DNA polymerase gamma','E':'Post-transcriptional polyadenylation of mitochondrial messenger RNAs'},
 'B','PMPCA encodes the alpha subunit of mitochondrial processing peptidase, which is required for maturation of many imported nuclear-encoded mitochondrial precursor proteins',
 'Most nuclear-encoded mitochondrial proteins are synthesized as precursor proteins carrying targeting presequences. After mitochondrial import, the mitochondrial processing peptidase removes targeting sequences to generate mature proteins. PMPCA encodes the alpha subunit of this processing complex; pathogenic variants impair precursor maturation, including processing of frataxin.',
 {'A':'TOM20 participates in initial recognition of many mitochondrial targeting sequences, but the vignette states that import occurs and precursor proteins accumulate after entry.','B':'Correct. PMPCA dysfunction impairs mitochondrial processing peptidase activity and therefore maturation of imported precursor proteins.','C':'TIM22 inserts a restricted class of multipass inner-membrane carriers; PMPCA deficiency instead causes defective proteolytic maturation of many imported precursor proteins.','D':'POLG replicates mitochondrial DNA and does not cleave targeting presequences from nuclear-encoded proteins.','E':'Mitochondrial mRNA polyadenylation is a post-transcriptional RNA process and cannot explain accumulation of unprocessed imported protein precursors.'},
 'Distinguish mitochondrial protein import from post-import processing: PMPCA deficiency impairs mitochondrial processing peptidase-mediated maturation of nuclear-encoded precursor proteins.',
 [{'source_id':'Q1627-PUBMED-PRIMARY','title':'PMPCA mutations cause abnormal mitochondrial protein processing in patients with non-progressive cerebellar ataxia','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/25808372/','source_section_date':'2015-03-25','date_basis':'PubMed reports Epub 2015-03-25; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'the primary enzyme responsible for the maturation of the vast majority of nuclear-encoded mitochondrial proteins'}],
 'A','TOM20 is the strongest same-pathway alternative because it acts on mitochondrial precursor proteins before import. The explicit accumulation of precursors after successful mitochondrial delivery localizes the defect to post-import processing by mitochondrial processing peptidase.')
