def build(make):
 return make(1622,'','Multisystem Processes & Disorders',['Biochemistry','Genetics','Metabolism'],
 'A 2-year-old boy has developmental regression, chronic diarrhea, recurrent petechiae and acrocyanosis, and episodic metabolic acidosis. Urine contains markedly increased ethylmalonic acid, and plasma C4 and C5 acylcarnitines are elevated. Muscle biopsy shows reduced cytochrome c oxidase activity. Genetic testing identifies biallelic loss-of-function variants in ETHE1.',
 'Which mechanism most directly explains the respiratory-chain abnormality?',
 {'A':'Failure to insert copper into cytochrome c oxidase, preventing assembly of complex IV','B':'Failure of mitochondrial sulfide oxidation, causing hydrogen sulfide accumulation that secondarily inhibits cytochrome c oxidase','C':'Defective transfer of electrons from succinate to ubiquinone at respiratory-chain complex II','D':'Failure to synthesize mitochondrial-encoded cytochrome c oxidase subunits because of mitochondrial DNA depletion','E':'Failure of coenzyme Q biosynthesis, limiting electron transfer from complexes I and II to complex III'},
 'B','ETHE1 is a mitochondrial sulfur dioxygenase; its loss causes sulfide accumulation that inhibits cytochrome c oxidase',
 'ETHE1 participates in mitochondrial sulfide detoxification as a sulfur dioxygenase. ETHE1 deficiency causes hydrogen sulfide to accumulate. Sulfide is a potent inhibitor of cytochrome c oxidase and short-chain fatty-acid oxidation, accounting for the secondary complex IV defect and characteristic biochemical phenotype of ethylmalonic encephalopathy.',
 {'A':'Copper-delivery defects can cause primary complex IV deficiency but do not explain the ETHE1 genotype, ethylmalonic aciduria, or sulfide toxicity.','B':'Correct. Loss of ETHE1 blocks mitochondrial sulfide oxidation; accumulated hydrogen sulfide inhibits cytochrome c oxidase.','C':'Complex II dysfunction impairs succinate oxidation and electron transfer to ubiquinone but is not the ETHE1-dependent lesion.','D':'Mitochondrial DNA depletion can reduce respiratory-chain complexes containing mtDNA-encoded subunits, but ETHE1 deficiency causes a toxic-metabolite-mediated secondary complex IV defect.','E':'Primary coenzyme Q deficiency impairs electron transfer from complexes I and II to complex III, a real respiratory-chain mechanism that does not explain the sulfide accumulation caused by ETHE1 loss.'},
 'Link ETHE1 deficiency to impaired mitochondrial sulfide detoxification and secondary inhibition of cytochrome c oxidase by accumulated hydrogen sulfide.',
 [{'source_id':'Q1622-PUBMED-PRIMARY','title':'Loss of ETHE1, a mitochondrial dioxygenase, causes fatal sulfide toxicity in ethylmalonic encephalopathy','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/19136963/','source_section_date':'2009-01-11','date_basis':'PubMed reports Epub 2009-01-11; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'ETHE1 is a mitochondrial sulfur dioxygenase involved in catabolism of sulfide that accumulates to toxic levels in ethylmalonic encephalopathy'}],
 'A','A primary complex-IV assembly defect is a strong alternative because muscle cytochrome c oxidase activity is low. The ETHE1 genotype plus ethylmalonic biochemical pattern instead identifies secondary COX inhibition from sulfide accumulation.')
