def build(make):
 return make(1620,'','Endocrine System',['Endocrinology','Genetics','Cell Biology'],
 'A 2-year-old boy is evaluated after recurrent fasting hypoglycemia and seizures. He has diffuse hyperpigmentation. Morning cortisol is very low and plasma ACTH is markedly elevated, but serum sodium, potassium, plasma renin activity, and aldosterone are normal. Sequencing shows no pathogenic variant in the coding region of MC2R. In cultured adrenal cells, the ACTH receptor is synthesized but fails to reach the plasma membrane.',
 'Which protein defect most directly explains these findings?',
 {'A':'Loss of steroidogenic acute regulatory protein, preventing mitochondrial cholesterol transport','B':'Loss of 21-hydroxylase, impairing cortisol and aldosterone synthesis','C':'Activating mutation of the calcium-sensing receptor, suppressing parathyroid hormone release','D':'Loss of the glucocorticoid receptor, causing peripheral cortisol resistance','E':'Loss of MRAP, preventing normal trafficking of the melanocortin-2 ACTH receptor to the cell surface'},
 'E','MRAP deficiency preventing trafficking of MC2R/ACTH receptor to the adrenal-cell surface',
 'Familial glucocorticoid deficiency can result from defects in MRAP, the melanocortin-2 receptor accessory protein. MRAP is required for trafficking MC2R, the ACTH receptor, to the cell surface. Failure of this step produces ACTH resistance with very low cortisol and compensatory ACTH elevation while mineralocorticoid function can remain preserved.',
 {'A':'StAR deficiency causes lipoid congenital adrenal hyperplasia with broad adrenal and gonadal steroid deficiency rather than isolated ACTH resistance with preserved mineralocorticoid function.','B':'21-hydroxylase deficiency impairs both cortisol synthesis and, in classic salt-wasting disease, mineralocorticoid synthesis; it does not specifically prevent MC2R surface trafficking.','C':'Calcium-sensing receptor activation causes hypocalcemia with low or inappropriately normal parathyroid hormone and does not explain ACTH resistance.','D':'Glucocorticoid-receptor resistance generally produces elevated cortisol as well as elevated ACTH, rather than severe cortisol deficiency from failure of adrenal ACTH signaling.','E':'Correct. MRAP is an accessory protein essential for trafficking MC2R to the cell surface; loss causes familial glucocorticoid deficiency with ACTH resistance.'},
 'Recognize MRAP as the accessory protein required for MC2R/ACTH-receptor surface trafficking and link its loss to familial glucocorticoid deficiency with preserved mineralocorticoid function.',
 [{'source_id':'Q1620-PUBMED','title':'Familial glucocorticoid deficiency: advances in the molecular understanding of ACTH action','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/18059087/','source_section_date':'2007-12-05','date_basis':'PubMed record reports Epub 2007-12-05; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'MRAP encodes a small single transmembrane domain protein, which is essential in the trafficking of the MC2R to the cell surface'}],
 'B','Congenital adrenal hyperplasia can produce low cortisol and high ACTH, but 21-hydroxylase deficiency does not explain preserved mineralocorticoid indices plus direct demonstration that synthesized MC2R fails to reach the plasma membrane; MRAP directly controls that trafficking step.')
