def build(make):
 return make(1628,'','Blood & Lymphoreticular/Immune Systems',['Biochemistry','Genetics','Immunology'],
 'A 6-year-old boy has recurrent bacterial and viral infections, severe eczema, skeletal dysplasia, and developmental delay. Laboratory studies show lymphopenia and reduced intracellular UDP-N-acetylglucosamine. Genetic testing identifies biallelic hypomorphic variants in PGM3, and patient cells show reduced N-linked and O-linked protein glycosylation.',
 'Which metabolic reaction is most directly impaired?',
 {'A':'Conversion of fructose-6-phosphate and glutamine to glucosamine-6-phosphate','B':'Acetylation of glucosamine-6-phosphate to N-acetylglucosamine-6-phosphate','C':'Conversion of N-acetylglucosamine-6-phosphate to N-acetylglucosamine-1-phosphate','D':'Formation of UDP-N-acetylglucosamine from N-acetylglucosamine-1-phosphate and UTP','E':'Epimerization of UDP-N-acetylglucosamine to initiate sialic-acid biosynthesis'},
 'C','PGM3 converts N-acetylglucosamine-6-phosphate to N-acetylglucosamine-1-phosphate during UDP-GlcNAc synthesis',
 'PGM3 is a phosphoacetylglucosamine mutase in the hexosamine biosynthetic pathway. It converts GlcNAc-6-phosphate to GlcNAc-1-phosphate, which is subsequently used to generate UDP-GlcNAc. UDP-GlcNAc supplies multiple glycosylation pathways, explaining the combined immune, skeletal, and neurologic phenotype when PGM3 activity is reduced.',
 {'A':'GFPT catalyzes the upstream formation of glucosamine-6-phosphate from fructose-6-phosphate and glutamine; this is not the PGM3 reaction.','B':'GNPNAT1 catalyzes acetylation of glucosamine-6-phosphate upstream of PGM3.','C':'Correct. PGM3 interconverts GlcNAc-6-phosphate and GlcNAc-1-phosphate, supplying substrate for UDP-GlcNAc synthesis.','D':'UAP1 catalyzes the downstream uridylation step that forms UDP-GlcNAc from GlcNAc-1-phosphate and UTP.','E':'GNE uses UDP-GlcNAc at the entry to sialic-acid biosynthesis; it is downstream of UDP-GlcNAc production and is not the PGM3 reaction.'},
 'Link PGM3 immunodeficiency to impaired GlcNAc-6-phosphate to GlcNAc-1-phosphate conversion and reduced UDP-GlcNAc availability for protein glycosylation.',
 [{'source_id':'Q1628-PUBMED-PRIMARY','title':'PGM3 mutations cause a congenital disorder of glycosylation with severe immunodeficiency and skeletal dysplasia','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/24931394/','source_section_date':'2014-06-12','date_basis':'PubMed reports Epub 2014-06-12; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'catalyzes the conversion of N-acetyl-glucosamine (GlcNAc)-6-phosphate into GlcNAc-1-phosphate'}],
 'D','The UAP1 uridylation step is the strongest adjacent-pathway alternative because it immediately follows PGM3 and also controls UDP-GlcNAc production. The gene and source-bound reaction specifically identify the phosphomutase step as the lesion.')
