def build(make):
 return make(1628,'','Blood & Lymphoreticular/Immune Systems',['Biochemistry','Genetics','Immunology'],
 'A 6-year-old boy has recurrent bacterial and viral infections, severe eczema, skeletal dysplasia, and developmental delay. Laboratory studies show lymphopenia. Genetic testing identifies biallelic hypomorphic variants in PGM3, and patient cells show reduced N-linked and O-linked protein glycosylation.',
 'Which intracellular nucleotide-sugar pool is most directly reduced by this enzyme defect?',
 {'A':'GDP-mannose','B':'UDP-galactose','C':'UDP-N-acetylglucosamine','D':'CMP-N-acetylneuraminic acid','E':'UDP-glucuronic acid'},
 'C','PGM3 activity is required for synthesis of UDP-N-acetylglucosamine, a donor substrate used by multiple N-linked and O-linked glycosylation pathways',
 'PGM3 converts N-acetylglucosamine-6-phosphate to N-acetylglucosamine-1-phosphate in the hexosamine biosynthetic pathway. Reduced PGM3 activity lowers the cellular UDP-GlcNAc pool, limiting substrate availability for multiple glycosylation reactions and producing immune, skeletal, and neurologic abnormalities.',
 {'A':'GDP-mannose supplies mannose residues for several glycoconjugates but is generated through a different mannose pathway and is not the primary nucleotide-sugar deficit in PGM3 deficiency.','B':'UDP-galactose is generated from UDP-glucose by UDP-galactose 4-epimerase and is not the nucleotide-sugar pool directly reduced by PGM3 loss.','C':'Correct. PGM3 deficiency lowers UDP-GlcNAc, compromising both N-linked and O-linked protein glycosylation.','D':'CMP-sialic acid is the activated donor for terminal sialylation; its synthesis is downstream of a distinct pathway and is not the primary PGM3-dependent pool.','E':'UDP-glucuronic acid is produced by oxidation of UDP-glucose and is used in glycosaminoglycan synthesis and glucuronidation, not as the primary product of the PGM3-dependent pathway.'},
 'Recognize PGM3 immunodeficiency as a hexosamine-pathway defect that lowers UDP-GlcNAc availability and thereby compromises multiple protein-glycosylation pathways.',
 [{'source_id':'Q1628-PUBMED-PRIMARY','title':'Autosomal recessive phosphoglucomutase 3 (PGM3) mutations link glycosylation defects to atopy, immune deficiency, autoimmunity, and neurocognitive impairment','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/24589341/','source_section_date':'2014-02-28','date_basis':'PubMed reports Epub 2014-02-28; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'reduced uridine diphosphate-N-acetyl-D-glucosamine, along with decreased O- and N-linked protein glycosylation in patients cells'}],
 'D','CMP-sialic acid is the strongest downstream glycosylation alternative because abnormal sialylation can occur when glycan synthesis is disturbed. The primary biochemical defect demonstrated in PGM3-deficient cells is reduction of UDP-GlcNAc itself.')
