def build(make):
 return make(1627,'','Blood & Lymphoreticular/Immune Systems',['Cell Biology','Genetics','Immunology'],
 'A 5-year-old boy has silvery-gray hair, recurrent fevers, splenomegaly, pancytopenia, and markedly elevated ferritin. Genetic testing identifies biallelic loss-of-function variants in RAB27A. Cytotoxic T cells contain normal amounts of perforin, form conjugates with target cells, and polarize lytic granules toward the immunologic synapse, but show markedly reduced degranulation and target-cell killing.',
 'Which cellular step is most directly impaired?',
 {'A':'Synthesis of perforin within cytotoxic lymphocytes','B':'Membrane docking and regulated exocytosis of polarized lytic granules at the immunologic synapse','C':'MUNC13-4-dependent priming of already docked cytolytic granules for membrane fusion','D':'Syntaxin-11-dependent SNARE fusion after granule priming','E':'LYST-dependent regulation of lysosomal granule size and trafficking'},
 'B','RAB27A is required for regulated cytotoxic-granule secretion; RAB27A-deficient lytic granules polarize toward the immunologic synapse but fail to dock efficiently at the plasma membrane',
 'RAB27A is a small Rab GTPase required for terminal trafficking of cytotoxic secretory lysosomes. In RAB27A deficiency, cytotoxic granules can polarize toward the immunologic synapse but fail membrane docking and regulated release, producing defective NK-cell and cytotoxic T-cell killing and predisposing to hemophagocytic lymphohistiocytosis.',
 {'A':'Perforin deficiency causes familial HLH type 2, but the vignette specifies normal perforin abundance and a defect in granule release rather than granule cargo synthesis.','B':'Correct. RAB27A deficiency causes failure of membrane docking and regulated exocytosis of polarized lytic granules at the immunologic synapse.','C':'UNC13D/MUNC13-4 deficiency disrupts the priming step after granules have docked; it is a closely related but distinct exocytic defect.','D':'STX11 participates in the downstream SNARE fusion machinery; RAB27A acts earlier in terminal granule docking/exocytosis.','E':'LYST deficiency causes Chediak-Higashi syndrome with abnormal giant lysosomal granules, a distinct organelle-trafficking defect.'},
 'Differentiate defects within the cytotoxic-granule pathway: RAB27A deficiency impairs docking and regulated exocytosis of polarized lytic granules, causing Griscelli syndrome type 2 with HLH susceptibility.',
 [{'source_id':'Q1627-PUBMED-PRIMARY','title':'Rab27a is required for regulated secretion in cytotoxic T lymphocytes','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/11266472/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'polarization but no membrane docking of ash/ash lytic granules at the immunological synapse'}],
 'C','MUNC13-4 deficiency is the strongest pathway-level alternative because it also causes HLH with defective degranulation. However, MUNC13-4 acts in priming after docking, whereas RAB27A deficiency specifically produces failure of lytic-granule membrane docking despite polarization.')
