def build(make):
 return make(1621,'','Blood & Lymphoreticular/Immune Systems',['Biochemistry','Genetics','Hematology'],
 'A 7-year-old girl has chronic macrocytic anemia with ring sideroblasts, insulin-requiring diabetes mellitus, and progressive sensorineural hearing loss. Serum vitamin B12 and folate concentrations are normal. Her anemia improves substantially after pharmacologic-dose thiamine. Genetic testing identifies biallelic loss-of-function variants in SLC19A2.',
 'Which cellular process is most directly impaired in this disorder?',
 {'A':'High-affinity transport of thiamine across the plasma membrane into susceptible cells','B':'Conversion of thiamine to thiamine pyrophosphate by thiamine pyrophosphokinase','C':'Transport of thiamine pyrophosphate across the inner mitochondrial membrane','D':'Reabsorption of filtered thiamine by a proximal-tubule organic cation transporter','E':'Binding of thiamine pyrophosphate to the E1 subunit of pyruvate dehydrogenase'},
 'A','SLC19A2 encodes the high-affinity thiamine transporter THTR1; loss reduces cellular thiamine uptake',
 'SLC19A2 encodes thiamine transporter 1, a high-affinity plasma-membrane transporter. Loss of this transport system lowers intracellular thiamine in susceptible tissues, producing thiamine-responsive megaloblastic anemia syndrome with the characteristic anemia, diabetes, and sensorineural deafness triad.',
 {'A':'Correct. SLC19A2 loss impairs high-affinity cellular thiamine uptake through THTR1.','B':'Thiamine pyrophosphokinase acts after thiamine has entered the cell and is not encoded by SLC19A2.','C':'Mitochondrial thiamine-pyrophosphate transport is a distinct step and does not explain the SLC19A2 transport phenotype.','D':'The defining defect is high-affinity cellular thiamine uptake, not isolated renal reabsorption of filtered thiamine.','E':'Binding of thiamine pyrophosphate to thiamine-dependent enzymes can be secondarily limited when intracellular thiamine is low, but it is not the primary SLC19A2 defect.'},
 'Recognize thiamine-responsive megaloblastic anemia syndrome as loss of SLC19A2/THTR1-mediated high-affinity cellular thiamine transport.',
 [{'source_id':'Q1621-GENEREVIEWS','title':'Thiamine-Responsive Megaloblastic Anemia Syndrome - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1282/','source_section_date':'2022-07-28','date_basis':'GeneReviews reports Last Update: 2022-07-28; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Defect of a high-affinity thiamine transporter, SLC19A2, causes thiamine-responsive megaloblastic anemia syndrome (TRMA)'}],
 'B','A defect in thiamine activation could also impair thiamine-dependent metabolism, but the phenotype and SLC19A2 genotype specifically identify failure of high-affinity membrane transport; intracellular activation is downstream.')
