def build(make):
 return make(1623,'','Multisystem Processes & Disorders',['Biochemistry','Genetics','Cell Biology'],
 'An infant has severe developmental delay, seizures, short limbs, hearing loss, and abnormal transferrin glycosylation consistent with a type II congenital disorder of glycosylation. Serum manganese is below the limit of detection. Genetic testing identifies biallelic pathogenic variants in SLC39A8, which encodes the ZIP8 metal transporter.',
 'Reduced activity of which enzyme most directly links the trace-element abnormality to the glycosylation defect?',
 {'A':'Dolichol-phosphate mannosyltransferase in the endoplasmic reticulum','B':'Mannosyl-oligosaccharide glucosidase I in the endoplasmic reticulum','C':'Beta-1,4-galactosyltransferase in the Golgi apparatus','D':'N-acetylglucosaminyl-1-phosphotransferase in the cis-Golgi','E':'UDP-glucose:glycoprotein glucosyltransferase in the endoplasmic reticulum'},
 'C','SLC39A8 deficiency causes manganese deficiency, reducing activity of manganese-dependent Golgi beta-1,4-galactosyltransferase',
 'ZIP8/SLC39A8 mediates manganese uptake. Severe loss of transporter function can produce profound manganese deficiency. Manganese is required by several enzymes, and impaired activity of manganese-dependent Golgi beta-1,4-galactosyltransferase causes defective galactosylation and a type II congenital disorder of glycosylation.',
 {'A':'Dolichol-phosphate mannosyltransferase participates in assembly of the lipid-linked oligosaccharide precursor but is not the manganese-dependent enzyme highlighted in SLC39A8 deficiency.','B':'MOGS/glucosidase I trims glucose from N-linked glycans in the endoplasmic reticulum and is not the principal manganese-dependent lesion in this disorder.','C':'Correct. Manganese deficiency from SLC39A8 loss impairs manganese-dependent beta-1,4-galactosyltransferase and therefore Golgi glycan processing.','D':'N-acetylglucosaminyl-1-phosphotransferase creates the mannose-6-phosphate targeting signal for lysosomal enzymes; this is a distinct Golgi pathway.','E':'UGGT participates in ER glycoprotein quality control and is not the manganese-dependent galactosylation step disrupted by SLC39A8 deficiency.'},
 'Recognize SLC39A8 deficiency as impaired cellular manganese uptake that causes secondary dysfunction of manganese-dependent glycosyltransferases, especially Golgi beta-1,4-galactosyltransferase.',
 [{'source_id':'Q1623-PUBMED-PRIMARY','title':'SLC39A8 Deficiency: A Disorder of Manganese Transport and Glycosylation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/26637979/','source_section_date':'2015-12-03','date_basis':'PubMed reports publication 2015-12-03; live record reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'variants in SLC39A8 impair the function of manganese-dependent enzymes, most notably β-1,4-galactosyltransferase'}],
 'B','Glucosidase I is a plausible glycosylation-pathway alternative, but it catalyzes ER glucose trimming. The trace-element clue points to manganese-dependent Golgi beta-1,4-galactosyltransferase.')
