def build(make):
 return make(1629,'','Multisystem Processes & Disorders',['Cell Biology','Genetics','Molecular Biology'],
 'A 2-year-old boy from a French-Canadian founder population has developmental delay and recurrent episodes of severe lactic acidosis during minor illnesses. Muscle studies show a marked cytochrome c oxidase deficiency. Genetic testing identifies biallelic pathogenic variants in LRPPRC. Mitochondrial DNA copy number is normal, but steady-state levels of multiple mitochondrial messenger RNAs are markedly reduced.',
 'Which molecular process is most directly impaired?',
 {'A':'Replication of mitochondrial DNA by DNA polymerase gamma','B':'Initiation of mitochondrial transcription by the POLRMT-TFAM machinery','C':'Cleavage of polycistronic mitochondrial transcripts at transfer-RNA boundaries','D':'Post-transcriptional stabilization and polyadenylation of mitochondrial messenger RNAs','E':'Aminoacylation of mitochondrial transfer RNAs before translation'},
 'D','LRPPRC forms an RNA-binding complex that stabilizes mitochondrial mRNAs and supports their polyadenylation and coordinated translation',
 'LRPPRC acts at the post-transcriptional level in mitochondria. In complex with RNA-binding partners such as SLIRP, it helps maintain mitochondrial mRNA stability and polyadenylation and coordinates translation. LRPPRC deficiency therefore lowers steady-state mitochondrial mRNA levels despite preserved mitochondrial DNA copy number.',
 {'A':'POLG-dependent mtDNA replication failure would reduce or deplete mitochondrial DNA itself; copy number is normal in this vignette.','B':'POLRMT and TFAM are central to mitochondrial transcription initiation, but LRPPRC primarily regulates mitochondrial RNA after transcription.','C':'Mitochondrial transcript cleavage is performed by RNA-processing machinery at tRNA junctions and is not the principal LRPPRC function.','D':'Correct. LRPPRC loss destabilizes mitochondrial mRNAs and impairs their polyadenylation and coordinated translation.','E':'Aminoacyl-tRNA synthetases charge mitochondrial tRNAs; failure of that process does not directly explain selective loss of steady-state mitochondrial mRNAs.'},
 'Recognize LRPPRC deficiency as a post-transcriptional mitochondrial gene-expression defect involving mRNA stabilization, polyadenylation, and coordinated translation.',
 [{'source_id':'Q1629-PUBMED-PRIMARY','title':'LRPPRC is necessary for polyadenylation and coordination of translation of mitochondrial mRNAs','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/22045337/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'leads to loss of mRNA polyadenylation'}],
 'B','A primary transcription-initiation defect is the strongest alternative because it could also lower mitochondrial mRNA abundance. The source and normal mtDNA copy number support a post-transcriptional LRPPRC defect in mRNA stability/polyadenylation rather than impaired transcription initiation.')
