def build(make):
 return make(1626,'','Multisystem Processes & Disorders',['Biochemistry','Genetics','Metabolism'],
 'A 4-month-old boy has recurrent episodes of severe lactic acidosis and hypotonia. Enzyme assays show markedly reduced pyruvate dehydrogenase and 2-ketoglutarate dehydrogenase activities. Glycine concentration is normal. Immunoblotting shows markedly decreased lipoylation of the E2 subunits of both dehydrogenase complexes but preserved lipoylation of the H protein of the glycine cleavage system. Genetic testing identifies biallelic pathogenic variants in LIPT1.',
 'Which biochemical process is most directly impaired?',
 {'A':'Transfer of lipoyl groups to selected E2 subunits of mitochondrial 2-ketoacid dehydrogenase complexes','B':'Insertion of sulfur atoms into protein-bound octanoyl groups by mitochondrial lipoic acid synthetase','C':'Covalent attachment of biotin to mitochondrial carboxylases by holocarboxylase synthetase','D':'Binding of thiamine pyrophosphate to the E1 subunit of pyruvate dehydrogenase','E':'Transport of pyruvate from the cytosol into the mitochondrial matrix'},
 'A','LIPT1 is required for transfer of lipoic acid to selected 2-ketoacid dehydrogenase proteins, allowing their lipoylation and activation',
 'LIPT1 deficiency causes a selective lipoic-acid transfer defect. The E2 subunits of pyruvate dehydrogenase and 2-ketoglutarate dehydrogenase require covalently attached lipoate for catalytic activity. In the original human LIPT1 disorder, lipoylation of these E2 proteins was markedly reduced while lipoylation of the glycine-cleavage H protein was preserved, distinguishing defective lipoate transfer to selected proteins from a generalized failure of lipoic-acid synthesis.',
 {'A':'Correct. LIPT1 is required for lipoylation and activation of selected 2-ketoacid dehydrogenases.','B':'LIAS inserts sulfur into protein-bound octanoyl groups during mitochondrial lipoate biosynthesis; a generalized LIAS defect would not fit the preserved H-protein lipoylation described in the vignette.','C':'Holocarboxylase synthetase attaches biotin to biotin-dependent carboxylases; it does not lipoylate the E2 subunits of PDH or 2-KGDH.','D':'Thiamine pyrophosphate is a required E1 cofactor, but the demonstrated abnormality is loss of E2 lipoylation rather than impaired TPP binding.','E':'Mitochondrial pyruvate transport occurs upstream of PDH and cannot explain simultaneous loss of PDH and 2-KGDH activity with selective E2 hypolipoylation.'},
 'Recognize LIPT1 deficiency as a selective mitochondrial lipoate-transfer defect that reduces lipoylation and activity of 2-ketoacid dehydrogenase complexes.',
 [{'source_id':'Q1626-PUBMED-PRIMARY','title':'Mutations in the lipoyltransferase LIPT1 gene cause a fatal disease associated with a specific lipoylation defect of the 2-ketoacid dehydrogenase complexes','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/24256811/','source_section_date':'2013-11-20','date_basis':'PubMed reports Epub 2013-11-20; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'LIPT1 protein is required for lipoylation and activation of 2-ketoacid dehydrogenases in humans'}],
 'B','Generalized lipoic-acid synthesis failure is the strongest alternative because it can also impair lipoate-dependent enzymes. Preserved H-protein lipoylation together with selective E2 hypolipoylation supports a LIPT1 transfer defect rather than LIAS failure.')
