def build(make):
 return make(1621,'','Blood & Lymphoreticular/Immune Systems',['Biochemistry','Genetics','Hematology'],
 'A 7-year-old girl has chronic macrocytic anemia with ring sideroblasts, insulin-requiring diabetes mellitus, and progressive sensorineural hearing loss. Serum vitamin B12 and folate concentrations are normal. Her anemia improves substantially after pharmacologic-dose thiamine. Genetic testing identifies biallelic loss-of-function variants in SLC19A2.',
 'Which cellular process is most directly impaired in this disorder?',
 {'A':'High-affinity transport of thiamine across the plasma membrane into susceptible cells','B':'Conversion of thiamine to thiamine pyrophosphate by thiamine pyrophosphokinase','C':'Transport of thiamine pyrophosphate across the inner mitochondrial membrane','D':'SLC19A3-mediated high-affinity thiamine transport across the plasma membrane','E':'Binding of thiamine pyrophosphate to the E1 subunit of pyruvate dehydrogenase'},
 'A','SLC19A2 encodes the high-affinity thiamine transporter THTR1; loss reduces cellular thiamine uptake',
 'SLC19A2 encodes thiamine transporter 1, a high-affinity plasma-membrane transporter. Loss of this transport system lowers intracellular thiamine in susceptible tissues, producing thiamine-responsive megaloblastic anemia syndrome with the characteristic anemia, diabetes, and sensorineural deafness triad.',
 {'A':'Correct. SLC19A2 loss impairs high-affinity cellular thiamine uptake through THTR1.','B':'Thiamine pyrophosphokinase acts after thiamine has entered the cell and is not encoded by SLC19A2.','C':'Mitochondrial thiamine-pyrophosphate transport is a distinct step and does not explain the SLC19A2 transport phenotype.','D':'SLC19A3 encodes a second high-affinity thiamine transporter, THTR2; it is a real alternative transport pathway but is not the mutated transporter in this patient.','E':'Binding of thiamine pyrophosphate to thiamine-dependent enzymes can be secondarily limited when intracellular thiamine is low, but it is not the primary SLC19A2 defect.'},
 'Recognize thiamine-responsive megaloblastic anemia syndrome as loss of SLC19A2/THTR1-mediated high-affinity cellular thiamine transport.',
 [{'source_id':'Q1621-GENEREVIEWS','title':'Thiamine-Responsive Megaloblastic Anemia Syndrome - GeneReviews® - NCBI Bookshelf','agency':'National Center for Biotechnology Information (NCBI), National Library of Medicine, NIH','url':'https://www.ncbi.nlm.nih.gov/books/NBK1282/','source_section_date':'2022-07-28','date_basis':'GeneReviews reports Last Update: 2022-07-28; live NCBI Bookshelf page reverified 2026-09-18.','retrieved_at':'2026-09-18','section_locator':'Molecular Pathogenesis'}],
 'D','SLC19A3/THTR2 is the strongest alternative because it is a second real high-affinity thiamine transporter. GeneReviews distinguishes the two transporters and notes tissue-specific expression; the SLC19A2 genotype and TRMA phenotype specifically identify THTR1 loss.')
