def build(make):
 return make(1630,'','Nervous System & Special Senses',['Genetics','Physiology','Toxicology'],
 'A 10-year-old boy has progressive dystonia, gait difficulty, polycythemia, and chronic liver disease. Whole-blood manganese concentration is markedly elevated, and T1-weighted brain MRI shows symmetric hyperintensity of the basal ganglia. Genetic testing identifies biallelic loss-of-function variants in SLC30A10.',
 'Which transport function is most directly impaired?',
 {'A':'Cellular manganese uptake mediated by SLC39A8','B':'Manganese uptake into hepatocytes mediated by SLC39A14','C':'Canalicular copper export mediated by ATP7B','D':'Cellular iron export mediated by ferroportin','E':'Cell-surface manganese efflux mediated by SLC30A10'},
 'E','SLC30A10 is a cell-surface manganese efflux transporter; loss of trafficking or efflux function causes cellular and systemic manganese accumulation',
 'SLC30A10 localizes to the cell surface and exports manganese, protecting cells from manganese toxicity. Disease-causing variants can prevent appropriate surface trafficking or directly impair efflux, producing hypermanganesemia with dystonia, polycythemia, and liver disease.',
 {'A':'SLC39A8 promotes manganese uptake and its deficiency causes systemic manganese deficiency with glycosylation abnormalities, the opposite metal phenotype.','B':'SLC39A14 is a manganese influx transporter important for tissue uptake; its deficiency can also cause manganese neurotoxicity but is mechanistically distinct from SLC30A10 loss.','C':'ATP7B exports copper into bile; its failure causes copper accumulation rather than isolated hypermanganesemia.','D':'Ferroportin exports iron and does not account for the characteristic manganese accumulation and SLC30A10 genotype.','E':'Correct. SLC30A10 mediates cell-surface manganese efflux, and loss of this function increases cellular manganese burden.'},
 'Recognize SLC30A10-associated hypermanganesemia as failure of cell-surface manganese efflux rather than a defect in copper, iron, or manganese-uptake pathways.',
 [{'source_id':'Q1630-PUBMED-PRIMARY','title':'SLC30A10 is a cell surface-localized manganese efflux transporter, and parkinsonism-causing mutations block its intracellular trafficking and efflux activity','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/25319704/','source_section_date':'2014-10-15','date_basis':'PubMed reports publication 2014-10-15; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'SLC30A10 is a cell surface-localized Mn efflux transporter that reduces cellular Mn levels'}],
 'B','SLC39A14 deficiency is the strongest phenotypic alternative because it also produces inherited manganese neurotoxicity. The identified SLC30A10 genotype directly specifies failure of the distinct cell-surface manganese-efflux pathway.')
