def build(make):
 return make(1635,'','Multisystem Processes & Disorders',['Biochemistry','Genetics','Molecular Biology'],
 'A 2-year-old girl has developmental regression, hypotonia, lactic acidosis, and symmetric basal-ganglia lesions consistent with Leigh syndrome. Muscle studies show combined oxidative-phosphorylation deficiency. Genetic testing identifies biallelic pathogenic variants in MTFMT, and patient fibroblasts have markedly reduced mitochondrial protein synthesis.',
 'Which reaction involving mitochondrial methionyl-tRNA is most directly impaired?',
 {'A':'Addition of the terminal CCA sequence to mitochondrial transfer RNAs','B':'Charging of mitochondrial tRNA-Met with methionine by mitochondrial methionyl-tRNA synthetase','C':'Pseudouridylation of mitochondrial ribosomal and transfer RNAs','D':'Taurine-containing wobble-base modification of selected mitochondrial transfer RNAs','E':'Formylation of mitochondrial methionyl-tRNA to generate N-formylmethionyl-tRNA used for translation initiation'},
 'E','MTFMT formylates mitochondrial Met-tRNA to generate fMet-tRNA required for efficient mitochondrial translation initiation',
 'Human mitochondria use a single tRNA-Met pool for both initiation and elongation. MTFMT formylates a portion of charged mitochondrial Met-tRNA to produce N-formylmethionyl-tRNA, the initiator species used for efficient mitochondrial translation initiation. Loss of MTFMT reduces fMet-tRNA and impairs mitochondrial protein synthesis.',
 {'A':'CCA addition is required for aminoacylation of tRNAs but is mediated by a distinct tRNA nucleotidyltransferase.','B':'MARS2 charges mitochondrial tRNA-Met with methionine; MTFMT acts after aminoacylation by adding a formyl group.','C':'Pseudouridylation is performed by RNA-modifying enzymes and is not the MTFMT-dependent modification.','D':'Taurine-containing wobble modifications affect decoding by selected mitochondrial tRNAs and are mechanistically distinct from initiator Met-tRNA formylation.','E':'Correct. MTFMT generates N-formylmethionyl-tRNA from mitochondrial Met-tRNA, enabling efficient initiation of mitochondrial translation.'},
 'Link MTFMT-associated Leigh syndrome to defective formylation of mitochondrial methionyl-tRNA and impaired mitochondrial translation initiation.',
 [{'source_id':'Q1635-PUBMED-PRIMARY','title':'Mutations in MTFMT underlie a human disorder of formylation causing impaired mitochondrial translation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/21907147/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'generate N-formylmethionine-tRNA'}],
 'B','MARS2-mediated methionine charging is the strongest pathway-level alternative because formylation requires an aminoacylated Met-tRNA substrate. MTFMT acts after charging and specifically performs the formylation step required for the initiator tRNA species.')
