def build(make):
 return make(1637,'','Nervous System & Special Senses',['Physiology','Genetics','Biochemistry'],
 'A 3-year-old boy had refractory seizures beginning on the first day of life and now has severe developmental delay and hypoplastic tooth enamel. Plasma citrate is elevated. Genetic testing identifies biallelic loss-of-function variants in SLC13A5.',
 'Which membrane transport process is most directly impaired?',
 {'A':'Citrate export from the mitochondrial matrix to the cytosol through the mitochondrial citrate carrier','B':'Sodium-coupled citrate uptake across the neuronal plasma membrane','C':'Proton-coupled lactate export through a monocarboxylate transporter','D':'Aspartate export from mitochondria in exchange for glutamate plus a proton','E':'Sodium-coupled glucose uptake through an epithelial sodium-glucose cotransporter'},
 'B','SLC13A5 encodes NaCT, a plasma-membrane sodium-dependent citrate transporter whose loss abolishes cellular citrate uptake',
 'SLC13A5 encodes the sodium-dependent citrate transporter NaCT. Pathogenic loss-of-function variants can abolish citrate uptake despite preserved synthesis of the transporter, producing neonatal-onset epilepsy, developmental impairment, and characteristic dental abnormalities.',
 {'A':'The mitochondrial citrate carrier exchanges citrate across the inner mitochondrial membrane; it is not SLC13A5 and does not mediate extracellular citrate uptake.','B':'Correct. SLC13A5/NaCT mediates sodium-coupled citrate uptake across the plasma membrane.','C':'Monocarboxylate transporters move lactate and related monocarboxylates and are distinct from NaCT-mediated citrate uptake.','D':'Citrin mediates mitochondrial aspartate-glutamate exchange and is unrelated to SLC13A5-mediated plasma-membrane citrate transport.','E':'Sodium-glucose cotransporters mediate epithelial glucose uptake and do not transport citrate.'},
 'Link SLC13A5-related developmental epilepsy to loss of NaCT-mediated sodium-coupled citrate uptake at the plasma membrane.',
 [{'source_id':'Q1637-PUBMED-PRIMARY','title':'Recessive mutations in SLC13A5 result in a loss of citrate transport and cause neonatal epilepsy, developmental delay and teeth hypoplasia','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/26384929/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'high affinity sodium-dependent citrate transporter'}],
 'A','The mitochondrial citrate carrier is the strongest substrate-level alternative because it also transports citrate. The SLC13A5 genotype and neonatal epilepsy phenotype identify NaCT-mediated plasma-membrane uptake rather than mitochondrial citrate export.')
