def build(make):
 return make(1631,'','Cardiovascular System',['Biochemistry','Genetics','Physiology'],
 'A 4-month-old boy has severe hypertrophic cardiomyopathy, muscular hypotonia, and recurrent lactic acidosis. Respiratory-chain complex activities in skeletal muscle are preserved, but isolated muscle mitochondria have markedly reduced oxidative ATP synthesis. Genetic testing identifies biallelic pathogenic variants in SLC25A3.',
 'Which mitochondrial transport process is most directly impaired?',
 {'A':'Import of inorganic phosphate from the cytosol into the mitochondrial matrix','B':'Exchange of cytosolic ADP for mitochondrial ATP through adenine nucleotide translocase','C':'Import of pyruvate from the cytosol into the mitochondrial matrix','D':'Export of mitochondrial aspartate in exchange for cytosolic glutamate plus a proton','E':'Exchange of acylcarnitine for free carnitine across the inner mitochondrial membrane'},
 'A','SLC25A3 is the mitochondrial phosphate carrier that imports inorganic phosphate into the matrix for oxidative phosphorylation',
 'SLC25A3 encodes the mitochondrial phosphate carrier. Inorganic phosphate must enter the mitochondrial matrix so ATP synthase can phosphorylate ADP. Loss of SLC25A3 therefore impairs oxidative ATP synthesis even when the respiratory-chain complexes themselves remain intact.',
 {'A':'Correct. SLC25A3 transports inorganic phosphate into the mitochondrial matrix, supplying a substrate required for ATP synthesis.','B':'Adenine nucleotide translocase exchanges matrix ATP for cytosolic ADP, but it is encoded by a different SLC25 family member and does not transport phosphate.','C':'The mitochondrial pyruvate carrier imports pyruvate for oxidation; its loss does not directly remove the phosphate substrate required by ATP synthase.','D':'Citrin/AGC2 mediates aspartate-glutamate exchange and is mechanistically distinct from the phosphate carrier.','E':'The carnitine-acylcarnitine translocase exchanges acylcarnitine and carnitine during long-chain fatty-acid oxidation; it does not supply phosphate for ATP synthesis.'},
 'Recognize SLC25A3 deficiency as impaired mitochondrial inorganic-phosphate import, limiting oxidative ATP synthesis despite preserved respiratory-chain complex activities.',
 [{'source_id':'Q1631-PUBMED-PRIMARY','title':'Mitochondrial phosphate-carrier deficiency: a novel disorder of oxidative phosphorylation','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/17273968/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'transports inorganic phosphate into the mitochondrial matrix'}],
 'B','Adenine nucleotide translocase is the strongest same-organelle alternative because ADP/ATP exchange is also essential for oxidative phosphorylation. The SLC25A3 genotype specifically identifies inorganic-phosphate import rather than nucleotide exchange.')
