def build(make):
 return make(1632,'','Nervous System & Special Senses',['Genetics','Molecular Biology','Neurology'],
 'A 10-month-old girl has congenital microcephaly, developmental delay, and recurrent intractable seizures. Cultured fibroblasts are unusually sensitive to ionizing radiation and repair induced DNA strand breaks slowly. Genetic testing identifies biallelic pathogenic variants in PNKP.',
 'Which DNA-end processing activity is most directly impaired?',
 {'A':'Removal of 8-oxoguanine from damaged DNA by a base-excision glycosylase','B':'Phosphorylation of DNA 5-prime hydroxyl ends and dephosphorylation of DNA 3-prime phosphate ends','C':'Poly-ADP-ribosylation at strand breaks to recruit repair proteins','D':'Nuclease-mediated resection of double-strand break ends to create 3-prime single-stranded overhangs','E':'ATP-dependent ligation of compatible double-strand break ends by DNA ligase IV'},
 'B','PNKP is a bifunctional DNA-end processing enzyme with 5-prime kinase and 3-prime phosphatase activities',
 'PNKP processes damaged DNA termini so they can be repaired. Its 5-prime kinase activity phosphorylates 5-prime hydroxyl ends, and its 3-prime phosphatase activity removes obstructive 3-prime phosphates, restoring termini compatible with downstream polymerase and ligase reactions. Loss of PNKP impairs DNA strand-break repair and causes microcephaly with early-onset seizures.',
 {'A':'OGG1 removes oxidized guanine bases during base-excision repair; it does not perform the dual DNA-end processing reaction of PNKP.','B':'Correct. PNKP has DNA 5-prime kinase and DNA 3-prime phosphatase activities that restore repair-compatible strand-break termini.','C':'PARP1 senses many single-strand breaks and catalyzes poly-ADP-ribosylation, but it does not provide the PNKP end-cleaning activities.','D':'MRE11-CtIP-dependent resection contributes to homologous recombination at double-strand breaks; it is not the defining PNKP reaction.','E':'DNA ligase IV seals compatible ends during nonhomologous end joining; PNKP acts upstream by converting damaged termini into ligatable 5-prime phosphate and 3-prime hydroxyl ends.'},
 'Link PNKP-associated microcephaly and seizures to defective DNA strand-break end processing caused by loss of 5-prime kinase and 3-prime phosphatase activities.',
 [{'source_id':'Q1632-PUBMED-PRIMARY','title':'Impact of PNKP mutations associated with microcephaly, seizures and developmental delay on enzyme activity and DNA strand break repair','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/22508754/','source_section_date':'2012-04-15','date_basis':'PubMed reports Epub 2012-04-15; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'DNA 5-prime kinase and DNA 3-prime phosphatase activity'}],
 'E','DNA ligase IV is the strongest pathway-level alternative because strand-break repair ultimately requires ligation. PNKP acts earlier by restoring chemically compatible DNA termini; ligase IV cannot substitute for missing 5-prime kinase and 3-prime phosphatase activity.')
