def build(make):
 return make(1633,'','Nervous System & Special Senses',['Cell Biology','Genetics','Neurology'],
 'A 17-year-old boy develops juvenile parkinsonism, pyramidal signs, and progressive cognitive decline. Genetic testing identifies biallelic loss-of-function variants in ATP13A2. Patient fibroblasts accumulate spermine within dysfunctional lysosomes and are unusually susceptible to lysosomal rupture under polyamine stress.',
 'Which transport process is most directly impaired?',
 {'A':'Export of cystine from lysosomes into the cytosol by cystinosin','B':'Egress of unesterified cholesterol from late endosomes and lysosomes through NPC1/NPC2','C':'ATP-dependent export of polyamines, especially spermine, from the lysosomal lumen to the cytosol','D':'ATP-dependent proton transport into lysosomes by the vacuolar proton pump','E':'Release of lysosomal calcium through the mucolipin-1 channel'},
 'C','ATP13A2 is a lysosomal polyamine exporter with high affinity for spermine',
 'ATP13A2 is a lysosomal P5B-type ATPase that exports polyamines from the lysosomal lumen toward the cytosol, with particularly high affinity for spermine. Loss of this transport function promotes lysosomal polyamine accumulation, lysosomal dysfunction, and vulnerability to membrane rupture, providing a mechanistic link to ATP13A2-associated juvenile parkinsonism.',
 {'A':'Cystinosin exports cystine from lysosomes and is defective in cystinosis; it is not the ATP13A2 substrate pathway.','B':'NPC1/NPC2 mediate lysosomal cholesterol egress; their loss causes Niemann-Pick type C rather than a primary polyamine-export defect.','C':'Correct. ATP13A2 exports lysosomal polyamines and shows particularly high affinity for spermine.','D':'V-ATPase acidifies lysosomes by pumping protons inward; ATP13A2 instead transports polyamines.','E':'MCOLN1/TRPML1 mediates lysosomal calcium release and is defective in mucolipidosis IV; it does not account for spermine accumulation in ATP13A2 deficiency.'},
 'Recognize ATP13A2-associated neurodegeneration as a lysosomal transport disorder in which defective polyamine, especially spermine, export disrupts lysosomal homeostasis.',
 [{'source_id':'Q1633-PUBMED-PRIMARY','title':'ATP13A2 deficiency disrupts lysosomal polyamine export','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/31996848/','source_section_date':'2020-01-29','date_basis':'PubMed reports Epub 2020-01-29; live record reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'lysosomal polyamine exporter that shows the highest affinity for spermine'}],
 'B','NPC1/NPC2-mediated lysosomal cholesterol egress is the strongest organelle-level alternative because it also causes a neurodegenerative lysosomal storage phenotype. The demonstrated spermine accumulation and ATP13A2 genotype specifically identify polyamine export.')
