def build(make):
 return make(1639,'','Musculoskeletal System',['Biochemistry','Genetics','Cell Biology'],
 'Two sisters have congenital cataracts, disproportionate short stature, spondyloepimetaphyseal dysplasia, and white-matter abnormalities. Genetic testing identifies compound heterozygous pathogenic variants in PISD. Their fibroblasts show fragmented mitochondria and reduced production of a major mitochondrial membrane phospholipid.',
 'Which biochemical reaction is most directly impaired?',
 {'A':'Exchange of serine for choline in phosphatidylcholine to synthesize phosphatidylserine in the endoplasmic reticulum','B':'CTP-dependent conversion of phosphoethanolamine to CDP-ethanolamine in the Kennedy pathway','C':'Sequential methylation of phosphatidylethanolamine to phosphatidylcholine in hepatocytes','D':'Decarboxylation of phosphatidylserine to phosphatidylethanolamine in the inner mitochondrial membrane','E':'Remodeling of immature cardiolipin acyl chains by tafazzin'},
 'D','PISD encodes mitochondrial phosphatidylserine decarboxylase, which converts phosphatidylserine to phosphatidylethanolamine in the inner mitochondrial membrane',
 'PISD is the mitochondrial phosphatidylserine decarboxylase. It converts phosphatidylserine to phosphatidylethanolamine in the inner mitochondrial membrane. Pathogenic PISD variants reduce this reaction and disrupt mitochondrial membrane composition and morphology.',
 {'A':'Phosphatidylserine synthases in the endoplasmic reticulum generate phosphatidylserine by base-exchange reactions; this is upstream of the PISD step.','B':'PCYT2 catalyzes formation of CDP-ethanolamine in the ER-based Kennedy pathway, an alternative biosynthetic route to phosphatidylethanolamine.','C':'PEMT methylates phosphatidylethanolamine to phosphatidylcholine mainly in liver and acts downstream of PE formation.','D':'Correct. PISD decarboxylates phosphatidylserine to phosphatidylethanolamine in the inner mitochondrial membrane.','E':'TAFAZZIN remodels cardiolipin and is defective in Barth syndrome; it does not catalyze phosphatidylserine decarboxylation.'},
 'Link PISD-related skeletal and neurologic disease to impaired mitochondrial conversion of phosphatidylserine into phosphatidylethanolamine.',
 [{'source_id':'Q1639-PUBMED-PRIMARY','title':'PISD is a mitochondrial disease gene causing skeletal dysplasia, cataracts, and white matter changes','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/30858161/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'converts phosphatidylserine to phosphatidylethanolamine'}],
 'B','The Kennedy pathway is the strongest alternative because it also synthesizes phosphatidylethanolamine. PISD genotype specifically identifies the mitochondrial phosphatidylserine-decarboxylation route rather than CDP-ethanolamine synthesis through the Kennedy pathway.')
