def build(make):
 return make(1634,'','Nervous System & Special Senses',['Biochemistry','Genetics','Neurology'],
 'An 8-year-old boy has early-onset spastic paraplegia, developmental delay, dysarthria, and a thin corpus callosum. Brain proton magnetic resonance spectroscopy shows an unusually large lipid signal, and imaging studies suggest widespread neuronal lipid-droplet accumulation. Genetic testing identifies biallelic loss-of-function variants in DDHD2.',
 'Which cellular metabolic defect most directly explains the lipid accumulation?',
 {'A':'Failure of lysosomal cholesteryl-ester and triglyceride hydrolysis by lysosomal acid lipase','B':'Failure of peroxisomal import and beta-oxidation of very-long-chain fatty acids','C':'Failure of lysosomal sphingomyelin degradation by acid sphingomyelinase','D':'Reduced intracellular triglyceride hydrolysis in the central nervous system, causing ectopic lipid-droplet accumulation','E':'Failure of mitochondrial cardiolipin remodeling by tafazzin'},
 'D','DDHD2 functions as a major intracellular triglyceride hydrolase in the central nervous system; loss promotes neuronal lipid-droplet accumulation',
 'DDHD2 is a serine hydrolase with important neutral-lipid lipase activity in the central nervous system. DDHD2 loss markedly reduces intracellular triglyceride hydrolysis and produces ectopic lipid-droplet accumulation in neurons, a characteristic biochemical feature of SPG54.',
 {'A':'Lysosomal acid lipase deficiency causes cholesteryl-ester and triglyceride accumulation in lysosomes, especially in liver and macrophages; it is not the DDHD2-dependent neuronal neutral-lipid defect.','B':'Peroxisomal very-long-chain fatty-acid oxidation defects cause characteristic VLCFA accumulation but do not explain the DDHD2-associated neuronal lipid-droplet phenotype.','C':'Acid sphingomyelinase deficiency causes sphingomyelin accumulation in lysosomes and is mechanistically distinct from neutral triglyceride hydrolysis by DDHD2.','D':'Correct. DDHD2 is a major CNS triglyceride hydrolase, and loss of its activity causes ectopic lipid-droplet accumulation.','E':'TAFAZZIN remodels cardiolipin in the inner mitochondrial membrane; its loss causes Barth syndrome rather than the DDHD2/SPG54 lipid-droplet phenotype.'},
 'Recognize DDHD2-associated SPG54 as a neuronal lipid-metabolism disorder in which reduced intracellular triglyceride hydrolysis causes ectopic lipid-droplet accumulation.',
 [{'source_id':'Q1634-PUBMED-PRIMARY','title':'Functional Contribution of the Spastic Paraplegia-Related Triglyceride Hydrolase DDHD2 to the Formation and Content of Lipid Droplets','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/29278326/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'principal triglyceride hydrolase in the central nervous system'}],
 'A','Lysosomal acid lipase deficiency is the strongest biochemical alternative because it also produces intracellular neutral-lipid accumulation. The DDHD2 genotype, neurologic phenotype, and neuronal lipid droplets instead localize the defect to cytosolic/CNS triglyceride hydrolysis rather than lysosomal lipid degradation.')
