def build(make):
 return make(1636,'','Nervous System & Special Senses',['Biochemistry','Genetics','Cell Biology'],
 'An 8-year-old boy has progressive behavioral deterioration, sleep disturbance, coarse facial features, and loss of previously acquired language. Urine glycosaminoglycan analysis shows excess heparan sulfate. Genetic testing identifies biallelic loss-of-function variants in HGSNAT.',
 'Which lysosomal reaction is most directly impaired?',
 {'A':'Transfer of an acetyl group from cytosolic acetyl-CoA across the lysosomal membrane to terminal alpha-glucosamine residues of heparan sulfate in the lysosomal lumen','B':'Removal of sulfate from terminal glucosamine residues of heparan sulfate by sulfamidase','C':'Hydrolysis of terminal N-acetylglucosamine residues from heparan sulfate by alpha-N-acetylglucosaminidase','D':'Export of cystine from the lysosomal lumen into the cytosol by cystinosin','E':'Addition of mannose-6-phosphate targeting signals to lysosomal hydrolases in the Golgi apparatus'},
 'A','HGSNAT catalyzes lysosomal transmembrane acetylation of terminal glucosamine residues in heparan sulfate using cytosolic acetyl-CoA',
 'HGSNAT is an integral lysosomal membrane acetyltransferase. It binds acetyl-CoA on the cytosolic side and transfers the acetyl group across the membrane to terminal glucosamine residues of heparan sulfate in the lysosomal lumen. This acetylation step is required for continued lysosomal degradation of heparan sulfate; HGSNAT deficiency causes mucopolysaccharidosis IIIC.',
 {'A':'Correct. HGSNAT couples cytosolic acetyl-CoA to acetylation of terminal glucosamine on luminal heparan sulfate.','B':'SGSH/sulfamidase removes N-sulfate groups from heparan sulfate and causes MPS IIIA when deficient; it is not the HGSNAT reaction.','C':'NAGLU removes terminal N-acetylglucosamine residues and causes MPS IIIB when deficient; HGSNAT performs the preceding acetylation step needed for further catabolism.','D':'Cystinosin exports cystine from lysosomes and is defective in cystinosis, not Sanfilippo type C.','E':'Mannose-6-phosphate tagging occurs in the Golgi and targets many soluble lysosomal enzymes; HGSNAT itself is a lysosomal membrane enzyme catalyzing transmembrane acetylation.'},
 'Recognize HGSNAT deficiency as failure of the unique transmembrane acetylation step required for lysosomal heparan-sulfate degradation.',
 [{'source_id':'Q1636-PUBMED-PRIMARY','title':'Structure and mechanism of lysosome transmembrane acetylation by HGSNAT','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/38769387/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'transfer of the acetyl group from Ac-CoA to the glucosamine group of HS'}],
 'C','NAGLU deficiency is the strongest pathway-level alternative because it also blocks heparan-sulfate degradation and causes Sanfilippo syndrome. HGSNAT genotype specifically identifies the acetylation step that prepares terminal glucosamine for subsequent glycosidase action.')
