def build(make):
 return make(1638,'','Multisystem Processes & Disorders',['Cell Biology','Genetics','Biochemistry'],
 'A 6-year-old girl has developmental delay, congenital cataracts, delayed tooth eruption, hearing loss, and metaphyseal skeletal abnormalities. Genetic testing identifies biallelic pathogenic variants in LONP1. The affected protein localizes to the mitochondrial matrix and contains ATP-binding and proteolytic domains.',
 'Which cellular function is most directly impaired?',
 {'A':'Proteolytic removal of mitochondrial targeting presequences by the mitochondrial processing peptidase','B':'ATP-dependent import of presequence-containing proteins into the mitochondrial matrix by the TIM23/PAM machinery','C':'ATP-stimulated proteolytic degradation of oxidized or abnormal proteins in the mitochondrial matrix','D':'Stress-induced cleavage of OPA1 by the inner-membrane metalloprotease OMA1','E':'Parkin-dependent ubiquitination of outer-mitochondrial-membrane proteins during mitophagy'},
 'C','LONP1 is an ATP-dependent mitochondrial matrix protease that removes oxidized and abnormal proteins as part of mitochondrial protein quality control',
 'LONP1 is a conserved ATP-dependent protease in the mitochondrial matrix. It recognizes and degrades oxidatively damaged or otherwise abnormal matrix proteins, thereby limiting their accumulation and aggregation. Biallelic LONP1 variants cause CODAS syndrome and can disrupt this mitochondrial proteostasis function.',
 {'A':'Mitochondrial processing peptidase removes targeting presequences from newly imported proteins but is distinct from LONP1-mediated quality-control proteolysis.','B':'TIM23/PAM imports many presequence-containing proteins into the matrix; it is not the protease responsible for degrading oxidized matrix proteins.','C':'Correct. LONP1 performs ATP-stimulated proteolytic degradation of damaged and abnormal mitochondrial-matrix proteins.','D':'OMA1 is an inner-membrane metalloprotease involved in stress-responsive OPA1 processing, not the matrix Lon protease.','E':'PINK1/Parkin-mediated mitophagy targets damaged mitochondria at the organelle level; it does not directly perform matrix protein proteolysis.'},
 'Recognize LONP1 as an ATP-dependent mitochondrial-matrix quality-control protease whose loss permits accumulation of oxidized and abnormal proteins.',
 [{'source_id':'Q1638-PUBMED-DISEASE','title':'Mutations in LONP1, a mitochondrial matrix protease, cause CODAS syndrome','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/25808063/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'participates in protein turnover within the mitochondrial matrix'},
  {'source_id':'Q1638-PUBMED-MECHANISM','title':'Lon protease preferentially degrades oxidized mitochondrial aconitase by an ATP-stimulated mechanism','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/12198491/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19.','retrieved_at':'2026-09-19','section_locator':'selectively recognizes and degrades the oxidized'}],
 'A','Mitochondrial processing peptidase is the strongest same-compartment alternative because it is also a matrix protease. The oxidative-protein accumulation and LONP1 genotype identify ATP-dependent quality-control proteolysis rather than presequence cleavage.')
