def build(make):
 return make(1640,'','Multisystem Processes & Disorders',['Biochemistry','Genetics','Cell Biology'],
 'An infant has severe developmental delay, seizures, failure to thrive, ichthyotic skin changes, and impaired vision. Serum transferrin is hypoglycosylated. Fibroblasts accumulate incomplete lipid-linked oligosaccharide precursors that lack mannose and glucose residues. Genetic testing identifies biallelic pathogenic variants in MPDU1.',
 'Which step in glycoprotein biosynthesis is most directly impaired?',
 {'A':'Synthesis of dolichol-phosphate-mannose from GDP-mannose by the DPM synthase complex','B':'Synthesis of GDP-mannose from mannose-1-phosphate and GTP','C':'Synthesis of dolichol-phosphate-glucose from UDP-glucose by ALG5','D':'En bloc transfer of a completed oligosaccharide from dolichol pyrophosphate to an asparagine residue by oligosaccharyltransferase','E':'Utilization of dolichol-phosphate-mannose and dolichol-phosphate-glucose donor substrates during lipid-linked oligosaccharide assembly'},
 'E','MPDU1 is required for utilization of dolichol-phosphate-mannose and dolichol-phosphate-glucose rather than for synthesis of those donor lipids',
 'MPDU1 deficiency causes a congenital disorder of glycosylation in which dolichol-phosphate-mannose and dolichol-phosphate-glucose can be synthesized but are not efficiently utilized for lipid-linked oligosaccharide assembly. The result is accumulation and transfer of incomplete oligosaccharide precursors lacking mannose and glucose residues.',
 {'A':'DPM synthase produces dolichol-phosphate-mannose; MPDU1 deficiency primarily impairs utilization of this donor rather than its biosynthesis.','B':'GDP-mannose synthesis supplies mannose nucleotide sugar upstream and is not the specific MPDU1-dependent step.','C':'ALG5 synthesizes dolichol-phosphate-glucose; MPDU1 deficiency affects use of Dol-P-Glc rather than its formation.','D':'Oligosaccharyltransferase transfers lipid-linked oligosaccharides to nascent proteins, but the MPDU1 defect occurs earlier during donor utilization and precursor assembly.','E':'Correct. MPDU1 is required for effective use of Dol-P-Man and Dol-P-Glc donor substrates in lipid-linked oligosaccharide biosynthesis.'},
 'Distinguish donor-lipid synthesis from donor-lipid utilization: MPDU1 deficiency impairs use of Dol-P-Man and Dol-P-Glc during N-linked oligosaccharide assembly.',
 [{'source_id':'Q1640-PUBMED-PRIMARY','title':'A mutation in the human MPDU1 gene causes congenital disorder of glycosylation type If (CDG-If)','agency':'PubMed, U.S. National Library of Medicine','url':'https://pubmed.ncbi.nlm.nih.gov/11733556/','source_section_date':None,'date_basis':'PubMed record live reverified 2026-09-19; no unsupported exact publication-day metadata inferred.','retrieved_at':'2026-09-19','section_locator':'affect the use, rather than the biosynthesis, of donor substrates for lipid-linked oligosaccharides'}],
 'D','Oligosaccharyltransferase is the strongest pathway-level alternative because incomplete precursors are eventually transferred to protein. The biochemical hallmark and MPDU1 genotype localize the primary lesion earlier, at utilization of Dol-P-Man and Dol-P-Glc during precursor assembly.')
